import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import OpportunitiesPage from "../../app/opportunities/page";
import { OpportunityRadarView } from "../../components/opportunity-radar/opportunity-radar-view";
import type { OpportunityRadarItem } from "../../server/read-models/opportunity-radar";
import { applyOpportunityRadarQuery, getOpportunityRadarPage, opportunityRadarHref, parseOpportunityRadarQuery, type OpportunityRadarQuery } from "../../server/opportunity-radar/get-opportunity-radar-page";

const BASE: OpportunityRadarItem = {
  opportunityId: "opp/real-1", identityKey: "stable-real-1", title: "Gulf Expansion", companyName: "Acme Electric", companyVerificationState: "VERIFIED", projectRef: "project-9", location: "Houston, TX", tradeId: "ELECTRICAL", occupationId: null, lifecycle: "ACTIVE",
  externalManpowerAcceptance: { result: "VERIFIED_POSITIVE", accepted: true, trustState: "VERIFIED", currentness: "CURRENT", qualifyingCategories: ["STAFFING"], provenanceRefs: [], reason: "fixture evidence" },
  vendorRouteState: "CANDIDATE", bestContactRouteGrade: "A", readiness: { eligible: true, eligibilityType: "HOT_A_ELIGIBLE", blockingGaps: [] }, currentness: "CURRENT", verificationState: "VERIFIED", scope: { kind: "PROJECT", companyId: null, projectId: "project-9", divisionName: null, tradeId: null }, provenanceRefs: [],
};
const DEFAULT_QUERY = parseOpportunityRadarQuery({});
const operational = (items: readonly OpportunityRadarItem[], query: OpportunityRadarQuery = DEFAULT_QUERY) => applyOpportunityRadarQuery(items, query);

describe("UI-4 Opportunity Radar", () => {
  it("renders /opportunities through the honest production boundary", async () => { const html = renderToStaticMarkup(await OpportunitiesPage()); expect(html).toContain("Opportunity Radar"); expect(html).toContain("opportunity list is not connected yet"); expect(html).not.toContain("Acme Electric"); });
  it("imports the certified UI-2 OpportunityRadarItem boundary", async () => { const source = await readFile(resolve(process.cwd(), "src/server/opportunity-radar/get-opportunity-radar-page.ts"), "utf8"); expect(source).toContain("read-models/opportunity-radar"); });
  it("does not introduce direct database access", async () => { for (const file of ["src/app/opportunities/page.tsx", "src/components/opportunity-radar/opportunity-radar-view.tsx", "src/server/opportunity-radar/get-opportunity-radar-page.ts"]) { const source = (await readFile(resolve(process.cwd(), file), "utf8")).toLowerCase(); expect(source).not.toContain("supabase"); expect(source).not.toMatch(/\.from\(["'`]|select \*|createclient\(/); } });
  it("renders supplied real read-model rows in the operational table", () => { const html = renderToStaticMarkup(<OpportunityRadarView locale="en-US" query={DEFAULT_QUERY} result={operational([BASE])} />); expect(html).toContain("Acme Electric"); expect(html).toContain("Houston, TX"); expect(html).toContain("HOT"); });
  it("renders a known empty source separately", () => { const html = renderToStaticMarkup(<OpportunityRadarView locale="en-US" query={DEFAULT_QUERY} result={operational([])} />); expect(html).toContain("No opportunities are available"); expect(html).not.toContain("not connected yet"); });
  it("keeps unavailable and unknown presentation distinct", () => { const item = { ...BASE, externalManpowerAcceptance: null, currentness: "UNKNOWN" as const }; const html = renderToStaticMarkup(<OpportunityRadarView locale="en-US" query={DEFAULT_QUERY} result={operational([item])} />); expect(html).toContain("Unavailable"); expect(html).toContain("Currentness unknown"); });
  it("does not expose unsupported enrichment filters through production URL state", () => { const query = parseOpportunityRadarQuery({ status: "hot", verification: "VERIFIED", acceptance: "accepted", currentness: "STALE" }); expect(query.state).toBe("all"); expect(query.verification).toBe("all"); expect(query.acceptance).toBe("all"); expect(query.currentness).toBe("all"); });
  it("searches supported display fields", () => { expect(applyOpportunityRadarQuery([BASE], parseOpportunityRadarQuery({ q: "houston" })).pageItems).toHaveLength(1); expect(applyOpportunityRadarQuery([BASE], parseOpportunityRadarQuery({ q: "fabricated" })).pageItems).toHaveLength(0); });
  it("parses and serializes only supported production URL state", () => { const query = parseOpportunityRadarQuery({ q: "Acme", status: "near-ready", verification: "VERIFIED", page: "2", sort: "project" }); const href = opportunityRadarHref(query, {}); expect(href).toContain("q=Acme"); expect(href).toContain("sort=project"); expect(href).toContain("page=2"); expect(href).not.toContain("status="); expect(href).not.toContain("verification="); });
  it("does not present missing enrichment as a complete commercial status", () => { const item = { ...BASE, readiness: null, externalManpowerAcceptance: null, bestContactRouteGrade: null, vendorRouteState: null }; const html = renderToStaticMarkup(<OpportunityRadarView locale="en-US" query={DEFAULT_QUERY} result={operational([item])} />); expect(html).toContain("Unavailable"); expect(html).not.toContain("Other / unknown"); });
  it("paginates at the bounded page size without fabricated totals", () => { const items = Array.from({ length: 26 }, (_, index) => ({ ...BASE, opportunityId: `opp-${index}`, identityKey: `key-${String(index).padStart(2, "0")}`, companyName: `Company ${String(index).padStart(2, "0")}` })); const page2 = applyOpportunityRadarQuery(items, parseOpportunityRadarQuery({ page: "2" })); expect(page2.pageItems).toHaveLength(1); expect(page2.filteredCount).toBe(26); expect(page2.pageCount).toBe(2); });
  it("routes rows using the real stable opportunity id", () => { const html = renderToStaticMarkup(<OpportunityRadarView locale="en-US" query={DEFAULT_QUERY} result={operational([BASE])} />); expect(html).toContain('/opportunities/opp%2Freal-1'); });
  it("renders bilingual interface copy without translating proper names", () => { const html = renderToStaticMarkup(<OpportunityRadarView locale="es-US" query={DEFAULT_QUERY} result={operational([BASE])} />); expect(html).toContain("Radar de Oportunidades"); expect(html).toContain("Acme Electric"); expect(html).toContain("Aceptación de mano de obra externa"); });
  it("returns unavailable rather than fake production rows by default", async () => { const result = await getOpportunityRadarPage(DEFAULT_QUERY); expect(result.capability).toBe("UNAVAILABLE"); expect(result.items).toEqual([]); expect(result.filteredCount).toBeNull(); });
  it("does not mutate canonical codes", () => { const before = BASE.readiness?.eligibilityType; applyOpportunityRadarQuery([BASE], parseOpportunityRadarQuery({ status: "hot" })); expect(BASE.readiness?.eligibilityType).toBe(before); expect(BASE.externalManpowerAcceptance?.result).toBe("VERIFIED_POSITIVE"); });
  it("retains labels, focusable row links, and table semantics", () => { const html = renderToStaticMarkup(<OpportunityRadarView locale="en-US" query={DEFAULT_QUERY} result={operational([BASE])} />); expect(html).toContain("<table"); expect(html).toContain('aria-label="Opportunity Radar filters"'); expect(html).toContain("Open opportunity"); });
  it("contains no human-verification write or automatic outreach behavior", async () => { const source = await readFile(resolve(process.cwd(), "src/components/opportunity-radar/opportunity-radar-view.tsx"), "utf8"); expect(source).not.toMatch(/fetch\(|useEffect|onClick|CALL_TODAY|EMAIL_TODAY/); });
});
