import type { HumanVerificationQuestionType, HumanVerificationTaskStatus } from "@/domain/human-verification";
import type { HumanVerificationPacket } from "@/domain/human-verification-planning";
import type { HumanVerificationPacketView } from "./human-verification";
import { assembleHumanVerificationPacketView } from "./human-verification";
import type { ReadModelCapabilityState, ReadModelCurrentness, ReadModelTrustState } from "./shared";
import { currentnessFromStaleAfter, mapDatabaseVerificationState } from "./shared";

export interface HumanVerificationDeskRecord { readonly id:string; readonly companyId:string; readonly companyName:string|null; readonly opportunityId:string|null; readonly opportunityTitle:string|null; readonly projectId:string|null; readonly projectName:string|null; readonly location:string|null; readonly contactName:string|null; readonly contactTitle:string|null; readonly routeType:string|null; readonly routeTarget:string|null; readonly routeTrust:string|null; readonly routeStaleAfter:Date|null; readonly targetType:string; readonly verificationObjective:string; readonly questionType:HumanVerificationQuestionType; readonly primaryQuestion:string; readonly followUpQuestion:string|null; readonly blockerCode:string|null; readonly preferredMethod:string|null; readonly status:HumanVerificationTaskStatus; readonly dueAt:Date|null; readonly createdAt:Date; readonly packetSnapshot:Record<string,unknown> }
export interface HumanVerificationDeskItem { readonly id:string; readonly companyName:string|null; readonly opportunityId:string|null; readonly opportunityTitle:string|null; readonly projectId:string|null; readonly projectName:string|null; readonly location:string|null; readonly targetType:string; readonly verificationObjective:string; readonly questionType:HumanVerificationQuestionType; readonly status:HumanVerificationTaskStatus; readonly dueAt:string|null; readonly currentness:ReadModelCurrentness; readonly nextHumanStep:string|null; readonly contact:{readonly name:string|null;readonly title:string|null;readonly routeType:string|null;readonly routeTarget:string|null;readonly trust:ReadModelTrustState|null}; readonly packetCapability:ReadModelCapabilityState }
export interface HumanVerificationDeskDetail extends HumanVerificationDeskItem { readonly exactQuestion:string; readonly followUpQuestion:string|null; readonly blockerCode:string|null; readonly packet:HumanVerificationPacketView|null }
function packet(value:Record<string,unknown>):HumanVerificationPacket|null { const question=value.question, target=value.target, task=value.task; return question&&typeof question==="object"&&typeof (question as Record<string,unknown>).primary==="string"&&target&&typeof target==="object"&&task&&typeof task==="object"?value as unknown as HumanVerificationPacket:null }
export function assembleHumanVerificationDeskItem(record:HumanVerificationDeskRecord,asOf:Date):HumanVerificationDeskItem { const snapshot=packet(record.packetSnapshot); return {id:record.id,companyName:record.companyName,opportunityId:record.opportunityId,opportunityTitle:record.opportunityTitle,projectId:record.projectId,projectName:record.projectName,location:record.location,targetType:record.targetType,verificationObjective:record.verificationObjective,questionType:record.questionType,status:record.status,dueAt:record.dueAt?.toISOString()??null,currentness:currentnessFromStaleAfter(asOf,record.dueAt),nextHumanStep:snapshot?.nextAction??record.preferredMethod,contact:{name:record.contactName,title:record.contactTitle,routeType:record.routeType,routeTarget:record.routeTarget,trust:record.routeTrust?mapDatabaseVerificationState(record.routeTrust as "UNVERIFIED"|"VERIFIED"|"REJECTED"|"STALE"):null},packetCapability:snapshot?"OPERATIONAL":"UNAVAILABLE"}; }
export function assembleHumanVerificationDeskDetail(record:HumanVerificationDeskRecord,asOf:Date):HumanVerificationDeskDetail { const item=assembleHumanVerificationDeskItem(record,asOf),snapshot=packet(record.packetSnapshot); return {...item,exactQuestion:record.primaryQuestion,followUpQuestion:record.followUpQuestion,blockerCode:record.blockerCode,packet:snapshot?assembleHumanVerificationPacketView(snapshot,record.questionType):null}; }
