import type { WorkerDemandEngagement, WorkerDemandEngagementEvent } from "../../../domain/worker-demand-engagement";
import type { SqlClient } from "../evidence/postgres-evidence-repository";
import type {
  AppendEngagementEventInput, ContactRouteFact, CreateEngagementRecordInput, EngagementContextFacts,
  EngagementProjectionPatch, WorkerDemandEngagementRepository,
} from "./worker-demand-engagement-repository";

type Row = Record<string, unknown>;
const date = (value: unknown) => value == null ? null : new Date(String(value));
const engagement = (r: Row): WorkerDemandEngagement => ({
  id:String(r.id),demandSignalId:String(r.demand_signal_id),workerId:String(r.worker_id),opportunityId:r.opportunity_id==null?null:String(r.opportunity_id),
  originatingMatchResultId:r.originating_match_result_id==null?null:String(r.originating_match_result_id),selectionState:r.selection_state as WorkerDemandEngagement["selectionState"],
  contactState:r.contact_state as WorkerDemandEngagement["contactState"],responseState:r.response_state as WorkerDemandEngagement["responseState"],
  demandAvailabilityState:r.demand_availability_state as WorkerDemandEngagement["demandAvailabilityState"],availableFrom:date(r.available_from),availableUntil:date(r.available_until),
  compensationResolutionState:r.compensation_resolution_state as WorkerDemandEngagement["compensationResolutionState"],travelResolutionState:r.travel_resolution_state as WorkerDemandEngagement["travelResolutionState"],
  mobilizationState:r.mobilization_state as WorkerDemandEngagement["mobilizationState"],closedAt:date(r.closed_at),closureReason:r.closure_reason as WorkerDemandEngagement["closureReason"],
  createdByOperatorId:String(r.created_by_operator_id),updatedByActorType:r.updated_by_actor_type as WorkerDemandEngagement["updatedByActorType"],
  updatedByOperatorId:r.updated_by_operator_id==null?null:String(r.updated_by_operator_id),version:Number(r.version),createdAt:new Date(String(r.created_at)),updatedAt:new Date(String(r.updated_at)),
});
const event = (r: Row): WorkerDemandEngagementEvent => ({
  id:String(r.id),engagementId:String(r.engagement_id),engagementVersion:Number(r.engagement_version),eventType:r.event_type as WorkerDemandEngagementEvent["eventType"],
  actorType:r.actor_type as WorkerDemandEngagementEvent["actorType"],actorOperatorId:r.actor_operator_id==null?null:String(r.actor_operator_id),occurredAt:new Date(String(r.occurred_at)),
  stateDimension:r.state_dimension as WorkerDemandEngagementEvent["stateDimension"],previousState:r.previous_state==null?null:String(r.previous_state),newState:r.new_state==null?null:String(r.new_state),
  workerContactRouteId:r.worker_contact_route_id==null?null:String(r.worker_contact_route_id),routeTypeSnapshot:r.route_type_snapshot as WorkerDemandEngagementEvent["routeTypeSnapshot"],
  consentStateSnapshot:r.consent_state_snapshot as WorkerDemandEngagementEvent["consentStateSnapshot"],routeLifecycleSnapshot:r.route_lifecycle_snapshot as WorkerDemandEngagementEvent["routeLifecycleSnapshot"],
  contactDirection:r.contact_direction as WorkerDemandEngagementEvent["contactDirection"],contactOutcome:r.contact_outcome as WorkerDemandEngagementEvent["contactOutcome"],
  availableFrom:date(r.available_from),availableUntil:date(r.available_until),matchResultId:r.match_result_id==null?null:String(r.match_result_id),
  commandIdempotencyKeyId:String(r.command_idempotency_key_id),reasonCode:r.reason_code==null?null:String(r.reason_code),notes:r.notes==null?null:String(r.notes),
  metadata:(r.metadata??{}) as Record<string,unknown>,createdAt:new Date(String(r.created_at)),
});

const ROOT_COLUMNS = `id,demand_signal_id,worker_id,opportunity_id,originating_match_result_id,selection_state,contact_state,response_state,demand_availability_state,available_from,available_until,compensation_resolution_state,travel_resolution_state,mobilization_state,closed_at,closure_reason,created_by_operator_id,updated_by_actor_type,updated_by_operator_id,version,created_at,updated_at`;
const EVENT_COLUMNS = `id,engagement_id,engagement_version,event_type,actor_type,actor_operator_id,occurred_at,state_dimension,previous_state,new_state,worker_contact_route_id,route_type_snapshot,consent_state_snapshot,route_lifecycle_snapshot,contact_direction,contact_outcome,available_from,available_until,match_result_id,command_idempotency_key_id,reason_code,notes,metadata,created_at`;

export class PostgresWorkerDemandEngagementRepository implements WorkerDemandEngagementRepository {
  constructor(private readonly client: SqlClient) {}
  async findById(id:string,forUpdate=false){const q=await this.client.query<Row>(`select ${ROOT_COLUMNS} from worker_demand_engagements where id=$1${forUpdate?" for update":""}`,[id]);return q.rows[0]?engagement(q.rows[0]):null;}
  async findByPair(demandSignalId:string,workerId:string){const q=await this.client.query<Row>(`select ${ROOT_COLUMNS} from worker_demand_engagements where demand_signal_id=$1 and worker_id=$2`,[demandSignalId,workerId]);return q.rows[0]?engagement(q.rows[0]):null;}
  async create(i:CreateEngagementRecordInput){const q=await this.client.query<Row>(`insert into worker_demand_engagements(demand_signal_id,worker_id,opportunity_id,originating_match_result_id,created_by_operator_id,updated_by_operator_id,created_at,updated_at) values($1,$2,$3,$4,$5,$5,$6,$6) returning ${ROOT_COLUMNS}`,[i.demandSignalId,i.workerId,i.opportunityId,i.originatingMatchResultId,i.operatorId,i.now]);return engagement(q.rows[0]);}
  async updateProjection(id:string,expectedVersion:number,p:EngagementProjectionPatch,actorType:"OPERATOR"|"SYSTEM",operatorId:string|null,now:Date){
    const q=await this.client.query<Row>(`update worker_demand_engagements set selection_state=coalesce($3,selection_state),contact_state=coalesce($4,contact_state),response_state=coalesce($5,response_state),demand_availability_state=coalesce($6,demand_availability_state),available_from=case when $7::boolean then $8::date else available_from end,available_until=case when $9::boolean then $10::date else available_until end,compensation_resolution_state=coalesce($11,compensation_resolution_state),travel_resolution_state=coalesce($12,travel_resolution_state),mobilization_state=coalesce($13,mobilization_state),closed_at=case when $14::boolean then $15::timestamptz else closed_at end,closure_reason=case when $16::boolean then $17 else closure_reason end,updated_by_actor_type=$18,updated_by_operator_id=$19,version=version+1,updated_at=$20 where id=$1 and version=$2 returning ${ROOT_COLUMNS}`,
      [id,expectedVersion,p.selectionState??null,p.contactState??null,p.responseState??null,p.demandAvailabilityState??null,"availableFrom" in p,p.availableFrom??null,"availableUntil" in p,p.availableUntil??null,p.compensationResolutionState??null,p.travelResolutionState??null,p.mobilizationState??null,"closedAt" in p,p.closedAt??null,"closureReason" in p,p.closureReason??null,actorType,operatorId,now]);return q.rows[0]?engagement(q.rows[0]):null;
  }
  async appendEvent(i:AppendEngagementEventInput){const q=await this.client.query<Row>(`insert into worker_demand_engagement_events(engagement_id,engagement_version,event_type,actor_type,actor_operator_id,occurred_at,state_dimension,previous_state,new_state,worker_contact_route_id,route_type_snapshot,consent_state_snapshot,route_lifecycle_snapshot,contact_direction,contact_outcome,available_from,available_until,match_result_id,command_idempotency_key_id,reason_code,notes,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22::jsonb) returning ${EVENT_COLUMNS}`,[i.engagementId,i.engagementVersion,i.eventType,i.actorType,i.actorOperatorId,i.occurredAt,i.stateDimension??null,i.previousState??null,i.newState??null,i.workerContactRouteId??null,i.routeTypeSnapshot??null,i.consentStateSnapshot??null,i.routeLifecycleSnapshot??null,i.contactDirection??null,i.contactOutcome??null,i.availableFrom??null,i.availableUntil??null,i.matchResultId??null,i.commandIdempotencyKeyId,i.reasonCode??null,i.notes??null,JSON.stringify(i.metadata??{})]);return event(q.rows[0]);}
  async listEvents(id:string){const q=await this.client.query<Row>(`select ${EVENT_COLUMNS} from worker_demand_engagement_events where engagement_id=$1 order by engagement_version`,[id]);return q.rows.map(event);}
  async getContactRoute(id:string):Promise<ContactRouteFact|null>{const q=await this.client.query<Row>(`select id,worker_id,route_type,consent_state,lifecycle_status from worker_contact_routes where id=$1`,[id]);const r=q.rows[0];return r?{id:String(r.id),workerId:String(r.worker_id),routeType:r.route_type as ContactRouteFact["routeType"],consentState:r.consent_state as ContactRouteFact["consentState"],lifecycleStatus:r.lifecycle_status as ContactRouteFact["lifecycleStatus"]}:null;}
  async getContextFacts(e:WorkerDemandEngagement):Promise<EngagementContextFacts|null>{const q=await this.client.query<Row>(`select w.lifecycle_status,o.lifecycle,d.start_date,(select r.id from worker_demand_match_results r where r.demand_signal_id=e.demand_signal_id and r.worker_id=e.worker_id and r.superseded_at is null) match_id,(select r.outcome from worker_demand_match_results r where r.demand_signal_id=e.demand_signal_id and r.worker_id=e.worker_id and r.superseded_at is null) match_outcome,exists(select 1 from worker_demand_match_results r join worker_demand_match_criteria c on c.match_result_id=r.id where r.demand_signal_id=e.demand_signal_id and r.worker_id=e.worker_id and r.superseded_at is null and c.importance='HARD' and c.state='VIOLATED') hard_violation,exists(select 1 from worker_demand_engagement_events ev where ev.engagement_id=e.id and ev.event_type='CONTACT_ATTEMPT_RECORDED' and ev.consent_state_snapshot='GRANTED' and ev.route_lifecycle_snapshot='ACTIVE') consented_contact,coalesce((select cr.consent_state='GRANTED' and cr.lifecycle_status='ACTIVE' from worker_demand_engagement_events ev join worker_contact_routes cr on cr.id=ev.worker_contact_route_id where ev.engagement_id=e.id and ev.event_type='CONTACT_ATTEMPT_RECORDED' order by ev.engagement_version desc limit 1),false) current_contact_consent from worker_demand_engagements e join workforce_workers w on w.id=e.worker_id join demand_signals d on d.id=e.demand_signal_id left join opportunities o on o.id=e.opportunity_id where e.id=$1`,[e.id]);const r=q.rows[0];if(!r)return null;return {workerLifecycle:r.lifecycle_status as EngagementContextFacts["workerLifecycle"],opportunityLifecycle:r.lifecycle==null?null:r.lifecycle as EngagementContextFacts["opportunityLifecycle"],demandStartDate:date(r.start_date),currentMatch:r.match_id==null?null:{id:String(r.match_id),outcome:r.match_outcome as NonNullable<EngagementContextFacts["currentMatch"]>["outcome"],hardViolation:Boolean(r.hard_violation)},consentedContactOccurred:Boolean(r.consented_contact),currentContactConsentGranted:Boolean(r.current_contact_consent)};}
  async getIdempotencyRecordId(key:string){const q=await this.client.query<{id:string}>(`select id from command_idempotency_keys where idempotency_key=$1`,[key]);if(!q.rows[0])throw new Error("Idempotency record missing");return q.rows[0].id;}
}
