import type{CommercialSourceDefinition,CommercialSourceEvaluation,FreshnessInput,FreshnessResult}from"../../../domain/commercial-intelligence";
export const COMMERCIAL_ACTIVATIONS:CommercialSourceDefinition[]=[
{key:"strike-midland",name:"Strike Journeyman Electrician",family:"EPC_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://strike.applytojob.com/apply/L3Wr0FKloj/Journeyman-Electrician",markets:["Midland / Odessa / Permian Basin"],decision:"ACTIVATE",reason:"Explicit industrial journeyman demand",risk:"Third-party ATS",gapsClosed:["demand","company context","Permian","schedule"],adapterId:"strike-midland-electrician",parserId:"strike-job-html",kind:"WORKFORCE_DEMAND",titlePattern:/(Journeyman Electrician)/i,organizationPattern:/(Strike)/i,locationPattern:/(Midland,? TX|Midland)/i,schedulePattern:/(Full Time)/i},
{key:"port-freeport-notices",name:"Port Freeport Public Notices",family:"PROCUREMENT_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.portfreeport.com/governance/public-notices",markets:["Freeport"],decision:"ACTIVATE",reason:"Current public construction bid and explicit owner route",risk:"Bid list changes",gapsClosed:["buyer candidate","procurement route","project","Freeport","freshness"],adapterId:"port-freeport-notices",parserId:"port-freeport-notices-html",kind:"VENDOR_ROUTE",titlePattern:/(Send us your bid|Public Notices)/i,organizationPattern:/(Port Freeport)/i,locationPattern:/(Freeport)/i,buyerPattern:/(Port Freeport)/i,contactPattern:/([\w.+-]+@portfreeport\.com)/i,schedulePattern:/(Deadline:[^.]+|accept bids until[^.]+)/i},
{key:"corpus-procurement",name:"City of Corpus Christi Procurement",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.corpuschristitx.gov/department-directory/finance-procurement/contracts-and-procurement/",markets:["Corpus Christi"],decision:"ACTIVATE",reason:"Explicit central buying agency and procurement contact",risk:"Supplier portal submission is out of scope",gapsClosed:["buyer candidate","procurement contact","vendor route","Corpus Christi"],adapterId:"corpus-procurement",parserId:"corpus-procurement-html",kind:"VENDOR_ROUTE",titlePattern:/(Contracts and Procurement)/i,organizationPattern:/(City of Corpus Christi)/i,locationPattern:/(Corpus Christi)/i,buyerPattern:/(central buying agency)/i,contactPattern:/([\w.+-]+@CorpusChristiTX\.gov)/i},
{key:"austin-industries-partners",name:"Austin Industries Partnerships",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.austin-ind.com/our-company/partnerships",markets:["Dallas–Fort Worth","Houston / Gulf Coast"],decision:"ACTIVATE",reason:"Explicit subcontractor partnerships and supplier-diversity path",risk:"Candidate requires human verification for labor scope",gapsClosed:["manpower buyer candidate","AF-01 candidate","subcontractor route"],adapterId:"austin-industries-partners",parserId:"austin-partnerships-html",kind:"PROJECT_CONTEXT",titlePattern:/(Partnerships)/i,organizationPattern:/(Austin Industries|Austin)/i,buyerPattern:/(Austin Industries|Austin)/i,af01Pattern:/(partner with subcontractors|subcontractors)/i},
{key:"freeport-lng-careers",name:"Freeport LNG Current Openings",family:"PROJECT_OWNER",tier:"DIRECT_CORPORATE",endpoint:"https://freeportlng.com/careers/current-openings",markets:["Freeport"],decision:"ACTIVATE",reason:"Current owner-side principal electrical engineering demand",risk:"Direct hiring is not manpower acceptance",gapsClosed:["demand","owner","Freeport","freshness"],adapterId:"freeport-lng-careers",parserId:"freeport-lng-careers-html",kind:"WORKFORCE_DEMAND",titlePattern:/(Principal Electrical Engineer)/i,organizationPattern:/(Freeport LNG)/i,locationPattern:/(Quintana,? TX|Freeport)/i,schedulePattern:/(Full Time)/i},
{key:"psv-industries",name:"PSV Industries Careers",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.psvindustries.com/careers",markets:["Corpus Christi","Beaumont / Port Arthur","Brownsville"],decision:"ACTIVATE",reason:"Explicit Gulf Coast industrial electrician demand and recruiter email",risk:"Company-managed page; headcount is role-specific",gapsClosed:["demand","contact route","Corpus Christi"],adapterId:"psv-industries-careers",parserId:"psv-careers-html",kind:"WORKFORCE_DEMAND",titlePattern:/(Industrial Electrician)/i,organizationPattern:/(PSV Industries)/i,locationPattern:/(Corpus Christi)/i,contactPattern:/([\w.+-]+@PSVindustries\.com)/i}
];
export const COMMERCIAL_EVALUATIONS:CommercialSourceEvaluation[]=[...COMMERCIAL_ACTIVATIONS,
{key:"peopleready-dayton",name:"PeopleReady Skilled Trades Electrician",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://skilled.peopleready.com/job/electrician-4/",markets:["Houston / Gulf Coast"],decision:"DEFER",reason:"Search result no longer matches the live endpoint",risk:"Live slug now resolves to Cincinnati, Ohio; Texas geography and compensation cannot be attributed",gapsClosed:["AF-01 candidate","compensation","staffing route","Gulf Coast"]},
{key:"nes-fircroft-odessa",name:"NES Fircroft Electrical Specialist",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.nesfircroft.com/job/electrical-specialist-iv/",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Previously explicit contract demand is no longer live",risk:"Live validation returned HTTP 410 on 2026-08-21",gapsClosed:["AF-01 candidate","compensation","schedule","Permian"]},
{key:"workintexas",name:"WorkInTexas / TWC",family:"JOB_BOARD",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.workintexas.com/",markets:["Texas"],decision:"UNDER_REVIEW",reason:"Search/session stability remains unresolved",risk:"Session-dependent navigation",gapsClosed:["compensation","headcount","schedule"]},
{key:"apple-electric",name:"Apple Electrical Contractors",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.appleelectric.com/application-2-hiring/",markets:["Odessa"],decision:"DEFER",reason:"Explicit demand but application form is not needed for capture",risk:"Personal-data form",gapsClosed:["Permian demand","phone route"]},
{key:"king-electrical",name:"King Electrical Solutions",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://kingelectricaltx.com/careers",markets:["Midland / Odessa"],decision:"DEFER",reason:"Evergreen recruiting without posting identity",risk:"Freshness ambiguity",gapsClosed:["contact route","Permian"]},
{key:"corey-sly",name:"Corey Sly Electrical",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.coreysly.com/apply",markets:["Midland / Odessa"],decision:"DEFER",reason:"Public route but weak structured economic fields",risk:"Application form",gapsClosed:["contact route","Permian"]},
{key:"willis-electric",name:"Willis Electric",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.williselectriclp.com/",markets:["Midland / Odessa"],decision:"DEFER",reason:"In-person applications only",risk:"No online posting identity",gapsClosed:["contractor identity","Permian"]},
{key:"texas-dir",name:"Texas DIR Procurement",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://dir.texas.gov/how-become-vendor",markets:["Texas"],decision:"DEFER",reason:"Explicit route but limited electrical scope",risk:"Technology procurement focus",gapsClosed:["buyer route","vendor route"]}
];
export function evaluateFreshness(x:FreshnessInput):FreshnessResult{const point=x.lastEvidenceAt??x.lastSuccessfulCapture;if(!point)return{state:"UNKNOWN",ageMinutes:null,sourceHealth:"UNKNOWN"};const age=Math.max(0,(x.asOf.getTime()-point.getTime())/60000),state=age>x.staleAfterMinutes?"STALE":"FRESH";return{state,ageMinutes:age,sourceHealth:state==="STALE"?"STALE":"HEALTHY"}}
export function hotLeadGapMetrics(items:{demand?:unknown;company?:unknown;project?:unknown;buyer?:unknown;af01?:unknown;route?:unknown;compensation?:unknown;perDiem?:unknown;headcount?:unknown;schedule?:unknown;provenance?:unknown}[]){const keys=["demand","company","project","buyer","af01","route","compensation","perDiem","headcount","schedule","provenance"]as const;return Object.fromEntries(keys.map(k=>[k,items.filter(x=>x[k]!=null).length]))}
