import type{CommercialSourceDefinition,CommercialSourceEvaluation}from"../../../domain/commercial-intelligence";
export const HOT_EVIDENCE_ACTIVATIONS:CommercialSourceDefinition[]=[
{key:"city-freeport-purchasing",name:"City of Freeport Purchasing",family:"PROCUREMENT_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.freeporttx.gov/purchasing",markets:["Freeport"],decision:"ACTIVATE",reason:"Explicit vendor participation, solicitation, contractor, and purchasing route",risk:"Registration remains a human action",gapsClosed:["buyer candidate","vendor route","contractor evidence","Freeport"],adapterId:"city-freeport-purchasing",parserId:"city-freeport-purchasing-html",kind:"VENDOR_ROUTE",titlePattern:/(Purchasing Department)/i,organizationPattern:/(City of Freeport)/i,locationPattern:/(Freeport,? TX|Freeport)/i,buyerPattern:/(City of Freeport)/i,af01Pattern:/(Contractors providing goods,? materials and services)/i,contactPattern:/((?:979)[\s()-]*233[\s-]*3526)/i},
{key:"port-arthur-procurement",name:"Port of Port Arthur Procurement",family:"PROCUREMENT_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://portpa.com/business/procurement/",markets:["Beaumont / Port Arthur"],decision:"ACTIVATE",reason:"Official contractor-assistance program and vendor registry",risk:"Registry submission remains a human action",gapsClosed:["buyer candidate","contractor services","vendor route","Port Arthur"],adapterId:"port-arthur-procurement",parserId:"port-arthur-procurement-html",kind:"VENDOR_ROUTE",titlePattern:/(Procurement)/i,organizationPattern:/(Port of Port Arthur)/i,locationPattern:/(Port Arthur)/i,buyerPattern:/(Port of Port Arthur)/i,af01Pattern:/(contractor services|participation in contracting)/i,contactPattern:/((?:409)[\s()-]*983[\s-]*2011)/i},
{key:"corpus-supplier-portal",name:"Corpus Christi Supplier Portal",family:"VENDOR_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.corpuschristitx.gov/department-directory/finance-procurement/contracts-and-procurement/supplier-portal-information/",markets:["Corpus Christi"],decision:"ACTIVATE",reason:"Official supplier registration and bid-event route",risk:"Portal account creation remains a human action",gapsClosed:["buyer candidate","supplier route","procurement opportunities","Corpus Christi"],adapterId:"corpus-supplier-portal",parserId:"corpus-supplier-portal-html",kind:"VENDOR_ROUTE",titlePattern:/(Supplier Portal Information)/i,organizationPattern:/(City of Corpus Christi)/i,locationPattern:/(Corpus Christi)/i,buyerPattern:/(City of Corpus Christi)/i,contactPattern:/(purchasing staff)/i},
{key:"tfc-vendor-compliance",name:"Texas Facilities Vendor Compliance",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://web.tfc.texas.gov/vendors/office-of-business-opportunities/vendor-reporting-and-compliance",markets:["Texas"],decision:"ACTIVATE",reason:"Explicit subcontractor payment compliance and named program contacts",risk:"Statewide rather than market-specific",gapsClosed:["subcontractor evidence","named procurement contacts","vendor route"],adapterId:"tfc-vendor-compliance",parserId:"tfc-vendor-compliance-html",kind:"VENDOR_ROUTE",titlePattern:/(Vendor Reporting and Compliance)/i,organizationPattern:/(Texas Facilities Commission)/i,buyerPattern:/(Texas Facilities Commission)/i,af01Pattern:/(subcontractors who will be paid on the project)/i,contactPattern:/([\w.+-]+@tfc\.texas\.gov)/i},
{key:"texas-dir-vendor",name:"Texas DIR Vendor and Subcontractor Guidance",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://dir.texas.gov/how-become-vendor",markets:["Texas"],decision:"ACTIVATE",reason:"Explicit prime-vendor and subcontractor approval workflow",risk:"Technology procurement scope limits electrical relevance",gapsClosed:["buyer candidate","subcontractor evidence","vendor route"],adapterId:"texas-dir-vendor",parserId:"texas-dir-vendor-html",kind:"VENDOR_ROUTE",titlePattern:/(Doing Business with DIR)/i,organizationPattern:/(Texas Department of Information Resources|DIR)/i,buyerPattern:/(DIR)/i,af01Pattern:/(Subcontractors may be added at the prime vendor's discretion)/i,contactPattern:/(DIR Contract Manager)/i}
];
export const HOT_EVIDENCE_EVALUATIONS:CommercialSourceEvaluation[]=[...HOT_EVIDENCE_ACTIVATIONS,
{key:"workintexas-2f",name:"WorkInTexas / TWC",family:"JOB_BOARD",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.workintexas.com/",markets:["Texas"],decision:"UNDER_REVIEW",reason:"No stable public query path proven",risk:"Session-dependent search controls",gapsClosed:["pay","headcount","schedule"]},
{key:"nes-texas-2f",name:"NES Fircroft Texas Assignments",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.nesfircroft.com/jobs/",markets:["Texas"],decision:"DEFER",reason:"Previously identified Texas assignment returned HTTP 410",risk:"Posting churn",gapsClosed:["pay","schedule","staffing"]},
{key:"aerotek-texas-2f",name:"Aerotek Texas Electrical Assignments",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://jobs.aerotek.com/us/en",markets:["Texas"],decision:"DEFER",reason:"Dynamic search did not expose a stable assignment endpoint",risk:"Client-rendered job inventory",gapsClosed:["pay","staffing","schedule"]},
{key:"peopleready-texas-2f",name:"PeopleReady Skilled Trades Texas",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://skilled.peopleready.com/jobs/",markets:["Texas"],decision:"DEFER",reason:"Indexed Texas slug resolved live to Ohio",risk:"Reused mutable slugs",gapsClosed:["pay","staffing","per diem"]},
{key:"strike-procurement-2f",name:"Strike Project Procurement",family:"EPC_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.strikeusa.com/projects/site-development-civil-mechanical-and-electrical-procurement-services/",markets:["Permian Basin"],decision:"DEFER",reason:"Explicit subcontractor/vendor usage but no current route",risk:"Historical project case study",gapsClosed:["buyer candidate","subcontractor evidence","Permian"]},
{key:"austin-opportunities-2f",name:"Austin Industries Subcontractor Opportunities",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.austin-ind.com/our-company/partnerships",markets:["Houston / Gulf Coast","DFW"],decision:"DEFER",reason:"Already represented by an active Phase 2D source",risk:"Duplicate evidence",gapsClosed:["AF-01","buyer candidate"]},
{key:"port-freeport-2f",name:"Port Freeport Contractor Procurement",family:"PROCUREMENT_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.portfreeport.com/governance/public-notices",markets:["Freeport"],decision:"DEFER",reason:"Already represented by an active Phase 2D source",risk:"Duplicate evidence",gapsClosed:["buyer","contact","project"]},
{key:"freeport-lng-supplier-2f",name:"Freeport LNG Supplier Programs",family:"PROJECT_OWNER",tier:"DIRECT_CORPORATE",endpoint:"https://freeportlng.com/",markets:["Freeport"],decision:"DEFER",reason:"No current public supplier onboarding program located",risk:"Insufficient explicit route",gapsClosed:["buyer","supplier route"]},
{key:"beaumont-purchasing-2f",name:"City of Beaumont Purchasing",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.beaumonttexas.gov/finance/purchasing/",markets:["Beaumont"],decision:"DEFER",reason:"Candidate retained for endpoint validation",risk:"Current route not validated",gapsClosed:["procurement","contact"]},
{key:"port-arthur-city-2f",name:"City of Port Arthur Procurement",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.portarthurtx.gov/",markets:["Port Arthur"],decision:"DEFER",reason:"Project documents exist but stable procurement index requires review",risk:"Document-centric navigation",gapsClosed:["project","subcontractor"]},
{key:"corpus-vendor-event-2f",name:"Corpus Christi Vendor Outreach",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.corpuschristitx.gov/news/posts/city-of-corpus-christi-to-host-doing-business-with-the-city-vendor-networking-and-training-event/",markets:["Corpus Christi"],decision:"DEFER",reason:"Time-bound event is past",risk:"Stale event",gapsClosed:["department contacts","vendor route"]},
{key:"txdot-contractors-2f",name:"TxDOT Contractor Information",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.dot.state.tx.us/business/contractors_consultants/contractor_information.htm",markets:["Texas"],decision:"DEFER",reason:"Explicit contractor qualification but limited electrical conversion context",risk:"Broad state program",gapsClosed:["contractor route"]}
];
export const sourceYield=(facts:{buyerCandidate:unknown;af01Candidate:unknown;contactRoute:unknown;payText:unknown;perDiem:unknown;headcount:unknown;schedule:unknown}[])=>({evidenceCaptured:facts.length,buyerCandidates:facts.filter(x=>x.buyerCandidate).length,af01Candidates:facts.filter(x=>x.af01Candidate).length,contactRoutes:facts.filter(x=>x.contactRoute).length,compensation:facts.filter(x=>x.payText).length,perDiem:facts.filter(x=>x.perDiem).length,headcount:facts.filter(x=>x.headcount).length,schedule:facts.filter(x=>x.schedule).length});
