import type{SourceCapability,SourceFamily,SourceTier}from"../../../domain/production-source";export interface SourceArchetype{family:SourceFamily;tier:SourceTier;targetMix:number;capabilities:SourceCapability[];funnelContribution:string;texasPriority:string[];liveStatus:"ARCHETYPE_ONLY"}
const markets=["Houston metro","Beaumont / Port Arthur","Freeport","Corpus Christi","Midland / Odessa / Permian Basin","Dallas–Fort Worth","Other evidence-supported Texas markets"];
export const INITIAL_SOURCE_STRATEGY:SourceArchetype[]=[
{family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",targetMix:20,capabilities:["WORKFORCE_DEMAND","COMPANY_IDENTITY","LOCATION","SCHEDULE","HEADCOUNT","PUBLICATION_CURRENTNESS"],funnelContribution:"Direct demand and company evidence",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"EPC_CONTRACTOR",tier:"DIRECT_CORPORATE",targetMix:12,capabilities:["PROJECT_EXISTENCE","COMPANY_ROLE","WORKFORCE_DEMAND"],funnelContribution:"Project and contractor context",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",targetMix:10,capabilities:["PROJECT_EXISTENCE","COMPANY_ROLE","VENDOR_ROUTE"],funnelContribution:"Buyer and vendor-route context",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",targetMix:15,capabilities:["WORKFORCE_DEMAND","STAFFING_RELATIONSHIP","CONTACT_ROUTE"],funnelContribution:"HOT-B staffing and recruiter paths",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"PROJECT_OWNER",tier:"PRIMARY_AUTHORITATIVE",targetMix:10,capabilities:["PROJECT_EXISTENCE","COMPANY_IDENTITY","COMPANY_ROLE"],funnelContribution:"Authoritative project and owner evidence",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"JOB_BOARD",tier:"STRUCTURED_PUBLIC",targetMix:10,capabilities:["WORKFORCE_DEMAND","COMPENSATION","LOCATION","PUBLICATION_CURRENTNESS"],funnelContribution:"Broad demand discovery requiring corroboration",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",targetMix:8,capabilities:["PROJECT_EXISTENCE","COMPANY_IDENTITY","PUBLICATION_CURRENTNESS"],funnelContribution:"Permits, awards, and public project evidence",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"PROCUREMENT_PORTAL",tier:"DIRECT_CORPORATE",targetMix:8,capabilities:["VENDOR_ROUTE","COMPANY_ROLE","AF01_ACCEPTANCE_EVIDENCE"],funnelContribution:"Vendor access and explicit acceptance evidence",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"},
{family:"PROJECT_NEWS",tier:"SECONDARY_REPUTABLE",targetMix:7,capabilities:["PROJECT_EXISTENCE","COMPANY_IDENTITY"],funnelContribution:"Discovery and independent corroboration",texasPriority:markets,liveStatus:"ARCHETYPE_ONLY"}];
