import type{EvaluatedSource,ExpandedSourceDefinition}from"../../../domain/multi-source";
export const ACTIVATED_EXPANSION:ExpandedSourceDefinition[]=[
{key:"tradesmen",name:"Tradesmen International",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://careers.tradesmeninternational.com/",markets:["Houston Metro","Dallas–Fort Worth","Texas"],decision:"ACTIVATE",reason:"Public skilled-trades staffing and recruiter route",capabilities:["WORKFORCE_DEMAND","STAFFING_RELATIONSHIP","CONTACT_ROUTE"],risk:"Public marketing is AF-01 candidate only",adapterId:"tradesmen-careers",parserId:"tradesmen-public-html",kind:"STAFFING_INTELLIGENCE",titlePattern:/(Skilled Trades?|Careers)/i,organizationPattern:/(Tradesmen International)/i},
{key:"exxon-beaumont",name:"ExxonMobil Beaumont Electrical Jobs",family:"PROJECT_OWNER",tier:"DIRECT_CORPORATE",endpoint:"https://jobs.exxonmobil.com/go/Electrical-Jobs-in-Beaumont/3051500/",markets:["Beaumont / Port Arthur"],decision:"ACTIVATE",reason:"Owner-side Gulf Coast electrical demand",capabilities:["WORKFORCE_DEMAND","COMPANY_IDENTITY","LOCATION"],risk:"Listing structure may change",adapterId:"exxon-beaumont-jobs",parserId:"exxon-job-list-html",kind:"WORKFORCE_DEMAND",titlePattern:/(Electrical Jobs in Beaumont|Electrician)/i,organizationPattern:/(ExxonMobil)/i,locationPattern:/(Beaumont)/i},
{key:"texas-comptroller-vendor",name:"Texas Comptroller Vendor Information",family:"PROCUREMENT_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://comptroller.texas.gov/purchasing/vendor/information.php",markets:["Texas"],decision:"ACTIVATE",reason:"Authoritative ESBD/CMBL vendor route",capabilities:["VENDOR_ROUTE","CONTACT_ROUTE"],risk:"Opportunity submissions may require registration",adapterId:"texas-comptroller-vendor",parserId:"comptroller-vendor-html",kind:"VENDOR_ROUTE",titlePattern:/(Vendor Information)/i,organizationPattern:/(Texas Comptroller|Comptroller of Public Accounts)/i},
{key:"dws-energy-careers",name:"DWS Energy Careers",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.dwsenergy.com/careers/",markets:["Dallas–Fort Worth","Houston Metro","Midland / Odessa / Permian Basin"],decision:"ACTIVATE",reason:"Explicit current electrical hiring across three priority markets",capabilities:["WORKFORCE_DEMAND","COMPANY_IDENTITY","LOCATION","CONTACT_ROUTE"],risk:"Company-managed page",adapterId:"dws-energy-careers",parserId:"dws-careers-html",kind:"WORKFORCE_DEMAND",titlePattern:/(Journeyman Electrician)/i,organizationPattern:/(DWS Energy)/i,locationPattern:/(Midland,? TX|Midland)/i},
{key:"gonzales-contractors",name:"Gonzales Contractors Careers",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.gonzalescontractors.com/careers",markets:["Midland / Odessa / Permian Basin"],decision:"ACTIVATE",reason:"Explicit Midland electrical opening and HR contact route",capabilities:["WORKFORCE_DEMAND","COMPANY_IDENTITY","CONTACT_ROUTE","LOCATION"],risk:"Company-managed page",adapterId:"gonzales-contractors-careers",parserId:"gonzales-careers-html",kind:"WORKFORCE_DEMAND",titlePattern:/(Master \/ Journeyman Electrical|Journeyman Electrician)/i,organizationPattern:/(Gonzales Contractors)/i,locationPattern:/(Midland,? TX|Midland)/i}
];
export const EVALUATED_EXPANSION:EvaluatedSource[]=[...ACTIVATED_EXPANSION,
{key:"workintexas",name:"WorkInTexas / TWC",family:"JOB_BOARD",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://www.workintexas.com/",markets:["Texas"],decision:"UNDER_REVIEW",reason:"Individual public pages work but search/session URLs are operationally unstable",capabilities:["WORKFORCE_DEMAND","COMPENSATION","HEADCOUNT"],risk:"Session-dependent navigation"},
{key:"nes-fircroft",name:"NES Fircroft",family:"STAFFING_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.nesfircroft.com/job/electrical-specialist-iv/",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Strong contract demand but current posting freshness needs confirmation",capabilities:["WORKFORCE_DEMAND","COMPENSATION","STAFFING_RELATIONSHIP"],risk:"Posting expiration"},
{key:"strike",name:"Strike",family:"EPC_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://strike.applytojob.com/apply/L3Wr0FKloj/Journeyman-Electrician",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Explicit industrial demand; defer to next adapter batch",capabilities:["WORKFORCE_DEMAND","COMPANY_ROLE"],risk:"Third-party ATS"},
{key:"king-electrical",name:"King Electrical Solutions",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://kingelectricaltx.com/careers",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Geographic presence but lower structured freshness",capabilities:["WORKFORCE_DEMAND","CONTACT_ROUTE"],risk:"Evergreen recruiting"},
{key:"apple-electric",name:"Apple Electrical Contractors",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.appleelectric.com/application-2-hiring/",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Explicit Odessa journeyman opening; application page collects personal data",capabilities:["WORKFORCE_DEMAND","CONTACT_ROUTE"],risk:"Avoid form submission"},
{key:"corey-sly",name:"Corey Sly Electrical",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",endpoint:"https://www.coreysly.com/apply",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Public hiring/contact path but limited role structure",capabilities:["CONTACT_ROUTE","LOCATION"],risk:"Application form"},
{key:"willis-electric",name:"Willis Electric",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.williselectriclp.com/",markets:["Midland / Odessa / Permian Basin"],decision:"DEFER",reason:"Contractor presence; applications in person only",capabilities:["COMPANY_IDENTITY","LOCATION"],risk:"No online posting IDs"},
{key:"tfc",name:"Texas Facilities Commission",family:"PROCUREMENT_PORTAL",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://web.tfc.texas.gov/vendors/doing-business-with-tfc",markets:["Texas"],decision:"BLOCKED",reason:"Public endpoint returned HTTP 403",capabilities:["VENDOR_ROUTE"],risk:"Access blocked"},
{key:"dir",name:"Texas DIR Procurement",family:"GOVERNMENT_PUBLIC",tier:"PRIMARY_AUTHORITATIVE",endpoint:"https://dir.texas.gov/how-become-vendor",markets:["Texas"],decision:"DEFER",reason:"Authoritative procurement route but primarily technology scope",capabilities:["VENDOR_ROUTE","PROJECT_EXISTENCE"],risk:"Lower electrical relevance"},
{key:"austin-industries",name:"Austin Industries",family:"GENERAL_CONTRACTOR",tier:"DIRECT_CORPORATE",endpoint:"https://www.austin-ind.com/careers",markets:["Dallas–Fort Worth","Gulf Coast"],decision:"DEFER",reason:"Strong contractor geography; electrical specificity not yet established",capabilities:["COMPANY_IDENTITY","COMPANY_ROLE"],risk:"Needs role-specific endpoint"}
];
export function strengthenOpportunity(parts:{sourceId:string;kind:string;evidenceId:string}[]){return{strengthened:new Set(parts.map(x=>x.sourceId)).size>=3&&new Set(parts.map(x=>x.kind)).size>=3,provenance:parts}}
