import{describe,expect,it}from"vitest";
import type{CandidateCommercialEvidence,CommercialClaimType}from"../../domain/commercial-evidence-acquisition";
import type{ConversionEvidenceInput}from"../../domain/commercial-conversion";
import type{TrackedDiscoverySignal}from"../../domain/discovery-promotion";
import{NO_ACTIONABILITY_EVIDENCE}from"../../domain/opportunity-actionability";
import{analyzeBuyerVendorIntelligence,mapAf01Candidates,previewBuyerVendorCandidate}from"../../server/services/buyer-vendor-intelligence/buyer-vendor-intelligence-service";
import{DISCOVERY_SOURCE_ORGANIZATION_PROFILES,resolveOrganizationProvenance}from"../../server/services/commercial-conversion/commercial-conversion-service";
const at=new Date("2026-08-30T12:00:00Z"),signal:TrackedDiscoverySignal={trackedId:"tracked:s",signalId:"signal:s",externalId:"s",sourceKey:"strike",sourceUrl:"https://fixture.test",title:"Journeyman Electrician",organization:"Strike",location:"Houston, TX",recognizedRoles:["JOURNEYMAN_ELECTRICIAN"],roleMatches:[{role:"JOURNEYMAN_ELECTRICIAN",phrase:"Journeyman Electrician"}],tier:"STANDARD",observedAt:at,reasons:["explicit"],ruleVersion:"fixture"};
const base=(o:Partial<ConversionEvidenceInput>={}):ConversionEvidenceInput=>({signal,evidenceIds:["listing:s"],employer:"Strike",companyRole:"PROBABLE_END_EMPLOYER",companyRoleEvidenceIds:["listing:s"],project:null,buyer:null,wage:null,perDiemOrIncentive:null,schedule:null,headcount:null,acceptance:null,contacts:[],actionability:NO_ACTIONABILITY_EVIDENCE("conversion:s"),conflicts:[],...o});
const acceptance=(state:"UNVERIFIED"|"VERIFIED"="VERIFIED")=>({id:"af01",category:"STAFFING_VENDOR_ACCEPTED",verificationState:state,accepted:true,observedAt:at,validUntil:new Date("2026-12-31"),evidenceIds:["ev:af01"]});
const route=(state:"UNVERIFIED"|"VERIFIED"="VERIFIED")=>({id:"route",organization:"Strike",function:"PROCUREMENT",routeType:"PROFESSIONAL_EMAIL",target:"p@fixture.test",gradeCandidate:"B"as const,verificationState:state,observedAt:at,staleAfter:new Date("2026-12-31"),evidenceIds:["ev:route"]});
const ev=(claim:string,claimType:CommercialClaimType="VENDOR_ONBOARDING_AVAILABLE",id=claim):CandidateCommercialEvidence=>({id:`ev:${id}`,opportunityId:"conversion:s",signalId:"signal:s",sourceOrganization:"Official",sourceUrl:"https://fixture.test/official",sourceType:"OFFICIAL_SUPPLIER_VENDOR",evidenceTier:"TIER_1_PRIMARY_AUTHORITATIVE",observedAt:at,publicationOrEffectiveDate:null,claimType,candidateClaim:claim,verificationState:"UNVERIFIED",freshUntil:new Date("2026-12-31"),conflicts:[],provenance:"official public page",acquisitionTaskId:"task",contactGradeCandidate:null});
const intel=(e:CandidateCommercialEvidence[]=[],x=base())=>analyzeBuyerVendorIntelligence(x,e,at);
describe("Phase 3B buyer and vendor-route truth boundaries",()=>{
it("1 posting employer differs from buyer",()=>expect(intel().buyerOrganizationState).toBe("UNKNOWN"));
it("2 procurement function differs from manpower buyer",()=>{const x=intel([ev("Corporate procurement manages suppliers","BUYER_FUNCTION")]);expect(x.buyerFunctionState).toBe("CANDIDATE");expect(x.buyerOrganizationState).toBe("UNKNOWN")});
it("3 supplier portal is not AF-01",()=>expect(intel([ev("Supplier portal registration")]).af01Candidates).toEqual([]));
it("4 vendor registration is not AF-01",()=>expect(intel([ev("Vendor registration available")]).af01Candidates).toEqual([]));
it("5 generic subcontractor page is not AF-01",()=>expect(intel([ev("Subcontractor information page")]).af01Candidates).toEqual([]));
for(const[n,text,category]of[[6,"accepts contingent workforce vendors","CONTINGENT_WORKFORCE_ACCEPTED"],[7,"onboards staffing vendors","STAFFING_VENDOR_ACCEPTED"],[8,"engages supplemental labor providers","SUPPLEMENTAL_LABOR_ACCEPTED"],[9,"accepts craft labor vendors","CRAFT_LABOR_VENDOR_ACCEPTED"],[10,"onboards labor subcontractors","LABOR_SUBCONTRACTING_ACCEPTED"],[11,"engages third-party recruiting firms","THIRD_PARTY_RECRUITING_ACCEPTED"]]as const)it(`${n} explicit evidence creates ${category} candidate`,()=>expect(mapAf01Candidates([ev(text,"EXTERNAL_MANPOWER_ACCEPTANCE")],at)[0].category).toBe(category));
it("12 candidate remains unverified",()=>expect(intel([ev("accepts staffing vendors","EXTERNAL_MANPOWER_ACCEPTANCE")]).af01State).toBe("CANDIDATE"));
it("13 generic contact has no authority or grade",()=>expect(intel([ev("General contact email","COMMERCIAL_CONTACT")]).vendorPaths[0]).toMatchObject({authorityExplicit:false,contactGrade:null}));
it("14 recruiter does not become buyer",()=>expect(intel([ev("Recruiter email","COMMERCIAL_CONTACT")]).buyerOrganizationState).toBe("UNKNOWN"));
it("15 source identity does not become buyer",()=>expect(intel().buyerCandidates).toEqual([]));
it("16 staffing intermediary does not become end client",()=>{const p=resolveOrganizationProvenance(null,{...DISCOVERY_SOURCE_ORGANIZATION_PROFILES.trillium,sourceUrl:"https://fixture",observedAt:at});expect(p).toMatchObject({companyRole:"STAFFING_COMPANY",staffingIntermediary:"Trillium Staffing"})});
it("17 conflicting buyer evidence is preserved",()=>{const e={...ev("Procurement","BUYER_FUNCTION"),conflicts:["buyer conflict"]};expect(intel([e]).conflicts).toContain("buyer conflict")});
it("18 conflicting AF-01 evidence is preserved",()=>{const e={...ev("accepts staffing vendors","EXTERNAL_MANPOWER_ACCEPTANCE"),conflicts:["scope conflict"]};expect(intel([e]).af01Candidates[0]).toMatchObject({state:"CONFLICTING",conflicts:["scope conflict"]})});
it("19 provenance is retained",()=>expect(intel([ev("Supplier portal")]).vendorPaths[0].provenance).toBe("official public page"));
it("20 stale evidence cannot satisfy a current gate",()=>{const e={...ev("accepts staffing vendors","EXTERNAL_MANPOWER_ACCEPTANCE"),freshUntil:new Date("2026-01-01")};expect(intel([e]).af01Candidates[0].state).toBe("STALE");expect(intel([e]).remainingBlockers).toContain("MISSING_AF01")});
it("21 same evidence is deduplicated",()=>{const e=ev("Supplier portal");expect(intel([e,e]).evidence).toHaveLength(1)});
it("22 planner and IDs are deterministic",()=>expect(intel([ev("Supplier portal")])).toEqual(intel([ev("Supplier portal")])));
it("23 verified buyer suppresses buyer blocker",()=>expect(intel([],base({buyer:"Verified Buyer"})).remainingBlockers).not.toContain("MISSING_BUYER"));
it("24 verified AF-01 suppresses AF-01 blocker",()=>expect(intel([],base({acceptance:acceptance()})).remainingBlockers).not.toContain("MISSING_AF01"));
it("25 candidate AF-01 does not suppress verified requirement",()=>expect(intel([ev("accepts staffing vendors","EXTERNAL_MANPOWER_ACCEPTANCE")]).remainingBlockers).toContain("MISSING_AF01"));
it("26 verification item is created",()=>expect(intel([ev("Supplier portal")]).verificationItems[0].kind).toBe("VERIFY_VENDOR_ROUTE"));
it("27 human decision is not auto-issued",()=>expect(intel([ev("Procurement","BUYER_FUNCTION")]).verificationItems[0].decision).toBeNull());
it("28 decision preview is non-persisting",()=>expect(previewBuyerVendorCandidate(base(),ev("Procurement","BUYER_FUNCTION")).persisted).toBe(false));
it("29 isolated buyer candidate does not unlock HOT",()=>expect(previewBuyerVendorCandidate(base(),ev("Procurement","BUYER_FUNCTION")).ifVerified.activeHot.every(h=>!h.active)).toBe(true));
it("30 isolated AF-01 candidate does not unlock HOT",()=>expect(previewBuyerVendorCandidate(base({acceptance:acceptance("UNVERIFIED")}),ev("accepts staffing vendors","EXTERNAL_MANPOWER_ACCEPTANCE")).ifVerified.activeHot.every(h=>!h.active)).toBe(true));
it("31 complete controlled verified path reaches existing HOT",()=>{const x=base({project:"Project",acceptance:acceptance(),contacts:[route()],actionability:{...NO_ACTIONABILITY_EVIDENCE("conversion:s"),explicitStatus:"OPEN"}});expect(previewBuyerVendorCandidate(x,ev("Procurement","BUYER_FUNCTION")).current.activeHot.some(h=>h.active)).toBe(true)});
it("32 no outreach",()=>expect(JSON.stringify(intel())).not.toMatch(/emailSent|formSubmitted|outreachExecuted/));
it("33 no unauthorized source activation",()=>expect(JSON.stringify(intel())).not.toMatch(/ACTIVATE|APPROVED_FOR_LIVE_CAPTURE/));
});
