import{readFile}from"node:fs/promises";import{resolve}from"node:path";import{PGlite}from"@electric-sql/pglite";import{afterAll,beforeAll,describe,expect,it}from"vitest";import type{SqlClient}from"../../server/repositories/evidence/postgres-evidence-repository";import{PostgresHumanVerificationDeskRepository}from"../../server/repositories/human-verification-desk/postgres-human-verification-desk-repository";import{assembleHumanVerificationDeskDetail}from"../../server/read-models/human-verification-desk";
const now=new Date("2026-09-05T12:00:00Z"),migrations=["20260817010000_canonical_model.sql","20260817020000_evidence_provenance.sql","20260817030000_source_registry_compliance.sql","20260817040000_controlled_ingestion.sql","20260817050000_claim_assertions.sql","20260817060000_company_resolution.sql","20260817070000_manpower_acceptance.sql","20260817080000_contacts_routes.sql","20260817090000_opportunity_graph.sql","20260817100000_human_verification.sql","20260904010000_human_verification_domain.sql"];
describe("UI-6 persisted verification queue",()=>{let db:PGlite,repo:PostgresHumanVerificationDeskRepository;beforeAll(async()=>{db=new PGlite();for(const m of migrations)await db.exec(await readFile(resolve(process.cwd(),"supabase/migrations",m),"utf8"));repo=new PostgresHumanVerificationDeskRepository(db as unknown as SqlClient)});afterAll(async()=>db.close());it("returns a known empty persisted queue",async()=>expect(await repo.list()).toEqual({items:[],total:0}));it("retrieves stable identity, relationships, route, and exact packet",async()=>{
  const c=(await db.query<{id:string}>("insert into companies(common_name)values('Persisted Electric')returning id")).rows[0],p=(await db.query<{id:string}>("insert into projects(name,location_text)values('Grid Project','Houston, TX')returning id")).rows[0],o=(await db.query<{id:string}>("insert into opportunities(title,project_id,lifecycle,opportunity_identity_key)values('Grid demand',$1,'ACTIVE','grid-task')returning id",[p.id])).rows[0];
  const person=(await db.query<{id:string}>("insert into contact_people(company_id,name,verification_state)values($1,'Pat Buyer','UNVERIFIED')returning id",[c.id])).rows[0],route=(await db.query<{id:string}>("insert into contact_routes(company_id,contact_person_id,route_type,target,observed_target,normalized_target,verification_state)values($1,$2,'CORPORATE_PHONE','555-0199','555-0199','5550199','UNVERIFIED')returning id",[c.id,person.id])).rows[0];
  const snapshot={task:{id:null,status:"PLANNED",createdAt:null,dueAt:null,assignedOperatorId:null,verificationObjective:"Verify route"},target:{companyId:c.id,companyName:"Persisted Electric",projectId:p.id,projectName:"Grid Project",opportunityId:o.id,opportunityTitle:"Grid demand",tradeId:null,occupationId:null,person:null},whyThisMatters:{blocker:"ROUTE_UNKNOWN",commercialQuestion:"Verify route",currentCanonicalState:"UNRESOLVED",publicEvidenceInsufficientReason:"exhausted"},question:{primary:"Who owns this route?",followUp:null},expectedClassifications:{answerDispositions:[],commercialMechanisms:[]},authorityRequired:{minimumLevel:"ROUTING_ONLY",evidenceToCapture:[],warning:"Capture basis"},scopeToConfirm:{projectId:p.id},possibleEffects:[],sourceBasis:[],conflicts:[],doNotClaim:[],safetyPrivacy:[],nextAction:"CALL"};
  const task=(await db.query<{id:string}>("insert into human_verification_tasks(company_id,opportunity_id,project_id,contact_person_id,contact_route_id,target_type,target_id,verification_objective,question_type,primary_question,scope,packet_snapshot,deduplication_key,status,created_by,rule_version,created_at)values($1,$2,$3,$4,$5,'CONTACT_ROUTE',$5,'Verify route','CONTACT_ROUTE','Who owns this route?','{}',$6,'stable-task','OPEN','tester','v1',$7)returning id",[c.id,o.id,p.id,person.id,route.id,JSON.stringify(snapshot),now.toISOString()])).rows[0];
  const listed=await repo.list(),loaded=await repo.get(task.id);expect(listed.total).toBe(1);expect(listed.items[0]).toMatchObject({id:task.id,companyName:"Persisted Electric",projectName:"Grid Project",contactName:"Pat Buyer",routeTarget:"555-0199"});expect(assembleHumanVerificationDeskDetail(loaded!,now).exactQuestion).toBe("Who owns this route?");
})});
