import {createHash} from "node:crypto";
import type {ContactPersonCandidate,ContactRouteCandidate,ContactRouteGrade,ContactRouteRecord,RouteGradeInput} from "../../../domain/contact";
import type {ContactRepository} from "../../repositories/contact/contact-repository";
export const CONTACT_GRADE_RULE_VERSION="contact-route-grade@1.0.0";
export const normalizePersonName=(v:string)=>v.normalize("NFKC").toLocaleLowerCase("en-US").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
export function normalizeRouteTarget(type:ContactRouteCandidate["routeType"],target:string){const v=target.trim();if(type.includes("EMAIL"))return v.toLocaleLowerCase("en-US");if(type.includes("PHONE")){const digits=v.replace(/\D/g,"");return digits.length===10?`+1${digits}`:digits.length===11&&digits.startsWith("1")?`+${digits}`:v;}if(type.includes("PROFILE")||type.includes("PORTAL")||type==="VENDOR_REGISTRATION"||type==="CONTACT_FORM"){try{const u=new URL(v);u.hash="";u.hostname=u.hostname.toLowerCase();return u.toString().replace(/\/$/,"");}catch{return v;}}return v;}
export class ContactService{
 constructor(private readonly repository:ContactRepository,private readonly clock:()=>Date=()=>new Date()){}
 async createPerson(c:ContactPersonCandidate){if((c.verificationState??"UNVERIFIED")==="VERIFIED"&&!c.evidenceId)throw new Error("Verified contact person requires evidence");if((c.languageStatus??"UNKNOWN")!=="UNKNOWN"&&!c.languageEvidenceId)throw new Error("Confirmed language requires explicit evidence");const n=normalizePersonName(c.fullName);const discriminator=c.professionalProfileUrl?normalizeRouteTarget("PROFESSIONAL_PROFILE",c.professionalProfileUrl):`${c.title??""}|${c.contactFunction}|${c.evidenceId??crypto.randomUUID()}`;const key=createHash("sha256").update(`${c.companyId}|${n}|${discriminator}`).digest("hex");const p=await this.repository.upsertPerson(c,n,key);if(c.evidenceId)await this.repository.linkEvidence("CONTACT_PERSON",p.id,c.evidenceId);return p;}
 async createRoute(c:ContactRouteCandidate){if((c.verificationState??"UNVERIFIED")==="VERIFIED"&&(!c.evidenceId||!c.lastVerifiedAt))throw new Error("Verified contact route requires evidence and verification time");const r=await this.repository.upsertRoute(c,normalizeRouteTarget(c.routeType,c.target));if(c.evidenceId)await this.repository.linkEvidence("CONTACT_ROUTE",r.id,c.evidenceId);return r;}
 async grade(input:RouteGradeInput){const at=input.evaluatedAt??this.clock();const r=input.route;let grade:ContactRouteGrade="E";let reason="Route is unverified or insufficient for a current professional path";const current=r.verificationState==="VERIFIED"&&r.evidenceId!==null&&r.lifecycle!=="DISABLED"&&r.lifecycle!=="STALE"&&(r.staleAfter===null||r.staleAfter>at);const direct=["PROFESSIONAL_PHONE","PROFESSIONAL_EMAIL"].includes(r.routeType);const relevant=["WORKFORCE","PROCUREMENT","SUBCONTRACTS","SUPPLIER_MANAGEMENT","PROJECT_MANAGEMENT","CONSTRUCTION_MANAGEMENT","OPERATIONS"].includes(input.personFunction??"");if(!current){grade="E";reason="Route is not current and verified";}else if(direct&&relevant&&input.authorityExplicit===true){grade="A";reason="Verified direct professional route with explicit relevant decision-path authority";}else if((["PROCUREMENT_PHONE","PROCUREMENT_EMAIL"].includes(r.routeType)||(direct&&relevant))){grade="B";reason=`Verified relevant department or professional route${input.manpowerAcceptance==="VERIFIED"?" with verified manpower acceptance context":""}`;}else if(["CORPORATE_PHONE","CORPORATE_EMAIL","SUPPLIER_PORTAL","VENDOR_REGISTRATION"].includes(r.routeType)){grade="C";reason="Verified official company route without named decision authority";}else if(["RECRUITER_PHONE","RECRUITER_EMAIL","OFFICE_PHONE","CONTACT_FORM"].includes(r.routeType)||r.target.toLowerCase().includes("careers@")){grade="D";reason="Verified operational or recruiting route with weak B2B authority";}return this.repository.saveGrade({contactRouteId:r.id,grade,reason,ruleVersion:CONTACT_GRADE_RULE_VERSION,evaluatedAt:at,inputs:{routeType:r.routeType,personFunction:input.personFunction??null,authorityExplicit:input.authorityExplicit??false,manpowerAcceptance:input.manpowerAcceptance??null}});}
 async currentGrade(route:ContactRouteRecord){if(route.staleAfter!==null&&route.staleAfter<=this.clock())return "E" as const;return route.routeGrade;}
}
