import{describe,expect,it}from"vitest";
import type{ConversionEvidenceInput}from"../../domain/commercial-conversion";
import{NO_ACTIONABILITY_EVIDENCE}from"../../domain/opportunity-actionability";
import type{ProductionObservation}from"../../domain/production-capture";
import{conversionGraph,convertDiscoverySignal}from"../../server/services/commercial-conversion/commercial-conversion-service";
import{runListingDiscovery}from"../../server/services/discovery/listing-discovery-service";
import{SOURCE_PORTFOLIO_INVENTORY,phase2kSummary,reconstructTrueInventory}from"../../server/services/production-source/source-portfolio-audit-2k-service";

const at=new Date("2026-08-30T12:00:00Z");
const observation=(externalId:string,title:string|null="Journeyman Electrician",sourceUrl="https://fixture.test/source-a"):ProductionObservation=>{const electrical=title!==null&&/electrician/i.test(title);return{kind:"WORKFORCE_DEMAND",title,organization:"Controlled Electrical Employer",location:"Houston, TX",sourceUrl,externalId,facts:{explicitElectricalRole:electrical,recognizedElectricalRoles:electrical?"JOURNEYMAN_ELECTRICIAN":null,rawListingText:title}}};
function input(id:string,overrides:Partial<ConversionEvidenceInput>={}):ConversionEvidenceInput{const signal=runListingDiscovery([observation(id)],{sourceKey:"controlled-source",listingUrl:"https://fixture.test/source-a",observedAt:at}).tracked[0];if(!signal)throw new Error("controlled electrical fixture was not tracked");return{signal,evidenceIds:[`evidence:${id}`],employer:"Controlled Electrical Employer",companyRole:"PROBABLE_END_EMPLOYER",companyRoleEvidenceIds:[`evidence:${id}`],project:null,buyer:null,wage:null,perDiemOrIncentive:null,schedule:null,headcount:null,acceptance:null,contacts:[],actionability:NO_ACTIONABILITY_EVIDENCE(`conversion:${id}`),conflicts:[],...overrides}}
const acceptance=(id:string)=>({id:`acceptance:${id}`,category:"STAFFING_VENDOR_ACCEPTED",verificationState:"VERIFIED"as const,accepted:true,observedAt:at,validUntil:new Date("2026-12-31"),evidenceIds:[`evidence:acceptance:${id}`]});
const route=(id:string)=>({id:`route:${id}`,organization:"Controlled Electrical Employer",function:"PROCUREMENT",routeType:"PROFESSIONAL_EMAIL",target:"procurement@fixture.test",gradeCandidate:"B"as const,verificationState:"VERIFIED"as const,observedAt:at,staleAfter:new Date("2026-12-31"),evidenceIds:[`evidence:route:${id}`]});
const complete=(id:string)=>input(id,{project:"Controlled Project",acceptance:acceptance(id),contacts:[route(id)]});

describe("Phase 2T deterministic end-to-end closure certification",()=>{
  it("reconstructs the frozen production portfolio without broadening source decisions",()=>{const recon=reconstructTrueInventory(),summary=phase2kSummary(),find=(pattern:RegExp)=>SOURCE_PORTFOLIO_INVENTORY.filter(x=>pattern.test(`${x.key} ${x.name}`));expect(recon).toMatchObject({rawEntries:27,uniqueByEndpoint:25});expect(recon.duplicates).toHaveLength(2);expect(SOURCE_PORTFOLIO_INVENTORY).toHaveLength(recon.registryEntriesTotal);expect(find(/tradesmenup/i).every(x=>x.decision==="UNDER_REVIEW")).toBe(true);expect(find(/rosendin/i).every(x=>x.portfolioValue==="BLOCKED")).toBe(true);expect(find(/bechtel/i).some(x=>x.decision==="ACTIVATE")).toBe(true);console.log("PHASE_2T_PORTFOLIO="+JSON.stringify({registryEntries:recon.registryEntriesTotal,activatedEntries:recon.rawEntries,uniqueActivatedEndpoints:recon.uniqueByEndpoint,duplicateEndpointGroups:recon.duplicates.length,inventory:{highValue:summary.inventoryHighValue,supporting:summary.inventorySupporting,lowYield:summary.inventoryLowYield,underReview:summary.inventoryUnderReview,blocked:summary.inventoryBlocked,retired:summary.inventoryRetired},activated:{highValue:summary.portfolioHighValue,supporting:summary.portfolioSupporting,lowYield:summary.portfolioLowYield,underReview:summary.portfolioUnderReview,blocked:summary.portfolioBlocked,retired:summary.portfolioRetired}}))});
  it("case 1: discovered electrical demand remains commercially blocked",()=>{const x=input("blocked"),d=convertDiscoverySignal(x);expect(x.signal.trackedId).toBe("tracked-discovery:blocked");expect(d.verificationQueue.length).toBeGreaterThan(0);expect(d.eligibility.every(e=>!e.eligible)).toBe(true);expect(d.activeHot.every(h=>!h.active)).toBe(true)});
  it("case 2: verified commercial path remains inactive when temporal state is UNKNOWN",()=>{const d=convertDiscoverySignal(complete("unknown"));expect(d.eligibility.some(e=>e.eligible)).toBe(true);expect(d.temporalState).toBe("UNKNOWN");expect(d.activeHot.every(h=>!h.active)).toBe(true)});
  it("case 3: full controlled evidence reaches the real Active HOT path",()=>{const x=complete("active");x.actionability={...x.actionability,explicitStatus:"OPEN",explicitStatusFreshUntil:new Date("2026-09-30"),evidenceIds:["evidence:open"]};const d=convertDiscoverySignal(x);expect(d.eligibility.some(e=>e.eligible)).toBe(true);expect(d.score.state).toBe("SCORED");expect(typeof d.commercialAction).toBe("string");expect(d.activeHot.some(h=>h.active)).toBe(true)});
  it("case 4: expired opportunity cannot remain Active HOT",()=>{const x=complete("expired");x.actionability={...x.actionability,deadlines:[{kind:"ORIGINAL",date:new Date("2026-08-29"),observedAt:new Date("2026-08-20"),evidenceIds:["evidence:deadline"]}]};const d=convertDiscoverySignal(x);expect(d.temporalState).toBe("EXPIRED");expect(d.activeHot.every(h=>!h.active)).toBe(true)});
  it("case 5: conflict remains visible and blocks Active HOT",()=>{const x=complete("conflict");x.conflicts=["authoritative sources disagree on company role"];x.actionability={...x.actionability,explicitStatus:"OPEN",explicitStatusFreshUntil:new Date("2026-09-30")};const d=convertDiscoverySignal(x);expect(d.conflicts).toEqual(x.conflicts);expect(d.eligibility.every(e=>!e.eligible)).toBe(true);expect(d.activeHot.every(h=>!h.active)).toBe(true)});
  it("case 6: candidate-only AF-01/contact evidence cannot clear verified gates",()=>{const id="candidate",d=convertDiscoverySignal(input(id,{project:"Controlled Project",acceptance:{...acceptance(id),verificationState:"UNVERIFIED"},contacts:[{...route(id),verificationState:"UNVERIFIED"}]}));expect(d.acceptance?.verificationState).toBe("UNVERIFIED");expect(d.contacts[0]?.verificationState).toBe("UNVERIFIED");expect(d.eligibility.every(e=>!e.eligible)).toBe(true);expect(d.activeHot.every(h=>!h.active)).toBe(true)});
  it("deduplicates evidence and repeats graph/dossier identity deterministically",()=>{const x=input("stable",{evidenceIds:["evidence:stable","evidence:stable"]});expect(conversionGraph(x).opportunity.identityKey).toBe("conversion:stable");expect(convertDiscoverySignal(x)).toEqual(convertDiscoverySignal(x));expect(convertDiscoverySignal(x).evidenceIds).toEqual(["evidence:stable"])});
});

describe("Phase 2T deterministic 1,000-observation stress certification",()=>{
  it("deduplicates and converts two sources without crashes or duplicate explosion",()=>{const make=(source:"a"|"b")=>Array.from({length:500},(_,i)=>{const n=i%450,title=n%10===0?null:n%3===0?"Journeyman Electrician":"Pipefitter";return observation(`${source}-${n}`,title,`https://fixture.test/source-${source}`)}),a=make("a"),b=make("b");const execute=()=>{const runs=([["stress-a",a],["stress-b",b]]as const).map(([sourceKey,rows])=>runListingDiscovery(rows,{sourceKey,listingUrl:`https://fixture.test/${sourceKey}`,observedAt:at})),tracked=runs.flatMap(r=>r.tracked),dossiers=tracked.map(signal=>convertDiscoverySignal({...input(`template-${signal.externalId}`),signal,evidenceIds:[`evidence:${signal.externalId}`]}));return{processed:a.length+b.length,deduplicated:runs.reduce((n,r)=>n+r.duplicatesSuppressed,0),electricalRecognized:tracked.length,dossiersCreated:dossiers.length,failures:0,stableIds:tracked.map(x=>x.externalId),dossierIds:dossiers.map(x=>x.sourceExternalId),verificationCounts:dossiers.map(x=>x.verificationQueue.length),eligibility:dossiers.map(x=>x.eligibility.map(e=>e.eligible)),actionability:dossiers.map(x=>x.temporalState)}};const started=performance.now(),first=execute(),elapsedMs=performance.now()-started,second=execute();expect(first).toEqual(second);expect(first).toMatchObject({processed:1000,deduplicated:100,electricalRecognized:270,dossiersCreated:270,failures:0});expect(new Set(first.stableIds).size).toBe(first.stableIds.length);expect(new Set(first.dossierIds).size).toBe(first.dossierIds.length);console.log("PHASE_2T_STRESS="+JSON.stringify({processed:first.processed,deduplicated:first.deduplicated,electricalRecognized:first.electricalRecognized,dossiersCreated:first.dossiersCreated,failures:first.failures,elapsedMs:Number(elapsedMs.toFixed(2)),deterministicRepeat:true}))});
});
