import { getProductionSqlClient } from "../database/production-sql-client";
import { PostgresOpportunityRepository } from "../repositories/opportunity/postgres-opportunity-repository";
import { assembleOpportunityIntelligenceDetail, type OpportunityIntelligenceDetail } from "../read-models/opportunity-detail";
import { loadOpportunityEconomics } from "./get-opportunity-economics";
import type { OpportunityEconomicsDetail } from "../read-models/economics";
import { loadOpportunityEconomicDecisions } from "./get-opportunity-economic-decisions";
import type { OpportunityEconomicDecisionDetail } from "../read-models/economic-decisions";
export type OpportunityDetailPageResult = { readonly state: "READY"; readonly detail: OpportunityIntelligenceDetail; readonly economics: OpportunityEconomicsDetail | null; readonly economicDecisions: OpportunityEconomicDecisionDetail | null } | { readonly state: "NOT_FOUND" | "UNAVAILABLE" | "ERROR"; readonly detail: null; readonly economics: null; readonly economicDecisions: null; readonly reason: string };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
/** Phase 4L composition seam: attaches the canonical Phase 4K projection without inspecting, deriving, or reordering decisions. */
export function composeOpportunityDetailResult(detail: OpportunityIntelligenceDetail, economics: OpportunityEconomicsDetail | null, economicDecisions: OpportunityEconomicDecisionDetail | null): OpportunityDetailPageResult { return { state: "READY", detail, economics, economicDecisions }; }
export async function loadOpportunityDetail(id: string): Promise<OpportunityDetailPageResult> { if (!UUID.test(id)) return { state: "NOT_FOUND", detail: null, economics: null, economicDecisions: null, reason: "INVALID_OPPORTUNITY_ID" }; const client = getProductionSqlClient(); if (!client) return { state: "UNAVAILABLE", detail: null, economics: null, economicDecisions: null, reason: "DATABASE_CONNECTION_UNAVAILABLE" }; const repository = new PostgresOpportunityRepository(client), asOf = new Date(); try { const [graph, snapshots, economics, economicDecisions] = await Promise.all([repository.loadGraph(id, asOf), repository.listCompleteness(id), loadOpportunityEconomics(id).catch(() => null), loadOpportunityEconomicDecisions(id)]); const latest = snapshots.at(-1); return composeOpportunityDetailResult(assembleOpportunityIntelligenceDetail({ ...graph, gaps: latest?.gaps ?? [], conflicts: latest?.conflicts ?? [] }, asOf), economics, economicDecisions); } catch (error) { return error instanceof Error && error.message === "Opportunity not found" ? { state: "NOT_FOUND", detail: null, economics: null, economicDecisions: null, reason: "OPPORTUNITY_NOT_FOUND" } : { state: "ERROR", detail: null, economics: null, economicDecisions: null, reason: "OPPORTUNITY_QUERY_FAILED" }; } }
export async function getOpportunityDetailPage(id: string, load: (id: string) => Promise<OpportunityDetailPageResult> = loadOpportunityDetail) { try { return await load(id); } catch { return { state: "ERROR", detail: null, economics: null, economicDecisions: null, reason: "OPPORTUNITY_QUERY_FAILED" } as const; } }
