import type{ExternalManpowerCategory}from"./database";
import type{CandidateCommercialEvidence}from"./commercial-evidence-acquisition";
export const BUYER_VENDOR_INTELLIGENCE_RULE_VERSION="buyer-vendor-intelligence@1.0.0";
export const BUYER_FUNCTIONS=["PROCUREMENT","PURCHASING","STRATEGIC_SOURCING","SUPPLY_CHAIN","VENDOR_MANAGEMENT","CONTINGENT_WORKFORCE","WORKFORCE_PROCUREMENT","SUBCONTRACTING","CONSTRUCTION_PROCUREMENT","PROJECT_PROCUREMENT","LABOR_PROCUREMENT","SUPPLIER_RELATIONS","UNKNOWN"]as const;
export type BuyerFunction=(typeof BUYER_FUNCTIONS)[number];
export type BuyerEvidenceState="UNKNOWN"|"CANDIDATE"|"VERIFIED"|"CONFLICTING"|"STALE"|"REJECTED";
export type VendorPathType="SUPPLIER_PORTAL"|"VENDOR_REGISTRATION"|"SUBCONTRACTOR_REGISTRATION"|"STAFFING_VENDOR_ONBOARDING"|"CONTINGENT_WORKFORCE_PROGRAM"|"CRAFT_LABOR_VENDOR_PROGRAM"|"SUPPLEMENTAL_LABOR_PROGRAM"|"THIRD_PARTY_RECRUITING_PROGRAM"|"LABOR_SUBCONTRACTING_PROGRAM"|"PROCUREMENT_CONTACT_ROUTE"|"GENERAL_SUPPLIER_ROUTE"|"UNKNOWN";
export interface BuyerCandidate{id:string;organization:string|null;function:BuyerFunction;state:BuyerEvidenceState;evidenceId:string;provenance:string;conflicts:string[];freshUntil:Date|null;authorityExplicit:boolean}
export interface VendorPathCandidate{id:string;pathType:VendorPathType;state:BuyerEvidenceState;evidenceId:string;provenance:string;authorityExplicit:boolean;contactGrade:null;conflicts:string[];freshUntil:Date|null}
export interface Af01Candidate{id:string;category:ExternalManpowerCategory;state:"CANDIDATE"|"CONFLICTING"|"STALE";evidenceId:string;sourceUrl:string;provenance:string;supportStrength:"EXPLICIT"|"STRONG";basis:string;whyUnverified:string;conflicts:string[];freshUntil:Date|null;humanReviewRequired:true}
export interface BuyerVendorVerificationItem{id:string;kind:"VERIFY_BUYER_ORGANIZATION"|"VERIFY_BUYER_FUNCTION"|"VERIFY_VENDOR_ROUTE"|"VERIFY_AF01_CATEGORY"|"VERIFY_CONTACT_AUTHORITY"|"VERIFY_ORGANIZATION_RELATIONSHIP";candidateFact:string;evidenceIds:string[];conflicts:string[];currentState:string;decisionRequired:string;impactIfVerified:string;impactIfRejected:string;remainingBlockers:string[];decision:null}
export interface BuyerVendorIntelligence{opportunityId:string;sourceOrganization:string|null;postingEmployer:string|null;staffingIntermediary:string|null;dispatchContractor:string|null;buyerOrganizationState:BuyerEvidenceState;buyerFunctionState:BuyerEvidenceState;buyerCandidates:BuyerCandidate[];vendorPathState:BuyerEvidenceState;vendorPaths:VendorPathCandidate[];af01State:BuyerEvidenceState;af01Candidates:Af01Candidate[];contactRouteState:BuyerEvidenceState;conflicts:string[];verificationItems:BuyerVendorVerificationItem[];evidence:CandidateCommercialEvidence[];remainingBlockers:string[];ruleVersion:string}
