import type{EvidenceVerificationState}from"./commercial-conversion";

export const COMMERCIAL_EVIDENCE_ACQUISITION_RULE_VERSION="commercial-evidence-acquisition@1.0.0";
export type CommercialEvidenceDimension="BUYER"|"AF01"|"CONTACT"|"TEMPORAL"|"PROJECT"|"HEADCOUNT"|"SCHEDULE"|"DURATION"|"ECONOMICS";
export type CommercialEvidenceGap="MISSING_BUYER"|"MISSING_BUYER_FUNCTION"|"MISSING_AF01"|"MISSING_ACTIONABLE_CONTACT"|"MISSING_CONTACT_AUTHORITY"|"MISSING_TEMPORAL_STATUS"|"MISSING_PROJECT"|"MISSING_PROJECT_RELATIONSHIP"|"MISSING_HEADCOUNT"|"MISSING_SCHEDULE"|"MISSING_DURATION"|"MISSING_ECONOMICS";
export type AcquisitionTaskType="FIND_EXTERNAL_MANPOWER_POLICY"|"FIND_BUYER_FUNCTION"|"FIND_VENDOR_ONBOARDING"|"FIND_COMMERCIAL_CONTACT"|"FIND_PROJECT_CONTEXT"|"VERIFY_TEMPORAL_STATUS"|"FIND_HEADCOUNT"|"FIND_SCHEDULE"|"FIND_DURATION"|"FIND_ECONOMICS";
export type EvidenceTier="TIER_1_PRIMARY_AUTHORITATIVE"|"TIER_2_STRONG_SUPPORTING"|"TIER_3_DISCOVERY_LEAD";
export type EvidenceSourceType="OFFICIAL_PROCUREMENT"|"OFFICIAL_SUPPLIER_VENDOR"|"OFFICIAL_CONTINGENT_WORKFORCE"|"OFFICIAL_SUBCONTRACTOR_ONBOARDING"|"OFFICIAL_PROJECT"|"OFFICIAL_BID_DOCUMENT"|"OFFICIAL_CORPORATE_CONTACT"|"OFFICIAL_CAREER_POSTING"|"GOVERNMENT_PUBLIC_RECORD"|"UNION_DISPATCH"|"PROFESSIONAL_CORPORATE_PAGE"|"STAFFING_POSTING"|"JOB_AGGREGATOR"|"TRADE_PUBLICATION";
export type CommercialClaimType="BUYER_ORGANIZATION"|"BUYER_FUNCTION"|"EXTERNAL_MANPOWER_ACCEPTANCE"|"VENDOR_ONBOARDING_AVAILABLE"|"COMMERCIAL_CONTACT"|"CONTACT_AUTHORITY"|"PROJECT_IDENTITY"|"PROJECT_RELATIONSHIP"|"TEMPORAL_STATUS"|"HEADCOUNT"|"SCHEDULE"|"DURATION"|"ECONOMICS";
export interface EvidenceAcquisitionTask{id:string;taskType:AcquisitionTaskType;opportunityId:string;signalId:string;dimension:CommercialEvidenceDimension;currentState:string;whyNeeded:string;preferredEvidenceTier:EvidenceTier;preferredSourceTypes:EvidenceSourceType[];priority:"HIGH"|"MEDIUM"|"LOW";blockingImpact:string[];verificationRequired:true;provenanceRequired:true;ruleVersion:string}
export interface CandidateCommercialEvidence{id:string;opportunityId:string;signalId:string;sourceOrganization:string;sourceUrl:string;sourceType:EvidenceSourceType;evidenceTier:EvidenceTier;observedAt:Date;publicationOrEffectiveDate:Date|null;claimType:CommercialClaimType;candidateClaim:string;verificationState:EvidenceVerificationState;freshUntil:Date|null;conflicts:string[];provenance:string;acquisitionTaskId:string;contactGradeCandidate:"A"|"B"|"C"|"D"|"E"|null}
export interface AcquisitionVerificationItem{id:string;opportunityId:string;kind:"VERIFY_BUYER"|"VERIFY_BUYER_FUNCTION"|"VERIFY_AF01"|"VERIFY_CONTACT_ROUTE"|"VERIFY_CONTACT_GRADE"|"VERIFY_PROJECT_RELATIONSHIP"|"VERIFY_TEMPORAL_STATUS";candidateFact:string;supportingEvidenceIds:string[];conflictingEvidence:string[];currentProductionFact:string;decisionRequired:string;impactIfVerified:string;impactIfRejected:string;remainingBlockers:string[];recommendedHumanAction:string;decision:null}
export interface CommercialEvidenceAcquisitionPlan{opportunityId:string;signalId:string;gaps:CommercialEvidenceGap[];tasks:EvidenceAcquisitionTask[];candidateEvidence:CandidateCommercialEvidence[];verificationItems:AcquisitionVerificationItem[];ruleVersion:string}
