import type{BuyerEvidenceState,BuyerFunction,BuyerVendorIntelligence}from"./buyer-vendor-intelligence";
import type{ContactRouteGrade}from"./contact";import type{EvidenceSourceType,EvidenceTier}from"./commercial-evidence-acquisition";import type{ConversionEvidenceInput}from"./commercial-conversion";
export const CONTACT_INTELLIGENCE_RULE_VERSION="contact-intelligence@1.0.0";
export type ContactIntelligenceType="PROCUREMENT_PERSON"|"PURCHASING_PERSON"|"SOURCING_PERSON"|"SUPPLY_CHAIN_PERSON"|"VENDOR_MANAGEMENT_PERSON"|"CONTINGENT_WORKFORCE_PERSON"|"WORKFORCE_PROCUREMENT_PERSON"|"SUBCONTRACTING_PERSON"|"PROJECT_PROCUREMENT_PERSON"|"CONSTRUCTION_PROCUREMENT_PERSON"|"SUPPLIER_RELATIONS_PERSON"|"PROJECT_LEADERSHIP_PERSON"|"RECRUITER"|"GENERAL_CORPORATE_CONTACT"|"SUPPLIER_SUPPORT_ROUTE"|"VENDOR_PORTAL_ROUTE"|"PROCUREMENT_MAILBOX"|"DEPARTMENT_MAILBOX"|"PHONE_ROUTE"|"CONTACT_FORM"|"UNKNOWN";
export type ContactFreshness="CURRENT"|"STALE"|"UNKNOWN";export type ContactTaskType="FIND_PROCUREMENT_CONTACT"|"FIND_BUYER_FUNCTION_CONTACT"|"FIND_VENDOR_MANAGEMENT_CONTACT"|"FIND_SUPPLIER_RELATIONS_CONTACT"|"FIND_SUBCONTRACTING_CONTACT"|"FIND_WORKFORCE_PROCUREMENT_CONTACT"|"FIND_CONTINGENT_WORKFORCE_CONTACT"|"FIND_PROJECT_PROCUREMENT_CONTACT"|"FIND_OFFICIAL_COMMERCIAL_MAILBOX"|"VERIFY_CONTACT_CURRENTNESS"|"VERIFY_CONTACT_AUTHORITY"|"VERIFY_CONTACT_ROUTE_GRADE";
export interface ContactAcquisitionTask{id:string;taskType:ContactTaskType;opportunityId:string;signalId:string;targetFunction:BuyerFunction;currentRouteState:BuyerEvidenceState;preferredEvidenceTier:EvidenceTier;preferredSourceTypes:readonly EvidenceSourceType[];priority:"HIGH"|"MEDIUM"|"LOW";blockingImpact:string[];provenanceRequirement:string;verificationRequirement:string;ruleVersion:string}
export interface ContactCandidateEvidence{id:string;opportunityId:string;signalId:string;personName:string|null;title:string|null;organization:string|null;function:BuyerFunction;contactType:ContactIntelligenceType;routeTarget:string|null;sourceUrl:string;evidenceTier:EvidenceTier;sourceType:EvidenceSourceType;observedAt:Date;publicationOrEffectiveDate:Date|null;verificationState:BuyerEvidenceState;freshness:ContactFreshness;conflicts:string[];provenance:string;supportedRelationship:string;authorityEvidence:string|null;proposedGrade:ContactRouteGrade;gradeJustification:string;humanReviewRequired:true;opportunityRelationshipExplicit:boolean}
export interface ContactGradeRecommendation{proposedGrade:ContactRouteGrade;basis:string;missingEvidence:string[];currentnessState:ContactFreshness;verificationRequired:true}
export interface ContactVerificationItem{id:string;kind:"VERIFY_CONTACT_IDENTITY"|"VERIFY_CONTACT_CURRENTNESS"|"VERIFY_CONTACT_FUNCTION"|"VERIFY_CONTACT_AUTHORITY"|"VERIFY_CONTACT_ROUTE"|"VERIFY_CONTACT_GRADE"|"VERIFY_OPPORTUNITY_RELATIONSHIP";candidateFact:string;evidenceIds:string[];conflicts:string[];currentProductionState:string;proposedGrade:ContactRouteGrade;exactHumanDecision:string;impactIfVerified:string;impactIfRejected:string;remainingBlockers:string[];decision:null}
export interface ContactIntelligence{opportunityId:string;signalId:string;tasks:ContactAcquisitionTask[];candidates:ContactCandidateEvidence[];verificationItems:ContactVerificationItem[];currentKnownRoutes:ConversionEvidenceInput["contacts"];contactState:BuyerEvidenceState;conflicts:string[];remainingBlockers:string[];ruleVersion:string}
export interface ContactIntelligenceInput{conversion:ConversionEvidenceInput;buyerVendor:BuyerVendorIntelligence;candidates?:readonly ContactCandidateEvidence[];asOf?:Date}
