export const PRODUCTION_SOURCE_SCHEMA_VERSION="production-source@1.0.0";
export const SOURCE_FAMILIES=["COMPANY_CAREERS","STAFFING_CAREERS","UNION_DISPATCH","JOB_BOARD","PROJECT_OWNER","EPC_CONTRACTOR","GENERAL_CONTRACTOR","PROCUREMENT_PORTAL","VENDOR_PORTAL","GOVERNMENT_PUBLIC","PROJECT_NEWS","INDUSTRY_NEWS","PUBLIC_COMPANY_DOCUMENT","PROFESSIONAL_DIRECTORY","OTHER_APPROVED"]as const;export type SourceFamily=(typeof SOURCE_FAMILIES)[number];
export const SOURCE_TIERS=["PRIMARY_AUTHORITATIVE","DIRECT_CORPORATE","STRUCTURED_PUBLIC","SECONDARY_REPUTABLE","DISCOVERY_ONLY"]as const;export type SourceTier=(typeof SOURCE_TIERS)[number];
export const SOURCE_CAPABILITIES=["WORKFORCE_DEMAND","PROJECT_EXISTENCE","COMPANY_IDENTITY","COMPANY_ROLE","STAFFING_RELATIONSHIP","AF01_ACCEPTANCE_EVIDENCE","VENDOR_ROUTE","CONTACT_PERSON","CONTACT_ROUTE","COMPENSATION","LOCATION","SCHEDULE","HEADCOUNT","PUBLICATION_CURRENTNESS"]as const;export type SourceCapability=(typeof SOURCE_CAPABILITIES)[number];
export const PRODUCTION_CAPTURE_METHODS=["STRUCTURED_API","PUBLIC_JSON","RSS_FEED","STATIC_HTML","SERVER_RENDERED_HTML","BROWSER_REQUIRED_PUBLIC_PAGE","PUBLIC_DOCUMENT","MANUAL_EVIDENCE"]as const;export type ProductionCaptureMethod=(typeof PRODUCTION_CAPTURE_METHODS)[number];
export const SOURCE_READINESS_STATES=["DISCOVERED","UNDER_REVIEW","APPROVED_FOR_FIXTURE","APPROVED_FOR_LIVE_CAPTURE","PAUSED","BLOCKED","RETIRED"]as const;export type SourceReadinessState=(typeof SOURCE_READINESS_STATES)[number];
export const PRODUCTION_HEALTH_STATES=["HEALTHY","DEGRADED","FAILING","BLOCKED","STALE","PAUSED"]as const;export type ProductionHealthState=(typeof PRODUCTION_HEALTH_STATES)[number];
export const SOURCE_FAILURE_CLASSES=["NETWORK_FAILURE","TIMEOUT","HTTP_FAILURE","RATE_LIMITED","PARSER_FAILURE","SCHEMA_CHANGED","ACCESS_BLOCKED","COMPLIANCE_BLOCKED","INVALID_CONTENT","TRANSIENT_UPSTREAM_FAILURE","PERMANENT_UNSUPPORTED_SOURCE"]as const;export type SourceFailureClass=(typeof SOURCE_FAILURE_CLASSES)[number];
export const CONTRIBUTION_EVENTS=["CAPTURE_ATTEMPT","CAPTURE_SUCCESS","NEW_EVIDENCE","VALID_DEMAND_SIGNAL","DUPLICATE_OBSERVATION","OPPORTUNITY_CREATED","OPPORTUNITY_STRENGTHENED","CANONICAL_COMPANY_RESOLVED","VERIFIED_CONTACT_ROUTE","MANPOWER_ACCEPTANCE_EVIDENCE","VAMO_ELIGIBILITY","HOT_A_ELIGIBILITY","HOT_B_ELIGIBILITY","COMMERCIAL_ACTION","STALE_OBSERVATION","FAILURE"]as const;export type ContributionEventType=(typeof CONTRIBUTION_EVENTS)[number];
export interface SourceSchedule{desiredCadenceMinutes:number;minimumIntervalMinutes:number;freshnessTargetMinutes:number;nextEligibleCapture:Date|null;backoff:{initialMinutes:number;maximumMinutes:number;multiplier:number};localRestrictions:string[]}
export interface ProductionSourceProfile{sourceId:string;family:SourceFamily;tier:SourceTier;capabilities:SourceCapability[];methods:ProductionCaptureMethod[];readiness:SourceReadinessState;schedule:SourceSchedule;rateLimit:{requests:number;windowMinutes:number}|null;identityVersion:string;metadata:Record<string,unknown>}
export interface ProductionAdapterDescriptor{adapterId:string;version:string;sourceId:string;sourceFamily:SourceFamily;captureMethod:ProductionCaptureMethod;capabilities:SourceCapability[];executionRequirements:string[];parser:{id:string;version:string}}
export interface ProductionCaptureRequest{executionId:string;requestedTarget:string;cursor:string|null;policyDecisionId:string;asOf:Date}
export type ProductionCaptureResult={status:"CAPTURED";executionId:string;capturedIdentifier:string;capturedUrl:string|null;capturedAt:Date;contentType:string|null;contentReference:string;httpMetadata:Record<string,unknown>;externalIdentifiers:Record<string,string>;nextCursor:string|null}|{status:"FAILED";executionId:string;failure:StructuredSourceFailure};
export interface ProductionSourceAdapter{readonly descriptor:ProductionAdapterDescriptor;capture(request:ProductionCaptureRequest):Promise<ProductionCaptureResult>}
export interface StructuredSourceFailure{classification:SourceFailureClass;retryable:boolean;message:string;httpStatus:number|null;occurredAt:Date;details:Record<string,unknown>}
export interface SourceHealthSnapshot{state:ProductionHealthState;lastAttemptAt:Date|null;lastSuccessAt:Date|null;consecutiveFailures:number;lastFailure:SourceFailureClass|null;parserFailure:boolean;structureChanged:boolean;emptyResultCount:number;freshUntil:Date|null;latencyMs:number|null}
export interface SourceExecutionAudit{executionId:string;sourceId:string;adapterId:string;adapterVersion:string;policyDecisionId:string;startedAt:Date;endedAt:Date;result:"SUCCESS"|"EMPTY_SUCCESS"|"FAILURE";failure:StructuredSourceFailure|null;evidenceIds:string[];parserId:string;parserVersion:string;correlationMetadata:Record<string,unknown>}
export interface SourceContributionEvent{sourceId:string;executionId:string|null;eventType:ContributionEventType;subjectType:string;subjectId:string;occurredAt:Date;metadata:Record<string,unknown>}
