import type{EvidenceSourceType,EvidenceTier}from"./commercial-evidence-acquisition";import type{ConversionEvidenceInput,EvidenceVerificationState}from"./commercial-conversion";import type{ActionabilityState}from"./opportunity-actionability";
export const TEMPORAL_PROJECT_INTELLIGENCE_RULE_VERSION="temporal-project-intelligence@1.0.0";
export type TemporalEvidenceType="POSTING_PUBLICATION_DATE"|"POSTING_CLOSING_DATE"|"APPLICATION_DEADLINE"|"SOLICITATION_DUE_DATE"|"PROJECT_START_DATE"|"PROJECT_COMPLETION_DATE"|"EXPLICIT_OPEN_STATUS"|"EXPLICIT_CLOSED_STATUS"|"EXPLICIT_CANCELLED_STATUS"|"EXPLICIT_AWARDED_STATUS"|"CURRENTLY_HIRING_STATEMENT"|"CURRENT_JOB_CALL"|"POSTING_REMOVED"|"POSTING_ARCHIVED"|"RELATIVE_POSTING_AGE"|"UNKNOWN";export type ProjectRelationship="OWNER"|"DEVELOPER"|"GENERAL_CONTRACTOR"|"ELECTRICAL_CONTRACTOR"|"SUBCONTRACTOR"|"STAFFING_INTERMEDIARY"|"POSTING_EMPLOYER"|"MANPOWER_BUYER"|"PROJECT_PARTNER"|"UNKNOWN";export type IntelligenceState="UNKNOWN"|"CANDIDATE"|"VERIFIED"|"CONFLICTING"|"REJECTED"|"STALE";export type TemporalProjectTaskType="VERIFY_CURRENT_POSTING_STATUS"|"FIND_APPLICATION_DEADLINE"|"FIND_SOLICITATION_STATUS"|"FIND_CURRENT_JOB_CALL"|"VERIFY_POSTING_CURRENTNESS"|"VERIFY_PROJECT_CURRENTNESS"|"RESOLVE_TEMPORAL_CONFLICT"|"FIND_PROJECT_IDENTITY"|"VERIFY_PROJECT_IDENTITY"|"FIND_PROJECT_OWNER"|"FIND_GENERAL_CONTRACTOR"|"FIND_ELECTRICAL_CONTRACTOR"|"FIND_PROJECT_RELATIONSHIP"|"VERIFY_PROJECT_RELATIONSHIP"|"FIND_PROJECT_STAGE"|"FIND_PROJECT_START_DATE"|"FIND_PROJECT_COMPLETION_DATE"|"FIND_HEADCOUNT"|"FIND_WORK_SCHEDULE"|"FIND_SHIFT"|"FIND_DURATION"|"FIND_PER_DIEM"|"VERIFY_MANPOWER_PROJECT_LINK";
export interface TemporalEvidenceCandidate{id:string;opportunityId:string;signalId:string;evidenceType:TemporalEvidenceType;candidateState:ActionabilityState;sourceUrl:string;sourceType:EvidenceSourceType;evidenceTier:EvidenceTier;observedAt:Date;publicationDate:Date|null;deadline:Date|null;startDate:Date|null;endDate:Date|null;explicitStatusLanguage:string|null;freshness:"CURRENT"|"STALE"|"UNKNOWN";verificationState:EvidenceVerificationState;conflicts:string[];provenance:string;reason:string;strongEvidence:boolean}
export interface ProjectEvidenceCandidate{id:string;opportunityId:string;signalId:string;projectName:string|null;projectLocation:string|null;owner:string|null;developer:string|null;generalContractor:string|null;electricalContractor:string|null;staffingIntermediary:string|null;postingEmployer:string|null;manpowerBuyer:string|null;relationship:ProjectRelationship;stage:string|null;startDate:Date|null;completionDate:Date|null;manpowerRole:string|null;headcount:number|null;schedule:string|null;shift:string|null;duration:string|null;perDiem:string|null;sourceUrl:string;evidenceTier:EvidenceTier;sourceType:EvidenceSourceType;observedAt:Date;state:IntelligenceState;conflicts:string[];provenance:string;linkageRationale:string;matchingDimensions:string[];mismatchingDimensions:string[];relationshipExplicit:boolean}
export interface TemporalProjectTask{id:string;taskType:TemporalProjectTaskType;opportunityId:string;signalId:string;currentState:string;targetFact:string;priority:"HIGH"|"MEDIUM"|"LOW";blockingImpact:string[];preferredEvidenceTier:EvidenceTier;sourcePreference:readonly EvidenceSourceType[];provenanceRequirement:string;verificationRequirement:string}
export interface TemporalProjectVerificationItem{id:string;kind:"VERIFY_TEMPORAL_STATUS"|"VERIFY_PROJECT_IDENTITY"|"VERIFY_PROJECT_OWNER"|"VERIFY_GC_RELATIONSHIP"|"VERIFY_ELECTRICAL_CONTRACTOR_RELATIONSHIP"|"VERIFY_MANPOWER_PROJECT_LINK"|"VERIFY_HEADCOUNT"|"VERIFY_SCHEDULE"|"VERIFY_DURATION";candidateFact:string;evidenceIds:string[];conflicts:string[];currentProductionState:string;exactHumanDecision:string;impactIfVerified:string;impactIfRejected:string;remainingBlockers:string[];decision:null}
export interface TemporalProjectIntelligence{opportunityId:string;signalId:string;currentTemporalState:ActionabilityState;candidateTemporalState:ActionabilityState;temporalEvidence:TemporalEvidenceCandidate[];projectState:IntelligenceState;projects:ProjectEvidenceCandidate[];tasks:TemporalProjectTask[];verificationItems:TemporalProjectVerificationItem[];conflicts:string[];remainingBlockers:string[];ruleVersion:string}
export interface TemporalProjectIntelligenceInput{conversion:ConversionEvidenceInput;temporalEvidence?:readonly TemporalEvidenceCandidate[];projectEvidence?:readonly ProjectEvidenceCandidate[];asOf?:Date}
