import type{ClosureSnapshot,ContributionRow,EvidenceFact,ReviewPackage}from"../../../domain/targeted-evidence-closure";import{qualificationDossiers}from"../opportunity-qualification/opportunity-qualification-service";
import{FACTS,TARGETED_SOURCES}from"./targeted-evidence-facts";
export{FACTS,TARGETED_SOURCES};
const at=new Date("2026-08-21T20:00:00Z");
// Phase 2M: TARGETED_SOURCES/FACTS moved to targeted-evidence-facts.ts (a dependency-
// free leaf) so evidence-aggregation-service.ts can read them without pulling in this
// file's import of qualificationDossiers, which would otherwise create a circular
// import. Re-exported above under their original names; every value, order and object
// identity is unchanged.
const noEligibility=()=>({VAMO_ELIGIBLE:{eligible:false,blockers:["MATERIAL_CONFLICT_PRESENT","ACTIONABLE_CONTACT_REQUIRED"]},HOT_A_ELIGIBLE:{eligible:false,blockers:["MANPOWER_ACCEPTANCE_REQUIRED","ACTIONABLE_CONTACT_REQUIRED"]},HOT_B_ELIGIBLE:{eligible:false,blockers:["HOT_B_INTELLIGENCE_PATH_PRESENT"]}}as ClosureSnapshot["eligibility"]);
export function closureSnapshots():ClosureSnapshot[]{return qualificationDossiers().map(x=>{const facts=FACTS.filter(f=>f.opportunityId===x.id),port=facts.find(f=>f.sourceKey.startsWith("port-arthur")),permian=facts.find(f=>f.sourceKey.startsWith("trillium"));return{opportunityId:x.id,market:x.market,before:{buyer:x.buyerVerificationStatus,af01:x.af01VerificationState,route:x.routeVerificationState,economics:[x.compensation,x.perDiem,x.headcount].every(v=>v==null)?"UNKNOWN":"PARTIAL",conflicts:x.conflicts},after:{buyer:port||permian?"CANDIDATE_UNVERIFIED":x.buyerVerificationStatus,af01:port||permian?"CANDIDATE_UNVERIFIED":x.af01VerificationState,route:port||permian?"CANDIDATE_UNVERIFIED":x.routeVerificationState,economics:permian?"PAY_MAX_PER_DIEM_OT_SCHEDULE_DURATION_KNOWN":"UNKNOWN",newEvidenceIds:facts.map(f=>f.id),conflicts:x.conflicts},eligibility:noEligibility(),scoreState:"NOT_SCORABLE",commercialActionState:"NOT_GENERATED"}})}
export function reviewPackages():ReviewPackage[]{return FACTS.filter(f=>f.opportunityId).flatMap(f=>[{targetType:"BUYER"as const,targetId:`COMPANY_ROLE:${f.opportunityId}:buyer`,opportunityId:f.opportunityId!,proposedDecision:"READY_FOR_HUMAN_REVIEW"as const,evidenceIds:[f.id],sourceUrls:[f.url],reason:f.support,contraryEvidence:["Employer or procurement issuer is not automatically a manpower buyer"],remainingUncertainty:"Human review must establish opportunity-specific manpower purchasing authority",freshUntil:f.freshUntil,ifVerified:"Buyer gate may improve; independent AF-01 and route review remains",ifRejected:"Buyer evidence remains unverified"},{targetType:"AF_01"as const,targetId:`AF_01:${f.opportunityId}`,opportunityId:f.opportunityId!,proposedDecision:"READY_FOR_HUMAN_REVIEW"as const,evidenceIds:[f.id],sourceUrls:[f.url],reason:f.af01Candidate??"",contraryEvidence:[],remainingUncertainty:"Human review must confirm taxonomy and opportunity scope",freshUntil:f.freshUntil,ifVerified:"Manpower acceptance gate may improve",ifRejected:"AF-01 remains unverified"}])}
export function correlate(left:EvidenceFact,right:EvidenceFact){for(const key of["procurement_notice_id","employer_posting_id","project_contract_id"])if(left.stableIdentifiers[key]&&left.stableIdentifiers[key]===right.stableIdentifiers[key])return{decision:"MATCH"as const,key,value:left.stableIdentifiers[key]};return{decision:"REVIEW_CANDIDATE"as const,key:null,value:null}}
export function contributionMatrix():ContributionRow[]{return TARGETED_SOURCES.filter(s=>s.decision==="ACTIVATE").map(s=>{const f=FACTS.filter(x=>x.sourceKey===s.key);return{sourceKey:s.key,demand:f.filter(x=>x.demand).length,company:f.filter(x=>x.buyerCandidate).length,project:f.filter(x=>x.project).length,buyer:f.filter(x=>x.buyerCandidate).length,af01:f.filter(x=>x.af01Candidate).length,contact:f.filter(x=>x.contactRoute).length,compensation:f.filter(x=>x.payMin!=null||x.payMax!=null).length,perDiem:f.filter(x=>x.perDiem!=null).length,headcount:f.filter(x=>x.headcount!=null).length,schedule:f.filter(x=>x.schedule).length,provenance:f.length,freshness:f.every(x=>x.freshUntil>at)?"FRESH"as const:"STALE"as const,opportunitiesStrengthened:[...new Set(f.flatMap(x=>x.opportunityId?[x.opportunityId]:[]))]}})}
export const phase2hSummary=()=>{const activated=TARGETED_SOURCES.filter(x=>x.decision==="ACTIVATE"),activatedKeys=new Set(activated.map(x=>x.key)),reviewKeys=new Set(TARGETED_SOURCES.filter(x=>x.decision==="UNDER_REVIEW").map(x=>x.key)),productionFacts=FACTS.filter(f=>activatedKeys.has(f.sourceKey)),researchFacts=FACTS.filter(f=>reviewKeys.has(f.sourceKey)),sourcesBefore=19,sourcesActivated=activated.length;return{sourcesBefore,sourcesActivated,sourcesAfter:sourcesBefore+sourcesActivated,workInTexas:"UNDER_REVIEW",opportunities:4,buyerCandidates:FACTS.filter(f=>f.buyerCandidate).length,verifiedBuyers:0,af01Candidates:FACTS.filter(f=>f.af01Candidate).length,verifiedAf01:0,contactRoutes:FACTS.filter(f=>f.contactRoute).length,verifiedActionableRoutes:0,compensationKnown:productionFacts.filter(f=>f.payMin!=null||f.payMax!=null).length,researchCompensationCandidates:researchFacts.filter(f=>f.payMin!=null||f.payMax!=null).length,perDiemKnown:productionFacts.filter(f=>f.perDiem!=null).length,researchPerDiemCandidates:researchFacts.filter(f=>f.perDiem!=null).length,headcountKnown:productionFacts.filter(f=>f.headcount!=null).length,researchHeadcountCandidates:researchFacts.filter(f=>f.headcount!=null).length,overtimeKnown:productionFacts.filter(f=>f.overtime!=null).length,researchOvertimeCandidates:researchFacts.filter(f=>f.overtime!=null).length,vamo:0,hotA:0,hotB:0,scored:0,commercialActions:0,outreachExecuted:false,contractEconomicsImplemented:false,phase2iStarted:false}};
