import type{EvidenceFact,TargetedSource}from"../../../domain/targeted-evidence-closure";

/**
 * Phase 2M extraction (TECH-DEBT-04). This file holds ONLY the raw captured-evidence
 * data for Phases 2H, 2I and 2J -- zero logic, zero imports of anything that (directly
 * or transitively) imports opportunity-qualification-service.ts.
 *
 * Why this file exists: the Phase 2M brief assumed evidence-aggregation-service.ts
 * could safely import TARGETED_SOURCES/FACTS directly from targeted-evidence-closure-
 * service.ts ("that direction is fine, it's not circular"). A full audit of the real
 * import graph found that assumption was wrong: targeted-evidence-closure-service.ts
 * (2H) already imports {qualificationDossiers} from opportunity-qualification-
 * service.ts (for its own closureSnapshots()), and -2i-service.ts / -2j-service.ts
 * both transitively depend on -service.ts for FACTS/TARGETED_SOURCES/correlate. Had
 * evidence-aggregation-service.ts imported FACTS/TARGETED_SOURCES directly from any
 * of those three files, and opportunity-qualification-service.ts then imported from
 * evidence-aggregation-service.ts (as TECH-DEBT-04 requires), the result would have
 * been a genuine three-hop cycle: opportunity-qualification-service.ts ->
 * evidence-aggregation-service.ts -> targeted-evidence-closure-service.ts ->
 * opportunity-qualification-service.ts.
 *
 * The fix is this file: a dependency-free leaf holding the raw arrays.
 * targeted-evidence-closure-service.ts, -2i-service.ts and -2j-service.ts now import
 * their TARGETED_SOURCES and FACTS constants from here and re-export them under their
 * existing names -- same values, same order, same object identity, same public API --
 * so every existing import of these arrays elsewhere in the codebase (including their
 * own established test suites and source-portfolio-audit-2k-service.ts) is completely
 * unaffected. targeted-evidence-closure-service.ts's own import of qualificationDossiers
 * is untouched. evidence-aggregation-service.ts imports its raw evidence from here
 * instead, so opportunity-qualification-service.ts -> evidence-aggregation-service.ts
 * -> targeted-evidence-facts.ts is now a dead end: no cycle. See the Phase 2M report
 * for the full explanation and the concrete acyclicity test.
 */

// ---------------------------------------------------------------------------
// Phase 2H
// ---------------------------------------------------------------------------
const at2h=new Date("2026-08-21T20:00:00Z"),fresh2h=new Date("2026-09-20T00:00:00Z");

export const TARGETED_SOURCES:TargetedSource[]=[
{key:"port-arthur-temp-staffing-2026",name:"Port of Port Arthur Temporary Staffing RFP 2026-01",endpoint:"https://portpa.com/wp-content/uploads/2026/03/Port-of-Port-Arthur-RFP-Temporary-Staffing-FINAL.pdf",family:"PROCUREMENT_PORTAL",market:"Beaumont / Port Arthur",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["AF-01","buyer","named procurement contact","stable RFP identity"],reason:"Official current RFP explicitly procures temporary personnel through an agency",limitation:"Maintenance staffing is not itself current electrical demand",portfolio:"HIGH_VALUE"},
{key:"trillium-midland-794201",name:"Trillium Midland Electrician 794201",endpoint:"https://trilliumstaffing.com/jobs/job/794201-electrician-per-diem-offered-midland-texas.html",family:"STAFFING_CAREERS",market:"Permian Basin",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","pay","overtime","per diem","schedule","duration","recruiter candidate"],reason:"Current indexed public assignment exposes stable job ID and explicit economics",limitation:"Automated live request returned non-success; no bypass attempted; customer, headcount and direct recruiter route are absent",portfolio:"HIGH_VALUE"},
{key:"nes-houston-27773",name:"NES Fircroft Electrician BH-330309",endpoint:"https://www.nesfircroft.com/job/electrician-27773/",family:"STAFFING_CAREERS",market:"Houston / Gulf Coast",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","pay","overtime","schedule","duration","staffing relationship"],reason:"Current indexed contract assignment has requisition, rate, hours and duration",limitation:"Automated live request returned non-success; no bypass attempted; customer, per diem, headcount and recruiter route are absent",portfolio:"HIGH_VALUE"},
{key:"workintexas-public-detail",name:"WorkInTexas public job details",endpoint:"https://www.workintexas.com/vosnet/jobbanks/jobdetails.aspx",family:"JOB_BOARD",market:"Texas",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer","pay","headcount","schedule","dates","employer posting ID"],reason:"Individual public records are indexable and expose useful fields",limitation:"Search, pagination and encrypted detail tokens remain session-dependent and no stable compliant discovery path is proven",portfolio:"UNDER_REVIEW"},
{key:"aerotek-texas-2h",name:"Aerotek Texas electrical assignments",endpoint:"https://jobs.aerotek.com/us/en",family:"STAFFING_CAREERS",market:"Texas",decision:"DEFER",readiness:"DISCOVERED",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","pay","staffing"],reason:"Potential high-value staffing inventory",limitation:"No stable current public assignment endpoint was proven",portfolio:"UNDER_REVIEW"},
{key:"peopleready-texas-2h",name:"PeopleReady Skilled Trades Texas",endpoint:"https://skilled.peopleready.com/jobs/",family:"STAFFING_CAREERS",market:"Texas",decision:"DEFER",readiness:"DISCOVERED",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","pay","per diem"],reason:"Potential skilled-trades staffing evidence",limitation:"Mutable indexed slugs prevent deterministic identity",portfolio:"UNDER_REVIEW"}
];
export const FACTS:EvidenceFact[]=[
{id:"evidence:portpa-rfp-2026-01",sourceKey:"port-arthur-temp-staffing-2026",url:TARGETED_SOURCES[0].endpoint,observedAt:at2h,freshUntil:fresh2h,market:"Beaumont / Port Arthur",opportunityId:"qual-beaumont-port-arthur",stableIdentifiers:{procurement_notice_id:"RFP-2026-01"},demand:false,project:"Temporary Staffing Services Project",buyerCandidate:"Port of Port Arthur",af01Candidate:"TEMPORARY PERSONNEL AGENCY ACCEPTED",contactPerson:"Rebecca Underhill, Director of Accounting",contactRoute:"Rebecca@portpa.com / 409-983-2011",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"Official RFP seeks temporary personnel through an agency and names the procurement contact",verification:"UNVERIFIED"},
{id:"evidence:trillium-794201",sourceKey:"trillium-midland-794201",url:TARGETED_SOURCES[1].endpoint,observedAt:at2h,freshUntil:fresh2h,market:"Permian Basin",opportunityId:"qual-permian",stableIdentifiers:{employer_posting_id:"794201"},demand:true,project:"Midland oilfield electrical assignment",buyerCandidate:"Trillium Construction Services",af01Candidate:"THIRD_PARTY_RECRUITING_ACCEPTED",contactPerson:"Olivia Barnes",contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:45,overtime:"6 days/week, 10-hour shifts",perDiem:150,headcount:null,schedule:"07:00-17:00, six days/week",duration:"5 months",support:"Current W-2 staffing assignment for TDLR journeyman electricians with explicit economics",verification:"UNVERIFIED"},
{id:"evidence:nes-bh-330309",sourceKey:"nes-houston-27773",url:TARGETED_SOURCES[2].endpoint,observedAt:at2h,freshUntil:fresh2h,market:"Houston / Gulf Coast",opportunityId:null,stableIdentifiers:{employer_posting_id:"BH-330309"},demand:true,project:"Industrial rotating-equipment electrical assembly",buyerCandidate:"NES Fircroft",af01Candidate:"THIRD_PARTY_RECRUITING_ACCEPTED",contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:35,payMax:45,overtime:"60 hours/week",perDiem:null,headcount:null,schedule:"Day shift, 12-hour shift",duration:"12 months renewable",support:"Contract electrician assignment published by an engineering staffing provider",verification:"UNVERIFIED"}
];

// ---------------------------------------------------------------------------
// Phase 2I
// ---------------------------------------------------------------------------
const at2i=new Date("2026-08-22T18:00:00Z"),fresh2i=new Date("2026-09-21T00:00:00Z");

export const TARGETED_SOURCES_2I:TargetedSource[]=[
{key:"port-freeport-epa-electrical-rfq-2025",name:"Port Freeport RFQ - Emissions and Electrical Professional Services (EPA Clean Ports Grant 02F79001)",endpoint:"https://www.portfreeport.com/hubfs/Business%20With%20the%20Port/Public%20Notices/RFQ%20%20EPA%20Grant%20-%20August%2028%202025%20-%20approved%20fully%20executed-PUBLISH.pdf",family:"PROCUREMENT_PORTAL",market:"Freeport",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["named contact"],reason:"Real, currently-indexed Port Freeport RFQ under EPA Clean Ports grant 02F79001 names a project manager and describes electrical infrastructure scope",limitation:"Scope is professional engineering/design services (not temporary staffing or manpower subcontracting); the October 13, 2025 submission deadline has passed and the solicitation is very likely already awarded, so it is not a live manpower opportunity",portfolio:"UNDER_REVIEW"},
{key:"hgac-temp-staffing-129452",name:"H-GAC Temporary Staffing, Direct-Hire and Other Employer Services",endpoint:"https://procurement.opengov.com/portal/h-gac/projects/129452",family:"PROCUREMENT_PORTAL",market:"Houston / Gulf Coast",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","buyer","AF-01","named procurement contact"],reason:"Houston-Galveston Area Council cooperative-purchasing solicitation explicitly seeks temporary staffing and direct-hire employer services region-wide, matching the Port Arthur RFP pattern",limitation:"OpenGov procurement portal returned HTTP 403 on direct fetch; no bid content is accessible via plain GET",portfolio:"UNDER_REVIEW"},
{key:"port-houston-workday-staffing-electrical",name:"Port Houston Strategic Sourcing (temporary-staffing category; electrical lighting portwide bid CSB-1216432)",endpoint:"https://port-of-houston-authority.public-portal.us.workdayspend.com/",family:"PROCUREMENT_PORTAL",market:"Houston / Gulf Coast",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","buyer","AF-01"],reason:"Port Houston Strategic Sourcing procures a temporary-staffing services category and separately posted an electrical lighting and components portwide bid",limitation:"Bid detail is served through a Workday Strategic Sourcing single-page application; WebFetch returned only the page shell with no bid content",portfolio:"UNDER_REVIEW"},
{key:"port-of-corpus-christi-procureware",name:"Port of Corpus Christi Authority ProcureWare bid portal",endpoint:"https://pocca.procureware.com/Bids",family:"PROCUREMENT_PORTAL",market:"Corpus Christi",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["buyer","AF-01"],reason:"Port of Corpus Christi Authority procurement portal lists current and closed bid opportunities",limitation:"ProcureWare portal returned only navigation chrome via WebFetch; no bid listing content was retrievable",portfolio:"UNDER_REVIEW"},
{key:"jefferson-county-purchasing-notices",name:"Jefferson County Purchasing Notices for Bid",endpoint:"https://jeffersoncountytx.gov/Purchasing/NoticesForBid",family:"PROCUREMENT_PORTAL",market:"Beaumont / Port Arthur",decision:"DEFER",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["buyer"],reason:"Static, successfully-fetched Jefferson County bid listing confirmed a current airfield electrical-lighting rehabilitation IFB at Jack Brooks Regional Airport",limitation:"No current staffing/manpower solicitation was found; the county's most recent electrical-services term contract (IFB 25-018) was already awarded in July 2025 and the current airfield-lighting IFB is ordinary construction, not evidence of temporary-staffing or subcontracted-manpower acceptance",portfolio:"LOW_YIELD"}
];
export const FACTS_2I:EvidenceFact[]=[
{id:"evidence:portfreeport-epa-rfq-2025",sourceKey:"port-freeport-epa-electrical-rfq-2025",url:TARGETED_SOURCES_2I[0].endpoint,observedAt:at2i,freshUntil:fresh2i,market:"Freeport",opportunityId:"qual-freeport",stableIdentifiers:{procurement_notice_id:"EPA-GRANT-02F79001-RFQ"},demand:false,project:"Charting a Cleaner Course: Port Freeport's Continuous Improvement for a Cleaner Port (EPA Clean Ports Program)",buyerCandidate:"Port Freeport",af01Candidate:null,contactPerson:"John Lowe, EPA Grant Project Manager",contactRoute:"lowe@portfreeport.com / 979-233-2667",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"Current RFQ for emissions and electrical professional services under Port Freeport's EPA Clean Ports grant names a project contact distinct from the existing generic procurement mailbox; scope is professional engineering, not temporary staffing, and the solicitation deadline has passed",verification:"UNVERIFIED"}
];

// ---------------------------------------------------------------------------
// Phase 2J
// ---------------------------------------------------------------------------
const at2j=new Date("2026-08-22T21:00:00Z"),fresh2j=new Date("2026-09-22T00:00:00Z");

export const TARGETED_SOURCES_2J:TargetedSource[]=[
{key:"strike-midland-apprentice-electrician",name:"Strike Apprentice Electrician - Midland TX",endpoint:"https://strike.applytojob.com/apply/CL0yzwQIx2/Apprentice-Electrician",family:"COMPANY_CAREERS",market:"Permian Basin",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity"],reason:"Strike's own JazzHR-hosted career page (strike.applytojob.com) is company-owned, unauthenticated, and confirmed to render as plain static HTML via direct GET",limitation:"No pay, per diem, overtime, headcount, schedule or duration is stated on the page; Strike is a direct EPC/pipeline employer here, not a staffing intermediary, so no buyer or AF-01 candidate is established",portfolio:"USEFUL"},
{key:"strike-midland-journeyman-electrician",name:"Strike Journeyman Electrician - Midland TX",endpoint:"https://strike.applytojob.com/apply/L3Wr0FKloj/Journeyman-Electrician",family:"COMPANY_CAREERS",market:"Permian Basin",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity","currentness reconfirmation"],reason:"Formalizes into the targeted-evidence pipeline the same live Strike Midland assignment already referenced descriptively by the Permian Basin qualification dossier's demand sources; reconfirms the assignment is still live",limitation:"No pay, per diem, overtime, headcount, schedule or duration is stated on the page; Strike is a direct EPC/pipeline employer, not a staffing intermediary, so no buyer or AF-01 candidate is established",portfolio:"USEFUL"},
{key:"strike-houston-journeyman-electrician",name:"Strike Journeyman Electrician - Houston TX",endpoint:"https://strike.applytojob.com/apply/5DyLJo3Zgw/Journeyman-Electrician",family:"COMPANY_CAREERS",market:"Houston / Gulf Coast",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity"],reason:"Same company-owned static JazzHR career page pattern as the Midland postings, confirmed by direct GET",limitation:"No economics fields are stated; Houston / Gulf Coast does not correlate to any of the four tracked qualification dossiers",portfolio:"USEFUL"},
{key:"strike-baytown-journeyman-electrician",name:"Strike Journeyman Electrician - Baytown TX",endpoint:"https://strike.applytojob.com/apply/2uOOVqgVhY/Journeyman-Electrician",family:"COMPANY_CAREERS",market:"Houston / Gulf Coast",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity"],reason:"Same company-owned static JazzHR career page pattern as the Midland postings, confirmed by direct GET",limitation:"No economics fields are stated; Houston / Gulf Coast does not correlate to any of the four tracked qualification dossiers",portfolio:"USEFUL"},
{key:"trillium-amarillo-journeyman-791374",name:"Trillium Amarillo Licensed Journeyman Electrician 791374",endpoint:"https://trilliumstaffing.com/jobs/job/791374-licensed-journeyman-electrician-per-diem-offered-amarillo-texas.html",family:"STAFFING_CAREERS",market:"Texas Panhandle",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","pay","per diem","schedule","duration","recruiter contact"],reason:"Trillium's own /jobs/job/ static HTML pages remain genuinely capturable by plain GET; this is a current posting with a different stable ID from the now-404 Midland assignment (794201) captured in Phase 2H, with explicit pay, per diem, schedule, duration and a named recruiter",limitation:"Texas Panhandle does not correlate to any of the four tracked qualification dossiers (Freeport, Beaumont/Port Arthur, Permian Basin, Corpus Christi); customer and headcount remain unstated",portfolio:"HIGH_VALUE"},
{key:"trillium-amarillo-apprentice-791431",name:"Trillium Amarillo TDLR Apprentice Electrician 791431",endpoint:"https://trilliumstaffing.com/jobs/job/791431-tdlr-apprentice-electrician-per-diem-offered-amarillo-texas.html",family:"STAFFING_CAREERS",market:"Texas Panhandle",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","pay","per diem","schedule","duration","recruiter contact"],reason:"Same genuinely capturable Trillium static-HTML pattern; distinct current posting ID with an explicit wage-progression range, per diem, schedule, duration and the same named recruiter",limitation:"Texas Panhandle does not correlate to any of the four tracked qualification dossiers; customer and headcount remain unstated",portfolio:"HIGH_VALUE"},
{key:"mcdean-icims-careers",name:"M.C. Dean Careers (iCIMS)",endpoint:"https://careers.mcdean.com/jobs",family:"COMPANY_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"M.C. Dean's careers portal is backed by iCIMS (careers-mcdean.icims.com); iCIMS' only documented external feed requires OAuth 2.0 partner credentials issued to approved job-board vendors with a sponsoring customer",limitation:"No stable current job-detail URL was in hand to test individually; undocumented direct access was not attempted and is treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"zachry-oracle-recruiting-cloud",name:"Zachry Group Careers (Oracle Recruiting Cloud)",endpoint:"https://fa-evfm-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1029/requisitions",family:"COMPANY_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Zachry Group's career site runs on Oracle Recruiting Cloud; Oracle publishes no public job-search API, and the requisition endpoints used by the page's own JavaScript are undocumented and gated",limitation:"Treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"walker-engineering-taleo",name:"Walker Engineering Careers (Oracle Taleo)",endpoint:"https://phg.tbe.taleo.net/phg04/ats/careers/v2/searchResults?org=WP3X5Q&cws=37",family:"COMPANY_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Walker Engineering's careers page hands off to Oracle Taleo; direct fetch confirmed job listings load via JavaScript with no documented public API",limitation:"Treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"skillforce-adp-recruitment",name:"Skillforce Careers (ADP Workforce Now)",endpoint:"https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=068836c5-32da-4d04-b518-9e662ad548ec&ccId=19000101_000001&lang=en_US",family:"STAFFING_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Skillforce's job board is an ADP Workforce Now recruitment widget; ADP's documented developer APIs cover OAuth-authenticated employer HRIS integration, not an open public job-search feed",limitation:"URL is keyed by a session-style cid parameter rather than a stable per-job public identifier; treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"austin-industries-ultipro",name:"Austin Industries Careers (UltiPro / UKG Pro)",endpoint:"https://recruiting2.ultipro.com/AUS1003AUIN/JobBoard/",family:"COMPANY_CAREERS",market:"Texas",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Austin Industries' job board runs on UltiPro/UKG Pro; no documented public API was found this phase",limitation:"Individual job detail pages were not tested for static-HTML capturability; genuinely unresolved, not assumed blocked",portfolio:"UNDER_REVIEW"},
{key:"turner-industries-applicantpro",name:"Turner Industries Careers (ApplicantPro)",endpoint:"https://turnerindustries.applicantpro.com/jobs/country/us/state/Texas-TX",family:"COMPANY_CAREERS",market:"Texas",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Turner Industries' Texas listing page rendered only navigation chrome with no job content on direct fetch, indicating JS-driven listing; no documented public API was found",limitation:"Individual already-known job detail URLs were not available to test and might behave differently than the listing page; genuinely unresolved, not assumed blocked",portfolio:"UNDER_REVIEW"}
];
export const FACTS_2J:EvidenceFact[]=[
{id:"evidence:strike-midland-apprentice",sourceKey:"strike-midland-apprentice-electrician",url:TARGETED_SOURCES_2J[0].endpoint,observedAt:at2j,freshUntil:fresh2j,market:"Permian Basin",opportunityId:"qual-permian",stableIdentifiers:{employer_posting_id:"CL0yzwQIx2"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"Current Strike Apprentice Electrician assignment in Midland, TX confirms direct-employer demand; page states 100% travel and TDLR license requirement but no economics",verification:"UNVERIFIED"},
{id:"evidence:strike-midland-journeyman",sourceKey:"strike-midland-journeyman-electrician",url:TARGETED_SOURCES_2J[1].endpoint,observedAt:at2j,freshUntil:fresh2j,market:"Permian Basin",opportunityId:"qual-permian",stableIdentifiers:{employer_posting_id:"L3Wr0FKloj"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"Reconfirms the previously known Strike Midland Journeyman Electrician demand source is still live; no economics stated",verification:"UNVERIFIED"},
{id:"evidence:strike-houston-journeyman",sourceKey:"strike-houston-journeyman-electrician",url:TARGETED_SOURCES_2J[2].endpoint,observedAt:at2j,freshUntil:fresh2j,market:"Houston / Gulf Coast",opportunityId:null,stableIdentifiers:{employer_posting_id:"5DyLJo3Zgw"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:"Full Time",duration:null,support:"Current Strike Journeyman Electrician assignment in Houston, TX confirms direct-employer demand; no economics stated",verification:"UNVERIFIED"},
{id:"evidence:strike-baytown-journeyman",sourceKey:"strike-baytown-journeyman-electrician",url:TARGETED_SOURCES_2J[3].endpoint,observedAt:at2j,freshUntil:fresh2j,market:"Houston / Gulf Coast",opportunityId:null,stableIdentifiers:{employer_posting_id:"2uOOVqgVhY"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:"Full Time",duration:null,support:"Current Strike Journeyman Electrician assignment in Baytown, TX confirms direct-employer demand; no economics stated",verification:"UNVERIFIED"},
{id:"evidence:trillium-amarillo-791374",sourceKey:"trillium-amarillo-journeyman-791374",url:TARGETED_SOURCES_2J[4].endpoint,observedAt:at2j,freshUntil:fresh2j,market:"Texas Panhandle",opportunityId:"qual-amarillo",stableIdentifiers:{employer_posting_id:"791374"},demand:true,project:null,buyerCandidate:"Trillium Construction Services",af01Candidate:"THIRD_PARTY_RECRUITING_ACCEPTED",contactPerson:"Roberto Venegas",contactRoute:"800-778-8907",contactGrade:null,payMin:null,payMax:43,overtime:null,perDiem:100,headcount:null,schedule:"Monday-Friday, 7am-3:30pm",duration:"approximately 18 months of steady work",support:"Current live W-2 staffing assignment for a TDLR journeyman electrician in Amarillo with explicit pay, per diem, schedule, duration and a named recruiter contact; distinct posting ID from the now-404 Midland assignment (794201) captured in Phase 2H",verification:"UNVERIFIED"},
{id:"evidence:trillium-amarillo-791431",sourceKey:"trillium-amarillo-apprentice-791431",url:TARGETED_SOURCES_2J[5].endpoint,observedAt:at2j,freshUntil:fresh2j,market:"Texas Panhandle",opportunityId:"qual-amarillo",stableIdentifiers:{employer_posting_id:"791431"},demand:true,project:null,buyerCandidate:"Trillium Construction Services",af01Candidate:"THIRD_PARTY_RECRUITING_ACCEPTED",contactPerson:"Roberto Venegas",contactRoute:"800-778-8907",contactGrade:null,payMin:20.35,payMax:43,overtime:null,perDiem:100,headcount:null,schedule:"40-50 hours per week, first shift, Monday-Friday, with some Saturdays",duration:"4 year Apprentice Program",support:"Current live TDLR apprentice electrician assignment in Amarillo with an explicit wage-progression range, per diem, schedule, duration and the same named recruiter as the Journeyman posting",verification:"UNVERIFIED"}
];

/**
 * Phase 2Q. A single, scoped live re-fetch of the SAME Port Arthur RFP PDF already
 * captured in Phase 2H (TARGETED_SOURCES[0]/FACTS[0], same endpoint, same source
 * key) -- not a new source, a re-verification of an already-approved one. Direct
 * read of the PDF surfaced two things Phase 2H's capture did not: (1) an explicit,
 * structured procurement schedule -- RFP issued 03/26/26, mandatory pre-proposal
 * conference 4/16/26, submission deadline 4/22/26 2:00 PM -- and (2) the document's
 * own text names the RFP coordinator as "Kaylynn Rizzotto, Director of Accounting"
 * at bids@portpa.com, which does NOT match Phase 2H's captured "Rebecca Underhill,
 * Director of Accounting" / Rebecca@portpa.com / 409-983-2011.
 *
 * That discrepancy is preserved here, not resolved: this file does not silently
 * treat the newer capture as a correction of the older one (could be genuine
 * turnover, could have been a Phase 2H capture error) -- see the contactPerson
 * value and support text below. Phase 2H's FACTS[0] is untouched by this addition.
 */
const at2q=new Date("2026-08-27T12:00:00Z"),fresh2q=new Date("2026-09-27T00:00:00Z"),at2qDiscovery=new Date("2026-08-28T12:00:00Z"),fresh2qDiscovery=new Date("2026-09-28T00:00:00Z");
export const TARGETED_SOURCES_2Q:TargetedSource[]=[
{key:"port-arthur-temp-staffing-2026-reverify",name:"Port of Port Arthur Temporary Staffing RFP 2026-01 (Phase 2Q re-verification)",endpoint:TARGETED_SOURCES[0].endpoint,family:"PROCUREMENT_PORTAL",market:"Beaumont / Port Arthur",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["deadline","RFP coordinator identity"],reason:"Re-fetch of the same already-approved Phase 2H PDF source to check for a structured submission deadline, which Phase 2H's capture did not extract",limitation:"Contact-person identity conflicts with Phase 2H's capture (Kaylynn Rizzotto vs Rebecca Underhill); not resolved automatically",portfolio:"HIGH_VALUE"},
/**
 * Phase 2Q Data Center Discovery Gap Closure. Root cause of the miss: the two real
 * employers actually posting Central Texas data-center-corridor electrician work
 * (Rosendin -- already in this portfolio, `rosendin-adapter.ts`/source-portfolio-
 * audit-2k-service.ts's own "rosendin" entry -- and Walker Engineering, Phase 2H's
 * `walker-engineering-taleo` entry) were BOTH already investigated in this
 * codebase and correctly found JS-rendered with no documented public API
 * (SOURCE_ACCESS_LIMITATION, TECH-DEBT-02 for Rosendin specifically) -- that is a
 * deliberate, principled non-discovery under this project's own Phase 2J bright
 * line (plain HTTP fetch only), not an oversight. The real, genuine gap is
 * SOURCE_COVERAGE_GAP: TradesmenUp, a third-party job aggregator, republishes
 * Walker Engineering's real Temple/Austin posting as plain server-rendered HTML
 * (confirmed fetchable this phase) even though the employer's own site is
 * JS-blocked -- but TradesmenUp itself was never evaluated as its own source
 * family. Marked UNDER_REVIEW here, not ACTIVATE: only fetchability was confirmed
 * this phase, not the full robots.txt/ToS access-legitimacy review this
 * portfolio's every other ACTIVATE decision required.
 */
{key:"tradesmenup-aggregator",name:"TradesmenUp (third-party skilled-trades job aggregator)",endpoint:"https://www.tradesmenup.com",family:"STAFFING_CAREERS",market:"Texas",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"PUBLIC_SERVER_RENDERED_PAGE",expectedContribution:["demand","pay","schedule","employer identity for otherwise JS-blocked sources"],reason:"Confirmed this phase to republish at least one real posting (Walker Engineering, Temple/Austin, TX) as plain server-rendered HTML that is directly fetchable, even though the originating employer's own career site (Oracle Taleo) is JS-only and already BLOCKED in this portfolio",limitation:"Only fetchability was confirmed; robots.txt, terms of service, and the same access-legitimacy review every other ACTIVATE source in this portfolio received have NOT been performed -- genuinely UNDER_REVIEW, not a hardcoded one-off workaround",portfolio:"UNDER_REVIEW"}
];
export const FACTS_2Q:EvidenceFact[]=[
{id:"evidence:port-arthur-rfp-2026-01-2q-reverify",sourceKey:"port-arthur-temp-staffing-2026-reverify",url:TARGETED_SOURCES_2Q[0].endpoint,observedAt:at2q,freshUntil:fresh2q,market:"Beaumont / Port Arthur",opportunityId:"qual-beaumont-port-arthur",stableIdentifiers:{procurement_notice_id:"RFP-2026-01"},demand:false,project:"Temporary Staffing Services Project",buyerCandidate:"Port of Port Arthur",af01Candidate:"TEMPORARY PERSONNEL AGENCY ACCEPTED",contactPerson:"Kaylynn Rizzotto, Director of Accounting",contactRoute:"bids@portpa.com",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"RFP 2026-01 procurement schedule reads verbatim: RFP Issued 03/26/26; Mandatory Pre Proposal Conference 4/16/26 2:00 PM; Deadline for submissions 4/22/26 2:00 PM (\"Proposals received after the above date and time will not be considered\"). The document names the RFP Coordinator as Kaylynn Rizzotto, Director of Accounting, bids@portpa.com -- this conflicts with Phase 2H's captured contact (Rebecca Underhill / Rebecca@portpa.com / 409-983-2011) for the same document; that discrepancy is unresolved and requires human review, not assumed to be a correction. Buyer/AF-01 candidates are unchanged from Phase 2H -- this re-verification found no new evidence bearing on buyer or AF-01 verification, and the ExxonMobil/Port-of-Port-Arthur identity conflict remains unaddressed.",verification:"UNVERIFIED"},
/**
 * Real, live-captured posting (fetched this phase via TradesmenUp). opportunityId
 * is deliberately null: no buyer, AF-01, or contact evidence exists to qualify
 * this as a tracked opportunity yet, and this phase does not manufacture one --
 * see Section AB-style discipline already applied to Trillium Amarillo. The point
 * of capturing it here is that it now EXISTS in the evidence ledger and is
 * genuinely discoverable, which it was not before this phase.
 */
{id:"evidence:walker-engineering-temple-791676883",sourceKey:"tradesmenup-aggregator",url:"https://www.tradesmenup.com/jobs/481676883-journeyman-electrician-per-diem-+-pay-bump!-temple-tx-austin-tx",observedAt:at2qDiscovery,freshUntil:fresh2qDiscovery,market:"Central Texas",opportunityId:null,stableIdentifiers:{employer_posting_id:"481676883"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:null,contactGrade:null,payMin:38,payMax:45,overtime:"Night Shift and overtime as needed",perDiem:null,headcount:null,schedule:null,duration:null,support:"Real live posting, \"Journeyman Electrician Per-Diem + Pay Bump!\", Walker Engineering, Temple TX / Austin TX, $38.00-$45.00/hr, night shift and overtime as needed, posted approximately 3 months before this capture. Per diem is referenced in the title (\"Per-Diem + Pay Bump\") but no dollar amount or frequency is stated in the posting text, so perDiem stays null rather than assumed. This posting's own text does not explicitly name a data-center project; its connection to the confirmed $800M Meta/Rosendin/JE Dunn Temple data center (same city, same labor corridor, same per-diem-plus-bump compensation pattern documented in 2024-2026 trade press) is circumstantial, not confirmed -- reported as plausible context, not fact. Walker Engineering's own career site (Oracle Taleo) is already BLOCKED in this portfolio (Phase 2H); this posting was only discoverable via TradesmenUp, an unevaluated third-party aggregator.",verification:"UNVERIFIED"}
];
