import type{ContributionRow,ReviewPackage}from"../../../domain/targeted-evidence-closure";import{FACTS as FACTS_2H,correlate,phase2hSummary}from"./targeted-evidence-closure-service";
import{FACTS_2I,TARGETED_SOURCES_2I}from"./targeted-evidence-facts";
export{FACTS_2H,correlate,FACTS_2I,TARGETED_SOURCES_2I};
const at=new Date("2026-08-22T18:00:00Z");
// Phase 2M: TARGETED_SOURCES_2I/FACTS_2I moved to targeted-evidence-facts.ts (see that
// file's header comment); re-exported above under their original names, values and
// order unchanged.
export function reviewPackages2i():ReviewPackage[]{return FACTS_2I.filter(f=>f.contactPerson).map(f=>({targetType:"CONTACT_AUTHORITY"as const,targetId:`CONTACT:${f.opportunityId}:${f.contactPerson}`,opportunityId:f.opportunityId!,proposedDecision:"NEEDS_MORE_EVIDENCE"as const,evidenceIds:[f.id],sourceUrls:[f.url],reason:f.support,contraryEvidence:["Named contact is tied to a closed EPA grant RFQ for professional engineering services, not a manpower or staffing procurement; relevance to workforce-staffing outreach is unverified"],remainingUncertainty:"Human review must confirm whether this contact has any authority relevant to manpower/staffing outreach and whether the underlying RFQ has already been awarded to a different consultant",freshUntil:f.freshUntil,ifVerified:"Adds a second named Port Freeport contact for future outreach; does not itself establish buyer or AF-01 status for manpower",ifRejected:"Contact candidate remains unverified and unused"}))}
export function contributionMatrix2i():ContributionRow[]{return TARGETED_SOURCES_2I.filter(s=>s.decision==="ACTIVATE").map(s=>{const f=FACTS_2I.filter(x=>x.sourceKey===s.key);return{sourceKey:s.key,demand:f.filter(x=>x.demand).length,company:f.filter(x=>x.buyerCandidate).length,project:f.filter(x=>x.project).length,buyer:f.filter(x=>x.buyerCandidate).length,af01:f.filter(x=>x.af01Candidate).length,contact:f.filter(x=>x.contactRoute).length,compensation:f.filter(x=>x.payMin!=null||x.payMax!=null).length,perDiem:f.filter(x=>x.perDiem!=null).length,headcount:f.filter(x=>x.headcount!=null).length,schedule:f.filter(x=>x.schedule).length,provenance:f.length,freshness:f.every(x=>x.freshUntil>at)?"FRESH"as const:"STALE"as const,opportunitiesStrengthened:[...new Set(f.flatMap(x=>x.opportunityId?[x.opportunityId]:[]))]}})}
export const phase2iSummary=()=>{const h=phase2hSummary(),activated2i=TARGETED_SOURCES_2I.filter(x=>x.decision==="ACTIVATE"),reviewKeys2i=new Set(TARGETED_SOURCES_2I.filter(x=>x.decision==="UNDER_REVIEW").map(x=>x.key)),researchFacts2i=FACTS_2I.filter(f=>reviewKeys2i.has(f.sourceKey)),sourcesBefore=h.sourcesAfter,sourcesActivated=activated2i.length;return{sourcesBefore,sourcesEvaluated:TARGETED_SOURCES_2I.length,sourcesActivated,sourcesAfter:sourcesBefore+sourcesActivated,workInTexas:"UNDER_REVIEW"as const,trilliumStatus:"UNDER_REVIEW_CONFIRMED_UNAVAILABLE"as const,nesStatus:"UNDER_REVIEW_CONFIRMED_UNAVAILABLE"as const,opportunitiesTouched:[...new Set(FACTS_2I.flatMap(f=>f.opportunityId?[f.opportunityId]:[]))].length,newBuyerCandidates:0,newAf01Candidates:0,newVerifiedBuyers:0,newVerifiedAf01:0,contactCandidatesFound:FACTS_2I.filter(f=>f.contactPerson).length,productionCompensationKnown:0,productionPerDiemKnown:0,productionHeadcountKnown:0,productionOvertimeKnown:0,researchCompensationCandidates:researchFacts2i.filter(f=>f.payMin!=null||f.payMax!=null).length,researchPerDiemCandidates:researchFacts2i.filter(f=>f.perDiem!=null).length,researchHeadcountCandidates:researchFacts2i.filter(f=>f.headcount!=null).length,researchOvertimeCandidates:researchFacts2i.filter(f=>f.overtime!=null).length,vamo:0,hotA:0,hotB:0,scored:0,commercialActions:0,outreachExecuted:false,contractEconomicsImplemented:false,phase2jStarted:false}};
