import type{ContributionRow,ReviewPackage}from"../../../domain/targeted-evidence-closure";import{FACTS as FACTS_2H,TARGETED_SOURCES as TARGETED_SOURCES_2H,correlate}from"./targeted-evidence-closure-service";import{FACTS_2I,TARGETED_SOURCES_2I,phase2iSummary}from"./targeted-evidence-closure-2i-service";
import{FACTS_2J,TARGETED_SOURCES_2J}from"./targeted-evidence-facts";
export{FACTS_2H,TARGETED_SOURCES_2H,FACTS_2I,TARGETED_SOURCES_2I,FACTS_2J,TARGETED_SOURCES_2J,correlate};
const at=new Date("2026-08-22T21:00:00Z");
// Phase 2M: TARGETED_SOURCES_2J/FACTS_2J moved to targeted-evidence-facts.ts (see that
// file's header comment); re-exported above under their original names, values and
// order unchanged.

/**
 * Phase 2J platform-pattern analysis. This radar's only web-access tool is plain HTTP
 * fetch: no JS execution, no session/cookie handling, no CAPTCHA solving. Each row
 * records a per-platform (not per-company) classification of whether that constraint
 * still permits genuine, intentionally-public capture, grounded in the platform's own
 * documentation (or the confirmed absence of any) rather than in what a plain GET
 * happens to return.
 */
export type AtsPlatformStatus="SUPPORTED"|"UNDER_REVIEW_BROWSER_REQUIRED"|"BLOCKED";
export interface PlatformClassification{platform:string;status:AtsPlatformStatus;evidence:string;limitation:string}
export const PLATFORM_CLASSIFICATIONS:PlatformClassification[]=[
{platform:"Greenhouse",status:"SUPPORTED",evidence:"developers.greenhouse.io documents an unauthenticated public Job Board API (GET boards-api.greenhouse.io/v1/boards/{board_token}/jobs) explicitly built for external career-site and job-board consumption; no API key is required for GET endpoints",limitation:"No Texas electrical-staffing or EPC-contractor target evaluated this phase was found operating on Greenhouse; platform-level SUPPORTED status produced zero source activations"},
{platform:"Lever",status:"SUPPORTED",evidence:"Lever maintains a public GitHub repository (lever/postings-api) documenting an unauthenticated public Postings API intended for external careers pages",limitation:"No Texas electrical-staffing or EPC-contractor target evaluated this phase was found operating on Lever; platform-level SUPPORTED status produced zero source activations"},
{platform:"SmartRecruiters",status:"SUPPORTED",evidence:"developers.smartrecruiters.com documents a public Posting API (GET api.smartrecruiters.com/v1/companies/{company}/postings) explicitly intended for career sites and partner widgets",limitation:"No Texas electrical-staffing or EPC-contractor target evaluated this phase was found operating on SmartRecruiters; platform-level SUPPORTED status produced zero source activations"},
{platform:"Paylocity Recruiting (Public Careers Page and API Job Feed)",status:"SUPPORTED",evidence:"Paylocity documents a 'Recruiting Public Careers Page and API Job Feed' (GET recruiting.paylocity.com/Recruiting/v2/api/feed/jobs/{guid}), named and positioned as the public-facing companion to a company's own careers page",limitation:"Access requires the employer's own feed GUID, which must be discovered via that employer's own public careers page, never guessed or enumerated; no Texas electrical-staffing or EPC-contractor target evaluated this phase was confirmed exposing this feed"},
{platform:"JazzHR (ApplyToJob-hosted career pages)",status:"SUPPORTED",evidence:"Company-owned career pages hosted at *.applytojob.com (e.g. strike.applytojob.com) render the full job list and individual postings as plain server-rendered HTML with no session, cookie or JS required; this is the company's own directly-linked public careers page, confirmed by successfully reading five current Strike Texas postings via plain GET",limitation:"This is JazzHR's hosted career-page rendering, not a documented third-party API; usable only per known company subdomain, never by enumeration"},
{platform:"Company-owned custom static job board (e.g. Trillium Staffing's trilliumstaffing.com)",status:"SUPPORTED",evidence:"Trillium's own /jobs/search/ and /jobs/job/{id}-{slug}.html pages are plain server-rendered HTML with no JS or session required, confirmed by successfully reading five current Texas electrician postings and their explicit pay, per diem, schedule, duration and contact fields via plain GET",limitation:"Confirmed only for Trillium's own site this phase; NES Fircroft's newer careers.nesfircroft.com portal was tested and does not share this pattern (see BLOCKED entry below)"},
{platform:"Workday (myworkdayjobs.com)",status:"BLOCKED",evidence:"Workday's only documented API lives behind a Workday Community partner login (community.workday.com/api); the wday/cxs/ JSON endpoint every Workday career site's own search box calls is undocumented and known only through reverse engineering by third-party scraping tools",limitation:"Treated as not intentionally public per this phase's bright line; Primoris and Aerotek career sites both run on Workday and were left uncaptured on that basis. Noted for manager awareness, not altered this phase: a pre-existing Phase-prior-to-2H production adapter (rosendin-adapter.ts) already calls a wday/cxs endpoint directly, which is inconsistent with this phase's stricter standard; that adapter is out of this phase's scope and was left untouched"},
{platform:"SAP SuccessFactors Recruiting / Career Site Builder",status:"UNDER_REVIEW_BROWSER_REQUIRED",evidence:"No documented public Jobs API exists; the JobRequisition OData entity requires Recruiter Operator credentials, and the public career-site search is a client-side POST against the tenant's OData search endpoint",limitation:"Individual already-known detail-page URLs on *.jobs.hr.cloud.sap can render as static HTML (the pre-existing Bechtel adapter already relies on exactly this), but that is per-URL, not a documented feed, and cannot be used to discover new postings"},
{platform:"iCIMS",status:"BLOCKED",evidence:"iCIMS' standard XML job feed requires OAuth 2.0 client credentials issued only to approved third-party job-board partners with a sponsoring iCIMS customer; there is no open, unauthenticated public feed",limitation:"M.C. Dean's career site (careers.mcdean.com, backed by careers-mcdean.icims.com) runs on iCIMS; no stable current posting URL was in hand to test whether individual detail pages render as static HTML, and the partner-gated feed itself is out of scope per the bright line"},
{platform:"Oracle Recruiting Cloud / Taleo",status:"BLOCKED",evidence:"Oracle publishes no public job-search API; the recruitingCEJobRequisitions/recruitingCEJobRequisitionDetails endpoints and Taleo's search endpoints are undocumented internal calls gated by client-credential OAuth or session state",limitation:"Zachry Group (Oracle Recruiting Cloud) and Walker Engineering (Oracle Taleo) both run career sites on this pattern; Walker's listing was directly confirmed JS-rendered on fetch"},
{platform:"ADP (Workforce Now Recruiting)",status:"BLOCKED",evidence:"ADP's documented developer APIs (developers.adp.com) cover Job Requisitions/Applications for the employer's own OAuth-authenticated HRIS integration, not an open public job-search feed; no public unauthenticated endpoint was found",limitation:"Skillforce's job board is an ADP Workforce Now recruitment widget keyed by a session-style cid parameter, not a stable per-job public URL"},
{platform:"UltiPro / UKG Pro Recruiting",status:"UNDER_REVIEW_BROWSER_REQUIRED",evidence:"No documented public jobs API was found for UltiPro/UKG Pro's recruiting2.ultipro.com job board this phase",limitation:"Austin Industries runs on this pattern (recruiting2.ultipro.com/AUS1003AUIN/JobBoard/...); individual job detail pages were not tested for static-HTML capturability and remain genuinely unresolved rather than assumed blocked"},
{platform:"ApplicantPro",status:"UNDER_REVIEW_BROWSER_REQUIRED",evidence:"No documented public jobs API was found; Turner Industries' state-filtered listing page (turnerindustries.applicantpro.com/jobs/country/us/state/Texas-TX) rendered only navigation chrome with no job content on direct fetch",limitation:"Individual job detail pages were not tested this phase and might render differently than the listing page; treated as genuinely unresolved"},
];

export function contributionMatrix2j():ContributionRow[]{return TARGETED_SOURCES_2J.filter(s=>s.decision==="ACTIVATE").map(s=>{const f=FACTS_2J.filter(x=>x.sourceKey===s.key);return{sourceKey:s.key,demand:f.filter(x=>x.demand).length,company:f.filter(x=>x.buyerCandidate).length,project:f.filter(x=>x.project).length,buyer:f.filter(x=>x.buyerCandidate).length,af01:f.filter(x=>x.af01Candidate).length,contact:f.filter(x=>x.contactRoute).length,compensation:f.filter(x=>x.payMin!=null||x.payMax!=null).length,perDiem:f.filter(x=>x.perDiem!=null).length,headcount:f.filter(x=>x.headcount!=null).length,schedule:f.filter(x=>x.schedule).length,provenance:f.length,freshness:f.every(x=>x.freshUntil>at)?"FRESH"as const:"STALE"as const,opportunitiesStrengthened:[...new Set(f.flatMap(x=>x.opportunityId?[x.opportunityId]:[]))]}})}

/**
 * A ReviewPackage requires a real opportunityId. Facts that carry a candidate
 * (buyer/AF-01) but no matching tracked opportunity (Trillium Amarillo -> Texas
 * Panhandle) cannot honestly receive one, and facts that carry an opportunityId
 * but no candidate (the Strike postings, which only reconfirm demand) do not
 * warrant one either. The empty result is the truthful outcome, not an omission.
 */
export function reviewPackages2j():ReviewPackage[]{return FACTS_2J.filter(f=>f.opportunityId&&(f.buyerCandidate||f.af01Candidate)).flatMap(f=>[{targetType:"BUYER"as const,targetId:`COMPANY_ROLE:${f.opportunityId}:buyer`,opportunityId:f.opportunityId!,proposedDecision:"READY_FOR_HUMAN_REVIEW"as const,evidenceIds:[f.id],sourceUrls:[f.url],reason:f.support,contraryEvidence:["Employer or staffing posting is not automatically a manpower buyer"],remainingUncertainty:"Human review must establish opportunity-specific manpower purchasing authority",freshUntil:f.freshUntil,ifVerified:"Buyer gate may improve; independent AF-01 and route review remains",ifRejected:"Buyer evidence remains unverified"}])}

export const phase2jSummary=()=>{const i=phase2iSummary(),activated=TARGETED_SOURCES_2J.filter(x=>x.decision==="ACTIVATE"),blocked=TARGETED_SOURCES_2J.filter(x=>x.decision==="BLOCKED"),underReview=TARGETED_SOURCES_2J.filter(x=>x.decision==="UNDER_REVIEW"),sourcesBefore=i.sourcesAfter,sourcesActivated=activated.length,activatedKeys=new Set(activated.map(x=>x.key)),productionFacts=FACTS_2J.filter(f=>activatedKeys.has(f.sourceKey));return{sourcesBefore,sourcesEvaluated:TARGETED_SOURCES_2J.length,sourcesActivated,sourcesBlocked:blocked.length,sourcesUnderReview:underReview.length,sourcesAfter:sourcesBefore+sourcesActivated,platformsEvaluated:PLATFORM_CLASSIFICATIONS.length,platformsSupported:PLATFORM_CLASSIFICATIONS.filter(p=>p.status==="SUPPORTED").length,platformsBlocked:PLATFORM_CLASSIFICATIONS.filter(p=>p.status==="BLOCKED").length,platformsUnderReview:PLATFORM_CLASSIFICATIONS.filter(p=>p.status==="UNDER_REVIEW_BROWSER_REQUIRED").length,workInTexas:"UNDER_REVIEW"as const,trilliumHistoricalStatus:"UNDER_REVIEW_CONFIRMED_UNAVAILABLE"as const,trilliumCurrentTexasPostingsActivated:2,nesStatus:"UNDER_REVIEW_CONFIRMED_UNAVAILABLE"as const,opportunitiesTouched:[...new Set(productionFacts.flatMap(f=>f.opportunityId?[f.opportunityId]:[]))].length,buyerCandidatesFound:productionFacts.filter(f=>f.buyerCandidate).length,af01CandidatesFound:productionFacts.filter(f=>f.af01Candidate).length,contactCandidatesFound:productionFacts.filter(f=>f.contactPerson).length,newVerifiedBuyers:0,newVerifiedAf01:0,productionCompensationKnown:productionFacts.filter(f=>f.payMin!=null||f.payMax!=null).length,productionPerDiemKnown:productionFacts.filter(f=>f.perDiem!=null).length,productionHeadcountKnown:productionFacts.filter(f=>f.headcount!=null).length,productionOvertimeKnown:productionFacts.filter(f=>f.overtime!=null).length,reviewPackagesGenerated:reviewPackages2j().length,eligibilityChanged:false,vamo:0,hotA:0,hotB:0,scored:0,commercialActions:0,outreachExecuted:false,contractEconomicsImplemented:false,phase2kStarted:false}};
