import type{ContributionRow,EvidenceFact,ReviewPackage,TargetedSource}from"../../../domain/targeted-evidence-closure";import{FACTS as FACTS_2H,TARGETED_SOURCES as TARGETED_SOURCES_2H,correlate}from"./targeted-evidence-closure-service";import{FACTS_2I,TARGETED_SOURCES_2I,phase2iSummary}from"./targeted-evidence-closure-2i-service";
export{FACTS_2H,TARGETED_SOURCES_2H,FACTS_2I,TARGETED_SOURCES_2I,correlate};
const at=new Date("2026-08-22T21:00:00Z"),fresh=new Date("2026-09-22T00:00:00Z");

/**
 * Phase 2J platform-pattern analysis. This radar's only web-access tool is plain HTTP
 * fetch: no JS execution, no session/cookie handling, no CAPTCHA solving. Each row
 * records a per-platform (not per-company) classification of whether that constraint
 * still permits genuine, intentionally-public capture, grounded in the platform's own
 * documentation (or the confirmed absence of any) rather than in what a plain GET
 * happens to return.
 */
export type AtsPlatformStatus="SUPPORTED"|"UNDER_REVIEW_BROWSER_REQUIRED"|"BLOCKED";
export interface PlatformClassification{platform:string;status:AtsPlatformStatus;evidence:string;limitation:string}
export const PLATFORM_CLASSIFICATIONS:PlatformClassification[]=[
{platform:"Greenhouse",status:"SUPPORTED",evidence:"developers.greenhouse.io documents an unauthenticated public Job Board API (GET boards-api.greenhouse.io/v1/boards/{board_token}/jobs) explicitly built for external career-site and job-board consumption; no API key is required for GET endpoints",limitation:"No Texas electrical-staffing or EPC-contractor target evaluated this phase was found operating on Greenhouse; platform-level SUPPORTED status produced zero source activations"},
{platform:"Lever",status:"SUPPORTED",evidence:"Lever maintains a public GitHub repository (lever/postings-api) documenting an unauthenticated public Postings API intended for external careers pages",limitation:"No Texas electrical-staffing or EPC-contractor target evaluated this phase was found operating on Lever; platform-level SUPPORTED status produced zero source activations"},
{platform:"SmartRecruiters",status:"SUPPORTED",evidence:"developers.smartrecruiters.com documents a public Posting API (GET api.smartrecruiters.com/v1/companies/{company}/postings) explicitly intended for career sites and partner widgets",limitation:"No Texas electrical-staffing or EPC-contractor target evaluated this phase was found operating on SmartRecruiters; platform-level SUPPORTED status produced zero source activations"},
{platform:"Paylocity Recruiting (Public Careers Page and API Job Feed)",status:"SUPPORTED",evidence:"Paylocity documents a 'Recruiting Public Careers Page and API Job Feed' (GET recruiting.paylocity.com/Recruiting/v2/api/feed/jobs/{guid}), named and positioned as the public-facing companion to a company's own careers page",limitation:"Access requires the employer's own feed GUID, which must be discovered via that employer's own public careers page, never guessed or enumerated; no Texas electrical-staffing or EPC-contractor target evaluated this phase was confirmed exposing this feed"},
{platform:"JazzHR (ApplyToJob-hosted career pages)",status:"SUPPORTED",evidence:"Company-owned career pages hosted at *.applytojob.com (e.g. strike.applytojob.com) render the full job list and individual postings as plain server-rendered HTML with no session, cookie or JS required; this is the company's own directly-linked public careers page, confirmed by successfully reading five current Strike Texas postings via plain GET",limitation:"This is JazzHR's hosted career-page rendering, not a documented third-party API; usable only per known company subdomain, never by enumeration"},
{platform:"Company-owned custom static job board (e.g. Trillium Staffing's trilliumstaffing.com)",status:"SUPPORTED",evidence:"Trillium's own /jobs/search/ and /jobs/job/{id}-{slug}.html pages are plain server-rendered HTML with no JS or session required, confirmed by successfully reading five current Texas electrician postings and their explicit pay, per diem, schedule, duration and contact fields via plain GET",limitation:"Confirmed only for Trillium's own site this phase; NES Fircroft's newer careers.nesfircroft.com portal was tested and does not share this pattern (see BLOCKED entry below)"},
{platform:"Workday (myworkdayjobs.com)",status:"BLOCKED",evidence:"Workday's only documented API lives behind a Workday Community partner login (community.workday.com/api); the wday/cxs/ JSON endpoint every Workday career site's own search box calls is undocumented and known only through reverse engineering by third-party scraping tools",limitation:"Treated as not intentionally public per this phase's bright line; Primoris and Aerotek career sites both run on Workday and were left uncaptured on that basis. Noted for manager awareness, not altered this phase: a pre-existing Phase-prior-to-2H production adapter (rosendin-adapter.ts) already calls a wday/cxs endpoint directly, which is inconsistent with this phase's stricter standard; that adapter is out of this phase's scope and was left untouched"},
{platform:"SAP SuccessFactors Recruiting / Career Site Builder",status:"UNDER_REVIEW_BROWSER_REQUIRED",evidence:"No documented public Jobs API exists; the JobRequisition OData entity requires Recruiter Operator credentials, and the public career-site search is a client-side POST against the tenant's OData search endpoint",limitation:"Individual already-known detail-page URLs on *.jobs.hr.cloud.sap can render as static HTML (the pre-existing Bechtel adapter already relies on exactly this), but that is per-URL, not a documented feed, and cannot be used to discover new postings"},
{platform:"iCIMS",status:"BLOCKED",evidence:"iCIMS' standard XML job feed requires OAuth 2.0 client credentials issued only to approved third-party job-board partners with a sponsoring iCIMS customer; there is no open, unauthenticated public feed",limitation:"M.C. Dean's career site (careers.mcdean.com, backed by careers-mcdean.icims.com) runs on iCIMS; no stable current posting URL was in hand to test whether individual detail pages render as static HTML, and the partner-gated feed itself is out of scope per the bright line"},
{platform:"Oracle Recruiting Cloud / Taleo",status:"BLOCKED",evidence:"Oracle publishes no public job-search API; the recruitingCEJobRequisitions/recruitingCEJobRequisitionDetails endpoints and Taleo's search endpoints are undocumented internal calls gated by client-credential OAuth or session state",limitation:"Zachry Group (Oracle Recruiting Cloud) and Walker Engineering (Oracle Taleo) both run career sites on this pattern; Walker's listing was directly confirmed JS-rendered on fetch"},
{platform:"ADP (Workforce Now Recruiting)",status:"BLOCKED",evidence:"ADP's documented developer APIs (developers.adp.com) cover Job Requisitions/Applications for the employer's own OAuth-authenticated HRIS integration, not an open public job-search feed; no public unauthenticated endpoint was found",limitation:"Skillforce's job board is an ADP Workforce Now recruitment widget keyed by a session-style cid parameter, not a stable per-job public URL"},
{platform:"UltiPro / UKG Pro Recruiting",status:"UNDER_REVIEW_BROWSER_REQUIRED",evidence:"No documented public jobs API was found for UltiPro/UKG Pro's recruiting2.ultipro.com job board this phase",limitation:"Austin Industries runs on this pattern (recruiting2.ultipro.com/AUS1003AUIN/JobBoard/...); individual job detail pages were not tested for static-HTML capturability and remain genuinely unresolved rather than assumed blocked"},
{platform:"ApplicantPro",status:"UNDER_REVIEW_BROWSER_REQUIRED",evidence:"No documented public jobs API was found; Turner Industries' state-filtered listing page (turnerindustries.applicantpro.com/jobs/country/us/state/Texas-TX) rendered only navigation chrome with no job content on direct fetch",limitation:"Individual job detail pages were not tested this phase and might render differently than the listing page; treated as genuinely unresolved"},
];

export const TARGETED_SOURCES_2J:TargetedSource[]=[
{key:"strike-midland-apprentice-electrician",name:"Strike Apprentice Electrician - Midland TX",endpoint:"https://strike.applytojob.com/apply/CL0yzwQIx2/Apprentice-Electrician",family:"COMPANY_CAREERS",market:"Permian Basin",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity"],reason:"Strike's own JazzHR-hosted career page (strike.applytojob.com) is company-owned, unauthenticated, and confirmed to render as plain static HTML via direct GET",limitation:"No pay, per diem, overtime, headcount, schedule or duration is stated on the page; Strike is a direct EPC/pipeline employer here, not a staffing intermediary, so no buyer or AF-01 candidate is established",portfolio:"USEFUL"},
{key:"strike-midland-journeyman-electrician",name:"Strike Journeyman Electrician - Midland TX",endpoint:"https://strike.applytojob.com/apply/L3Wr0FKloj/Journeyman-Electrician",family:"COMPANY_CAREERS",market:"Permian Basin",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity","currentness reconfirmation"],reason:"Formalizes into the targeted-evidence pipeline the same live Strike Midland assignment already referenced descriptively by the Permian Basin qualification dossier's demand sources; reconfirms the assignment is still live",limitation:"No pay, per diem, overtime, headcount, schedule or duration is stated on the page; Strike is a direct EPC/pipeline employer, not a staffing intermediary, so no buyer or AF-01 candidate is established",portfolio:"USEFUL"},
{key:"strike-houston-journeyman-electrician",name:"Strike Journeyman Electrician - Houston TX",endpoint:"https://strike.applytojob.com/apply/5DyLJo3Zgw/Journeyman-Electrician",family:"COMPANY_CAREERS",market:"Houston / Gulf Coast",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity"],reason:"Same company-owned static JazzHR career page pattern as the Midland postings, confirmed by direct GET",limitation:"No economics fields are stated; Houston / Gulf Coast does not correlate to any of the four tracked qualification dossiers",portfolio:"USEFUL"},
{key:"strike-baytown-journeyman-electrician",name:"Strike Journeyman Electrician - Baytown TX",endpoint:"https://strike.applytojob.com/apply/2uOOVqgVhY/Journeyman-Electrician",family:"COMPANY_CAREERS",market:"Houston / Gulf Coast",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","location","stable posting identity"],reason:"Same company-owned static JazzHR career page pattern as the Midland postings, confirmed by direct GET",limitation:"No economics fields are stated; Houston / Gulf Coast does not correlate to any of the four tracked qualification dossiers",portfolio:"USEFUL"},
{key:"trillium-amarillo-journeyman-791374",name:"Trillium Amarillo Licensed Journeyman Electrician 791374",endpoint:"https://trilliumstaffing.com/jobs/job/791374-licensed-journeyman-electrician-per-diem-offered-amarillo-texas.html",family:"STAFFING_CAREERS",market:"Texas Panhandle",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","pay","per diem","schedule","duration","recruiter contact"],reason:"Trillium's own /jobs/job/ static HTML pages remain genuinely capturable by plain GET; this is a current posting with a different stable ID from the now-404 Midland assignment (794201) captured in Phase 2H, with explicit pay, per diem, schedule, duration and a named recruiter",limitation:"Texas Panhandle does not correlate to any of the four tracked qualification dossiers (Freeport, Beaumont/Port Arthur, Permian Basin, Corpus Christi); customer and headcount remain unstated",portfolio:"HIGH_VALUE"},
{key:"trillium-amarillo-apprentice-791431",name:"Trillium Amarillo TDLR Apprentice Electrician 791431",endpoint:"https://trilliumstaffing.com/jobs/job/791431-tdlr-apprentice-electrician-per-diem-offered-amarillo-texas.html",family:"STAFFING_CAREERS",market:"Texas Panhandle",decision:"ACTIVATE",readiness:"APPROVED_FOR_LIVE_CAPTURE",policy:"ALLOW",captureMethod:"PUBLIC_DOCUMENT",expectedContribution:["demand","pay","per diem","schedule","duration","recruiter contact"],reason:"Same genuinely capturable Trillium static-HTML pattern; distinct current posting ID with an explicit wage-progression range, per diem, schedule, duration and the same named recruiter",limitation:"Texas Panhandle does not correlate to any of the four tracked qualification dossiers; customer and headcount remain unstated",portfolio:"HIGH_VALUE"},
{key:"mcdean-icims-careers",name:"M.C. Dean Careers (iCIMS)",endpoint:"https://careers.mcdean.com/jobs",family:"COMPANY_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"M.C. Dean's careers portal is backed by iCIMS (careers-mcdean.icims.com); iCIMS' only documented external feed requires OAuth 2.0 partner credentials issued to approved job-board vendors with a sponsoring customer",limitation:"No stable current job-detail URL was in hand to test individually; undocumented direct access was not attempted and is treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"zachry-oracle-recruiting-cloud",name:"Zachry Group Careers (Oracle Recruiting Cloud)",endpoint:"https://fa-evfm-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1029/requisitions",family:"COMPANY_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Zachry Group's career site runs on Oracle Recruiting Cloud; Oracle publishes no public job-search API, and the requisition endpoints used by the page's own JavaScript are undocumented and gated",limitation:"Treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"walker-engineering-taleo",name:"Walker Engineering Careers (Oracle Taleo)",endpoint:"https://phg.tbe.taleo.net/phg04/ats/careers/v2/searchResults?org=WP3X5Q&cws=37",family:"COMPANY_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Walker Engineering's careers page hands off to Oracle Taleo; direct fetch confirmed job listings load via JavaScript with no documented public API",limitation:"Treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"skillforce-adp-recruitment",name:"Skillforce Careers (ADP Workforce Now)",endpoint:"https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=068836c5-32da-4d04-b518-9e662ad548ec&ccId=19000101_000001&lang=en_US",family:"STAFFING_CAREERS",market:"Texas",decision:"BLOCKED",readiness:"BLOCKED",policy:"DENY",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Skillforce's job board is an ADP Workforce Now recruitment widget; ADP's documented developer APIs cover OAuth-authenticated employer HRIS integration, not an open public job-search feed",limitation:"URL is keyed by a session-style cid parameter rather than a stable per-job public identifier; treated as not intentionally public per this phase's bright line",portfolio:"BLOCKED"},
{key:"austin-industries-ultipro",name:"Austin Industries Careers (UltiPro / UKG Pro)",endpoint:"https://recruiting2.ultipro.com/AUS1003AUIN/JobBoard/",family:"COMPANY_CAREERS",market:"Texas",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Austin Industries' job board runs on UltiPro/UKG Pro; no documented public API was found this phase",limitation:"Individual job detail pages were not tested for static-HTML capturability; genuinely unresolved, not assumed blocked",portfolio:"UNDER_REVIEW"},
{key:"turner-industries-applicantpro",name:"Turner Industries Careers (ApplicantPro)",endpoint:"https://turnerindustries.applicantpro.com/jobs/country/us/state/Texas-TX",family:"COMPANY_CAREERS",market:"Texas",decision:"UNDER_REVIEW",readiness:"UNDER_REVIEW",policy:"REVIEW_REQUIRED",captureMethod:"BROWSER_REQUIRED_PUBLIC_PAGE",expectedContribution:["demand","employer"],reason:"Turner Industries' Texas listing page rendered only navigation chrome with no job content on direct fetch, indicating JS-driven listing; no documented public API was found",limitation:"Individual already-known job detail URLs were not available to test and might behave differently than the listing page; genuinely unresolved, not assumed blocked",portfolio:"UNDER_REVIEW"},
];

export const FACTS_2J:EvidenceFact[]=[
{id:"evidence:strike-midland-apprentice",sourceKey:"strike-midland-apprentice-electrician",url:TARGETED_SOURCES_2J[0].endpoint,observedAt:at,freshUntil:fresh,market:"Permian Basin",opportunityId:"qual-permian",stableIdentifiers:{employer_posting_id:"CL0yzwQIx2"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"Current Strike Apprentice Electrician assignment in Midland, TX confirms direct-employer demand; page states 100% travel and TDLR license requirement but no economics",verification:"UNVERIFIED"},
{id:"evidence:strike-midland-journeyman",sourceKey:"strike-midland-journeyman-electrician",url:TARGETED_SOURCES_2J[1].endpoint,observedAt:at,freshUntil:fresh,market:"Permian Basin",opportunityId:"qual-permian",stableIdentifiers:{employer_posting_id:"L3Wr0FKloj"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:null,duration:null,support:"Reconfirms the previously known Strike Midland Journeyman Electrician demand source is still live; no economics stated",verification:"UNVERIFIED"},
{id:"evidence:strike-houston-journeyman",sourceKey:"strike-houston-journeyman-electrician",url:TARGETED_SOURCES_2J[2].endpoint,observedAt:at,freshUntil:fresh,market:"Houston / Gulf Coast",opportunityId:null,stableIdentifiers:{employer_posting_id:"5DyLJo3Zgw"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:"Full Time",duration:null,support:"Current Strike Journeyman Electrician assignment in Houston, TX confirms direct-employer demand; no economics stated",verification:"UNVERIFIED"},
{id:"evidence:strike-baytown-journeyman",sourceKey:"strike-baytown-journeyman-electrician",url:TARGETED_SOURCES_2J[3].endpoint,observedAt:at,freshUntil:fresh,market:"Houston / Gulf Coast",opportunityId:null,stableIdentifiers:{employer_posting_id:"2uOOVqgVhY"},demand:true,project:null,buyerCandidate:null,af01Candidate:null,contactPerson:null,contactRoute:"Public assignment page",contactGrade:null,payMin:null,payMax:null,overtime:null,perDiem:null,headcount:null,schedule:"Full Time",duration:null,support:"Current Strike Journeyman Electrician assignment in Baytown, TX confirms direct-employer demand; no economics stated",verification:"UNVERIFIED"},
{id:"evidence:trillium-amarillo-791374",sourceKey:"trillium-amarillo-journeyman-791374",url:TARGETED_SOURCES_2J[4].endpoint,observedAt:at,freshUntil:fresh,market:"Texas Panhandle",opportunityId:null,stableIdentifiers:{employer_posting_id:"791374"},demand:true,project:null,buyerCandidate:"Trillium Construction Services",af01Candidate:"THIRD_PARTY_RECRUITING_ACCEPTED",contactPerson:"Roberto Venegas",contactRoute:"800-778-8907",contactGrade:null,payMin:null,payMax:43,overtime:null,perDiem:100,headcount:null,schedule:"Monday-Friday, 7am-3:30pm",duration:"approximately 18 months of steady work",support:"Current live W-2 staffing assignment for a TDLR journeyman electrician in Amarillo with explicit pay, per diem, schedule, duration and a named recruiter contact; distinct posting ID from the now-404 Midland assignment (794201) captured in Phase 2H",verification:"UNVERIFIED"},
{id:"evidence:trillium-amarillo-791431",sourceKey:"trillium-amarillo-apprentice-791431",url:TARGETED_SOURCES_2J[5].endpoint,observedAt:at,freshUntil:fresh,market:"Texas Panhandle",opportunityId:null,stableIdentifiers:{employer_posting_id:"791431"},demand:true,project:null,buyerCandidate:"Trillium Construction Services",af01Candidate:"THIRD_PARTY_RECRUITING_ACCEPTED",contactPerson:"Roberto Venegas",contactRoute:"800-778-8907",contactGrade:null,payMin:20.35,payMax:43,overtime:null,perDiem:100,headcount:null,schedule:"40-50 hours per week, first shift, Monday-Friday, with some Saturdays",duration:"4 year Apprentice Program",support:"Current live TDLR apprentice electrician assignment in Amarillo with an explicit wage-progression range, per diem, schedule, duration and the same named recruiter as the Journeyman posting",verification:"UNVERIFIED"},
];

export function contributionMatrix2j():ContributionRow[]{return TARGETED_SOURCES_2J.filter(s=>s.decision==="ACTIVATE").map(s=>{const f=FACTS_2J.filter(x=>x.sourceKey===s.key);return{sourceKey:s.key,demand:f.filter(x=>x.demand).length,company:f.filter(x=>x.buyerCandidate).length,project:f.filter(x=>x.project).length,buyer:f.filter(x=>x.buyerCandidate).length,af01:f.filter(x=>x.af01Candidate).length,contact:f.filter(x=>x.contactRoute).length,compensation:f.filter(x=>x.payMin!=null||x.payMax!=null).length,perDiem:f.filter(x=>x.perDiem!=null).length,headcount:f.filter(x=>x.headcount!=null).length,schedule:f.filter(x=>x.schedule).length,provenance:f.length,freshness:f.every(x=>x.freshUntil>at)?"FRESH"as const:"STALE"as const,opportunitiesStrengthened:[...new Set(f.flatMap(x=>x.opportunityId?[x.opportunityId]:[]))]}})}

/**
 * A ReviewPackage requires a real opportunityId. Facts that carry a candidate
 * (buyer/AF-01) but no matching tracked opportunity (Trillium Amarillo -> Texas
 * Panhandle) cannot honestly receive one, and facts that carry an opportunityId
 * but no candidate (the Strike postings, which only reconfirm demand) do not
 * warrant one either. The empty result is the truthful outcome, not an omission.
 */
export function reviewPackages2j():ReviewPackage[]{return FACTS_2J.filter(f=>f.opportunityId&&(f.buyerCandidate||f.af01Candidate)).flatMap(f=>[{targetType:"BUYER"as const,targetId:`COMPANY_ROLE:${f.opportunityId}:buyer`,opportunityId:f.opportunityId!,proposedDecision:"READY_FOR_HUMAN_REVIEW"as const,evidenceIds:[f.id],sourceUrls:[f.url],reason:f.support,contraryEvidence:["Employer or staffing posting is not automatically a manpower buyer"],remainingUncertainty:"Human review must establish opportunity-specific manpower purchasing authority",freshUntil:f.freshUntil,ifVerified:"Buyer gate may improve; independent AF-01 and route review remains",ifRejected:"Buyer evidence remains unverified"}])}

export const phase2jSummary=()=>{const i=phase2iSummary(),activated=TARGETED_SOURCES_2J.filter(x=>x.decision==="ACTIVATE"),blocked=TARGETED_SOURCES_2J.filter(x=>x.decision==="BLOCKED"),underReview=TARGETED_SOURCES_2J.filter(x=>x.decision==="UNDER_REVIEW"),sourcesBefore=i.sourcesAfter,sourcesActivated=activated.length,activatedKeys=new Set(activated.map(x=>x.key)),productionFacts=FACTS_2J.filter(f=>activatedKeys.has(f.sourceKey));return{sourcesBefore,sourcesEvaluated:TARGETED_SOURCES_2J.length,sourcesActivated,sourcesBlocked:blocked.length,sourcesUnderReview:underReview.length,sourcesAfter:sourcesBefore+sourcesActivated,platformsEvaluated:PLATFORM_CLASSIFICATIONS.length,platformsSupported:PLATFORM_CLASSIFICATIONS.filter(p=>p.status==="SUPPORTED").length,platformsBlocked:PLATFORM_CLASSIFICATIONS.filter(p=>p.status==="BLOCKED").length,platformsUnderReview:PLATFORM_CLASSIFICATIONS.filter(p=>p.status==="UNDER_REVIEW_BROWSER_REQUIRED").length,workInTexas:"UNDER_REVIEW"as const,trilliumHistoricalStatus:"UNDER_REVIEW_CONFIRMED_UNAVAILABLE"as const,trilliumCurrentTexasPostingsActivated:2,nesStatus:"UNDER_REVIEW_CONFIRMED_UNAVAILABLE"as const,opportunitiesTouched:[...new Set(productionFacts.flatMap(f=>f.opportunityId?[f.opportunityId]:[]))].length,buyerCandidatesFound:productionFacts.filter(f=>f.buyerCandidate).length,af01CandidatesFound:productionFacts.filter(f=>f.af01Candidate).length,contactCandidatesFound:productionFacts.filter(f=>f.contactPerson).length,newVerifiedBuyers:0,newVerifiedAf01:0,productionCompensationKnown:productionFacts.filter(f=>f.payMin!=null||f.payMax!=null).length,productionPerDiemKnown:productionFacts.filter(f=>f.perDiem!=null).length,productionHeadcountKnown:productionFacts.filter(f=>f.headcount!=null).length,productionOvertimeKnown:productionFacts.filter(f=>f.overtime!=null).length,reviewPackagesGenerated:reviewPackages2j().length,eligibilityChanged:false,vamo:0,hotA:0,hotB:0,scored:0,commercialActions:0,outreachExecuted:false,contractEconomicsImplemented:false,phase2kStarted:false}};
