import {getProductionSqlClient} from "../database/production-sql-client";
import {PostgresProjectIntelligenceRepository} from "../repositories/project-intelligence/postgres-project-intelligence-repository";
import {assembleProjectDetail,assembleProjectListItem,type ProjectDetailView,type ProjectListItem} from "../read-models/project-intelligence";
import type {ReadModelCapabilityState} from "../read-models/shared";
export const PROJECT_PAGE_SIZE=25; const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export interface ProjectListQuery{search:string;page:number} export interface ProjectListResult{capability:ReadModelCapabilityState;items:readonly ProjectListItem[];total:number|null;pageCount:number|null;reason:string|null}
export type ProjectDetailResult={state:"READY";detail:ProjectDetailView}|{state:"NOT_FOUND"|"UNAVAILABLE"|"ERROR";detail:null;reason:string};
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??"":v??"";
export const parseProjectListQuery=(p:Record<string,string|string[]|undefined>):ProjectListQuery=>{const page=Number.parseInt(one(p.page),10);return{search:one(p.q).trim().slice(0,120),page:Number.isFinite(page)&&page>0?page:1}};
export const projectListHref=(q:ProjectListQuery,c:Partial<ProjectListQuery>)=>{const n={...q,...c},p=new URLSearchParams();if(n.search)p.set("q",n.search);if(n.page>1)p.set("page",String(n.page));return p.size?`/projects?${p}`:"/projects"};
async function source(q:ProjectListQuery):Promise<ProjectListResult>{const c=getProductionSqlClient();if(!c)return{capability:"UNAVAILABLE",items:[],total:null,pageCount:null,reason:"DATABASE_CONNECTION_UNAVAILABLE"};const r=await new PostgresProjectIntelligenceRepository(c).enumerate(q.search,PROJECT_PAGE_SIZE,(q.page-1)*PROJECT_PAGE_SIZE);const now=new Date();return{capability:"OPERATIONAL",items:r.items.map(x=>assembleProjectListItem(x,now)),total:r.total,pageCount:Math.max(1,Math.ceil(r.total/PROJECT_PAGE_SIZE)),reason:null}}
export async function getProjectListPage(q:ProjectListQuery,load=source):Promise<ProjectListResult>{try{return await load(q)}catch{return{capability:"UNKNOWN",items:[],total:null,pageCount:null,reason:"PROJECT_QUERY_FAILED"}}}
export async function loadProjectDetail(id:string):Promise<ProjectDetailResult>{if(!UUID.test(id))return{state:"NOT_FOUND",detail:null,reason:"INVALID_PROJECT_ID"};const c=getProductionSqlClient();if(!c)return{state:"UNAVAILABLE",detail:null,reason:"DATABASE_CONNECTION_UNAVAILABLE"};try{const b=await new PostgresProjectIntelligenceRepository(c).get(id);return b?{state:"READY",detail:assembleProjectDetail(b,new Date())}:{state:"NOT_FOUND",detail:null,reason:"PROJECT_NOT_FOUND"}}catch{return{state:"ERROR",detail:null,reason:"PROJECT_QUERY_FAILED"}}}
export async function getProjectDetailPage(id:string,load=loadProjectDetail):Promise<ProjectDetailResult>{try{return await load(id)}catch{return{state:"ERROR",detail:null,reason:"PROJECT_QUERY_FAILED"}}}
