import { describe, expect, it } from "vitest";
import type { CreateHumanVerificationTaskEventInput, HumanInteraction, HumanResponseAssessment, HumanVerificationTask, HumanVerificationTaskEvent, HumanVerificationTaskStatus } from "../../domain/human-verification";
import type { HumanVerificationPlanningInput } from "../../domain/human-verification-planning";
import type { HumanVerificationRepository, PersistHumanVerificationTaskInput } from "../../server/repositories/human-verification/human-verification-repository";
import { HumanVerificationPlanningService } from "../../server/services/human-verification/human-verification-planning-service";

const now = new Date("2026-09-05T12:00:00Z");
class MemoryRepository implements HumanVerificationRepository {
  tasks: HumanVerificationTask[] = []; events: HumanVerificationTaskEvent[] = [];
  async findOpenTaskByDeduplicationKey(key:string){return this.tasks.find(x=>x.deduplicationKey===key&&!(["COMPLETED","CANCELLED","DUPLICATE","UNRESOLVABLE"]as HumanVerificationTaskStatus[]).includes(x.status))??null}
  async createTask(input:PersistHumanVerificationTaskInput){const task:HumanVerificationTask={...input,id:`task-${this.tasks.length+1}`,status:"OPEN",createdAt:now,closedAt:null};this.tasks.push(task);this.events.push({id:`event-${this.events.length+1}`,verificationTaskId:task.id,eventType:"CREATED",oldState:null,newState:"OPEN",reason:"Task created",operatorId:input.createdBy,occurredAt:now,evidenceIds:[],claimIds:[],metadata:{},createdAt:now});return task}
  async getTask(id:string){return this.tasks.find(x=>x.id===id)??null}
  async transitionTask(id:string,status:HumanVerificationTaskStatus){const task=(await this.getTask(id))!;task.status=status;return task}
  async createTaskEvent(input:CreateHumanVerificationTaskEventInput){const event:HumanVerificationTaskEvent={...input,id:`event-${this.events.length+1}`,createdAt:now};this.events.push(event);return event}
  async listTaskEvents(id:string){return this.events.filter(x=>x.verificationTaskId===id)}
  async createInteraction():Promise<HumanInteraction>{throw new Error("B2 must not create interactions")}
  async listInteractions(taskId:string):Promise<HumanInteraction[]>{void taskId;return[]}
  async createAssessment():Promise<HumanResponseAssessment>{throw new Error("B2 must not assess responses")}
  async listAssessments(interactionId:string):Promise<HumanResponseAssessment[]>{void interactionId;return[]}
}
const contact={personId:"person-1",name:"Commercial Contact",title:"Manager",department:"Procurement",routeId:"route-1",routeType:"PROFESSIONAL_PHONE",routeTarget:"555-0100",routeVerificationState:"VERIFIED",routeCurrent:true,preferredMethod:"PHONE"as const};
const input=(overrides:Partial<HumanVerificationPlanningInput>={}):HumanVerificationPlanningInput=>({need:"EXTERNAL_MANPOWER_ACCEPTANCE_UNKNOWN",companyId:"company-1",companyName:"Example Contractor",opportunityId:"opportunity-1",projectId:"project-1",projectName:"Example Project",blockerCode:"MISSING_MANPOWER_ACCEPTANCE",tradeId:"ELECTRICAL",occupationId:"ELECTRICIAN",scope:{companyScope:"UNKNOWN",projectId:"project-1",tradeId:"ELECTRICAL",occupationId:"ELECTRICIAN",geographicScope:"Texas"},sourceBasis:[{evidenceId:"evidence-1",claimId:"claim-1",sourceUrl:"https://example.com",observedAt:"2026-09-01",current:true,summary:"Public evidence does not resolve AF01."}],contact,publicEvidenceExhausted:true,commerciallyMaterial:true,createdBy:"planner-1",...overrides});
const setup=()=>{const repository=new MemoryRepository();return{repository,service:new HumanVerificationPlanningService(repository,()=>now)}};

describe("Phase 3I-B2 verification planning and packet",()=>{
  it("1 valid governed blocker creates a ready verification plan",async()=>expect((await setup().service.plan(input())).disposition).toBe("READY"));
  it("2 a valid plan creates exactly one B1 task and creation event",async()=>{const x=setup();const p=await x.service.plan(input());expect(x.repository.tasks).toHaveLength(1);expect(p.task?.id).toBe("task-1");expect(x.repository.events[0].eventType).toBe("CREATED")});
  it("3 equivalent open task is reused and audited as deduplicated",async()=>{const x=setup();await x.service.plan(input());const p=await x.service.plan(input());expect(p.disposition).toBe("DUPLICATE_OPEN_TASK");expect(x.repository.tasks).toHaveLength(1);expect(x.repository.events.at(-1)?.metadata).toMatchObject({planningDisposition:"DUPLICATE_OPEN_TASK"})});
  it("4 resolved governed evidence prevents task creation",async()=>{const x=setup();expect((await x.service.plan(input({governedStateResolved:true}))).disposition).toBe("ALREADY_RESOLVED");expect(x.repository.tasks).toHaveLength(0)});
  it("5 current scoped VERIFIED_POSITIVE suppresses AF01 task",async()=>{const x=setup();expect((await x.service.plan(input({currentAf01Result:"VERIFIED_POSITIVE",currentAf01Scope:input().scope,currentAf01ValidUntil:new Date("2026-10-01")}))).disposition).toBe("ALREADY_RESOLVED")});
  it("6 current scoped VERIFIED_NEGATIVE suppresses AF01 task",async()=>{const x=setup();expect((await x.service.plan(input({currentAf01Result:"VERIFIED_NEGATIVE",currentAf01Scope:input().scope,currentAf01ValidUntil:new Date("2026-10-01")}))).disposition).toBe("ALREADY_RESOLVED")});
  it("7 STALE AF01 permits re-verification",async()=>expect((await setup().service.plan(input({need:"STALE_COMMERCIAL_EVIDENCE",currentAf01Result:"STALE"}))).disposition).toBe("READY"));
  it("8 project scope remains project-specific",async()=>{const p=await setup().service.plan(input());expect(p.packet?.scopeToConfirm).toMatchObject({companyScope:"UNKNOWN",projectId:"project-1"})});
  it("9 null or unknown scope never becomes companywide",async()=>{const p=await setup().service.plan(input({scope:{companyScope:"UNKNOWN"},projectId:null}));expect(p.packet?.scopeToConfirm.companyScope).toBe("UNKNOWN");expect(p.packet?.scopeToConfirm.companyScope).not.toBe("COMPANYWIDE")});
  it("a verified result from another scope does not suppress planning",async()=>{const p=await setup().service.plan(input({currentAf01Result:"VERIFIED_POSITIVE",currentAf01Scope:{companyScope:"UNKNOWN",projectId:"other-project"}}));expect(p.disposition).toBe("READY")});
  it("10 MMR scenario asks a bounded question without claiming acceptance",async()=>{const p=await setup().service.plan(input({companyName:"MMR Constructors",projectName:"Beaumont scope"}));expect(p.packet?.question.primary).toContain("Beaumont scope");expect(p.packet?.question.primary).toContain("does your team use");expect(p.packet?.whyThisMatters.currentCanonicalState).toBe("UNRESOLVED")});
  it("11 Bechtel scenario separates supplemental labor from full-scope subcontracting",async()=>{const p=await setup().service.plan(input({companyName:"Bechtel",projectName:"Louisiana LNG"}));expect(p.packet?.question.followUp).toContain("full-scope subcontractors")});
  it("12 Hays and Finish Line remain separate objectives",async()=>{const x=setup();const h=await x.service.plan(input({companyName:"Hays",companyId:"hays",targetId:"hays",targetType:"COMPANY_ROLE"}));const f=await x.service.plan(input({need:"WORKFORCE_PARTNER_RELATIONSHIP_UNVERIFIED",companyName:"Finish Line",companyId:"finish",targetId:"finish",targetType:"COMPANY_ROLE"}));expect(h.task?.verificationObjective).not.toBe(f.task?.verificationObjective);expect(x.repository.tasks).toHaveLength(2)});
  it("13 packet includes governed operator context",async()=>{const p=(await setup().service.plan(input())).packet!;expect(p).toMatchObject({whyThisMatters:{blocker:"MISSING_MANPOWER_ACCEPTANCE"},question:{primary:expect.any(String)},authorityRequired:{minimumLevel:"SUBJECT_MATTER_INFORMED"},scopeToConfirm:{projectId:"project-1"},sourceBasis:[{evidenceId:"evidence-1"}],nextAction:"CALL"});expect(p.possibleEffects.length).toBeGreaterThan(0);expect(p.doNotClaim.length).toBeGreaterThan(0)});
  it("14 possible effects explicitly do not mutate canonical state",async()=>{const p=(await setup().service.plan(input())).packet!;expect(p.possibleEffects.every(x=>x.includes("does not change canonical truth"))).toBe(true)});
  it("15 B2 creates no interactions or response assessments",async()=>{const x=setup();await x.service.plan(input());expect(await x.repository.listInteractions("task-1")).toEqual([]);expect(await x.repository.listAssessments("interaction-1")).toEqual([])});
  it("16 qualification question preserves Fly satisfaction as UNKNOWN",async()=>{const p=await setup().service.plan(input({need:"QUALIFICATION_REQUIREMENT_UNKNOWN"}));expect(p.packet?.question.primary).toContain("requirements must");expect(p.packet?.possibleEffects.join(" ")).toContain("Fly satisfaction remains UNKNOWN")});
  it("17 conflict planning preserves both evidence sides",async()=>{const conflicts=[{statement:"Uses staffing vendors",evidenceIds:["a"],scope:{companyScope:"DIVISION"as const},observedAt:"2026-08-01"},{statement:"Direct hire only",evidenceIds:["b"],scope:{companyScope:"DIVISION"as const},observedAt:"2026-08-02"}];const p=await setup().service.plan(input({need:"EXTERNAL_MANPOWER_ACCEPTANCE_CONFLICT",conflicts,staleOrConflicting:true}));expect(p.packet?.conflicts).toEqual(conflicts)});
  it("18 verification priority is deterministic",async()=>{const x=setup();expect((await x.service.plan(input({urgentTemporalWindow:true,nearHotEligibility:true}))).priority).toBe("URGENT");expect((await x.service.plan(input({companyId:"company-2",targetId:"two",urgentTemporalWindow:false,nearHotEligibility:false,staleOrConflicting:true}))).priority).toBe("HIGH")});
  it("19 public research not exhausted prevents task creation",async()=>{const x=setup();expect((await x.service.plan(input({publicEvidenceExhausted:false}))).disposition).toBe("PUBLIC_RESEARCH_REQUIRED");expect(x.repository.tasks).toHaveLength(0)});
  it("20 non-electrical pipefitter planning uses the same rules",async()=>{const p=await setup().service.plan(input({tradeId:"PIPEFITTING",occupationId:"PIPEFITTER",scope:{companyScope:"UNKNOWN",tradeId:"PIPEFITTING",occupationId:"PIPEFITTER"}}));expect(p.packet?.question.primary).toContain("PIPEFITTING");expect(p.task?.tradeId).toBe("PIPEFITTING")});
  it("21 missing route returns a plan but does not create an unactionable task",async()=>{const x=setup();const p=await x.service.plan(input({contact:null}));expect(p.disposition).toBe("NEEDS_CONTACT_ROUTE");expect(p.packet?.nextAction).toBe("FIND_BETTER_ROUTE");expect(x.repository.tasks).toHaveLength(0)});
  it("rejects software defects and prohibited outreach",async()=>{const x=setup();expect((await x.service.plan(input({internalSoftwareDefect:true}))).disposition).toBe("NOT_HUMAN_VERIFICATION_PROBLEM");expect((await x.service.plan(input({companyId:"two",prohibitedOutreach:true}))).disposition).toBe("PROHIBITED_OUTREACH")});
});
