import type { SqlClient } from "../evidence/postgres-evidence-repository";
import type { HumanVerificationDeskRecord } from "../../read-models/human-verification-desk";
type Row=Record<string,unknown>; const date=(v:unknown)=>v?new Date(String(v)):null; const object=(v:unknown)=>v&&typeof v==="object"?v as Record<string,unknown>:{};
const columns=`t.id,t.company_id,t.opportunity_id,t.project_id,t.target_type,t.verification_objective,t.question_type,t.primary_question,t.follow_up_question,t.blocker_code,t.preferred_method,t.status,t.due_at,t.created_at,t.packet_snapshot,coalesce(c.common_name,c.legal_name)company_name,o.title opportunity_title,p.name project_name,p.location_text,cp.name contact_name,cp.title contact_title,cr.route_type,cr.target route_target,cr.verification_state route_trust,cr.stale_after route_stale_after`;
const joins=`from human_verification_tasks t join companies c on c.id=t.company_id left join opportunities o on o.id=t.opportunity_id left join projects p on p.id=t.project_id left join contact_people cp on cp.id=t.contact_person_id left join contact_routes cr on cr.id=t.contact_route_id`;
const map=(r:Row):HumanVerificationDeskRecord=>({id:String(r.id),companyId:String(r.company_id),companyName:r.company_name?String(r.company_name):null,opportunityId:r.opportunity_id?String(r.opportunity_id):null,opportunityTitle:r.opportunity_title?String(r.opportunity_title):null,projectId:r.project_id?String(r.project_id):null,projectName:r.project_name?String(r.project_name):null,location:r.location_text?String(r.location_text):null,contactName:r.contact_name?String(r.contact_name):null,contactTitle:r.contact_title?String(r.contact_title):null,routeType:r.route_type?String(r.route_type):null,routeTarget:r.route_target?String(r.route_target):null,routeTrust:r.route_trust?String(r.route_trust):null,routeStaleAfter:date(r.route_stale_after),targetType:String(r.target_type),verificationObjective:String(r.verification_objective),questionType:r.question_type as HumanVerificationDeskRecord["questionType"],primaryQuestion:String(r.primary_question),followUpQuestion:r.follow_up_question?String(r.follow_up_question):null,blockerCode:r.blocker_code?String(r.blocker_code):null,preferredMethod:r.preferred_method?String(r.preferred_method):null,status:r.status as HumanVerificationDeskRecord["status"],dueAt:date(r.due_at),createdAt:date(r.created_at)!,packetSnapshot:object(r.packet_snapshot)});
export class PostgresHumanVerificationDeskRepository { constructor(private readonly client:SqlClient){} async list(limit=100,offset=0){const q=await this.client.query<Row&{total_count:string}>(`select ${columns},count(*)over()::text total_count ${joins} order by case when t.status in('COMPLETED','CANCELLED','DUPLICATE','UNRESOLVABLE')then 1 else 0 end,t.due_at nulls last,t.created_at,t.id limit $1 offset $2`,[limit,offset]);return{items:q.rows.map(map),total:q.rows.length?Number(q.rows[0].total_count):0}} async get(id:string){const q=await this.client.query<Row>(`select ${columns} ${joins} where t.id=$1`,[id]);return q.rows[0]?map(q.rows[0]):null}
  /** UI-7 addition, mirrors get()/list() -- no by-company read existed before. */
  async listByCompany(companyId:string){const q=await this.client.query<Row>(`select ${columns} ${joins} where t.company_id=$1 order by case when t.status in('COMPLETED','CANCELLED','DUPLICATE','UNRESOLVABLE')then 1 else 0 end,t.due_at nulls last,t.created_at,t.id`,[companyId]);return q.rows.map(map)} }
