import { randomUUID } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { ProductionCaptureRequest, ProductionSourceProfile } from "../../domain/production-source";
import { BechtelAdapter } from "../../server/adapters/production/bechtel-adapter";
import { RosendinAdapter } from "../../server/adapters/production/rosendin-adapter";
import { TpwdConstructionAdapter } from "../../server/adapters/production/tpwd-adapter";
import { ProductionCaptureIngestion } from "../../server/ingestion/production-capture-ingestion";
import { PostgresEvidenceRepository } from "../../server/repositories/evidence/postgres-evidence-repository";
import { PostgresIngestionRepository } from "../../server/repositories/ingestion/postgres-ingestion-repository";
import { PostgresProductionSourceRepository } from "../../server/repositories/production-source/postgres-production-source-repository";
import { EvidenceCaptureService } from "../../server/services/evidence/capture-evidence";
import { canExecuteLive, conservativeCorrelation, deterministicObservationIdentity, nextHealth, structuredFailure } from "../../server/services/production-source/production-source-policy";
const fixtures=[`<h1>Rosendin Journeyman Electrician</h1><p>Austin, Texas JR104653 recruiting@rosendin.com</p>`,`<h1>Bechtel Electrical Field Engineer</h1><p>Port Arthur, Texas Port Arthur LNG 297735</p>`,`<h1>Texas Parks and Wildlife Department Construction Bid Opportunities</h1><p>Current Texas public construction projects</p>`];
const transport=(body:string,status=200)=>({get:async(url:string)=>({status,url,contentType:"text/html",body,headers:{"cache-control":"public"}})});
const request=():ProductionCaptureRequest=>({executionId:randomUUID(),requestedTarget:"public-target",cursor:null,policyDecisionId:randomUUID(),asOf:new Date("2026-08-21T12:00:00Z")});
const profile=(readiness:ProductionSourceProfile["readiness"]="APPROVED_FOR_LIVE_CAPTURE"):ProductionSourceProfile=>({sourceId:"source",family:"COMPANY_CAREERS",tier:"DIRECT_CORPORATE",capabilities:["WORKFORCE_DEMAND"],methods:["STATIC_HTML"],readiness,schedule:{desiredCadenceMinutes:1440,minimumIntervalMinutes:60,freshnessTargetMinutes:2880,nextEligibleCapture:null,backoff:{initialMinutes:15,maximumMinutes:1440,multiplier:2},localRestrictions:[]},rateLimit:{requests:1,windowMinutes:1},identityVersion:"source@1",metadata:{}});
const health=()=>({state:"HEALTHY"as const,lastAttemptAt:null,lastSuccessAt:null,consecutiveFailures:0,lastFailure:null,parserFailure:false,structureChanged:false,emptyResultCount:0,freshUntil:null,latencyMs:null});
describe("Phase 2B production adapters",()=>{let db:PGlite,source:string,policy:string,evidenceRepo:PostgresEvidenceRepository,service:ProductionCaptureIngestion;
beforeAll(async()=>{db=new PGlite();for(const f of(await readdir(resolve(process.cwd(),"supabase/migrations"))).filter(x=>x.endsWith(".sql")).sort())await db.exec(await readFile(resolve(process.cwd(),"supabase/migrations",f),"utf8"));source=(await db.query<{id:string}>("insert into sources(name)values('Phase 2B')returning id")).rows[0].id;policy=(await db.query<{id:string}>("insert into source_capture_policy_decisions(source_id,capture_method,decision,reason,reviewed_at,reviewed_by,policy_version)values($1,'HTTP_FETCH','ALLOWED','public page',now(),'manager','2b')returning id",[source])).rows[0].id;evidenceRepo=new PostgresEvidenceRepository(db);service=new ProductionCaptureIngestion(new EvidenceCaptureService(evidenceRepo),new PostgresProductionSourceRepository(db),new PostgresIngestionRepository(db),evidenceRepo)});afterAll(async()=>db.close());
it("1 fixture approval is not live approval",()=>expect(canExecuteLive(profile("APPROVED_FOR_FIXTURE"),"ALLOW",request().asOf)).toBe(false));
it("2 requires live readiness",()=>expect(canExecuteLive(profile(),"ALLOW",request().asOf)).toBe(true));
it("3 requires policy allow",()=>expect(canExecuteLive(profile(),"REVIEW_REQUIRED",request().asOf)).toBe(false));
it("4 deny prevents transport",async()=>{let called=false;const a=new RosendinAdapter({get:async()=>{called=true;throw Error()}});const r=request();r.policyDecisionId=policy;expect((await service.run(source,a,r,profile(),"DENY")).status).toBe("FAILED");expect(called).toBe(false)});
it("5 blocked source cannot execute",()=>expect(canExecuteLive(profile("BLOCKED"),"ALLOW",request().asOf)).toBe(false));
it("6 approved source executes",async()=>expect((await new RosendinAdapter(transport(fixtures[0])).capturePage(request())).result.status).toBe("CAPTURED"));
it("7 parses Rosendin",async()=>expect((await new RosendinAdapter(transport(fixtures[0])).capturePage(request())).observations[0]).toMatchObject({organization:"Rosendin",externalId:"JR104653"}));
it("8 parses Bechtel",async()=>expect((await new BechtelAdapter(transport(fixtures[1])).capturePage(request())).observations[0].facts.project).toBe("Port Arthur LNG"));
it("9 parses TPWD",async()=>expect((await new TpwdConstructionAdapter(transport(fixtures[2])).capturePage(request())).observations[0].kind).toBe("PROJECT_PROCUREMENT"));
it("10 persists raw evidence",async()=>{const r=request();r.policyDecisionId=policy;const x=await service.run(source,new RosendinAdapter(transport(fixtures[0])),r,profile(),"ALLOW");expect(x.status==="SUCCESS"&&x.evidence.id).toBeTruthy()});
it("11 integrates demand signal",async()=>{const r=request();r.policyDecisionId=policy;const x=await service.run(source,new RosendinAdapter(transport(fixtures[0])),r,profile(),"ALLOW");expect(x.status==="SUCCESS"&&x.demandSignalId).toBeTruthy()});
it("12 persists non-demand observation",async()=>{const r=request();r.policyDecisionId=policy;const x=await service.run(source,new TpwdConstructionAdapter(transport(fixtures[2])),r,profile(),"ALLOW");expect(x.status==="SUCCESS"&&x.observations[0].kind).toBe("PROJECT_PROCUREMENT")});
it("13 audits requested target",async()=>{const r=request();r.policyDecisionId=policy;await service.run(source,new RosendinAdapter(transport(fixtures[0])),r,profile(),"ALLOW");expect((await db.query<{requested_target:string}>("select requested_target from production_source_executions where id=$1",[r.executionId])).rows[0].requested_target).toBe("public-target")});
it("14 audits failed attempts",async()=>{const r=request();r.policyDecisionId=policy;await service.run(source,new RosendinAdapter(transport("",500)),r,profile(),"ALLOW");expect((await db.query<{result:string}>("select result from production_source_executions where id=$1",[r.executionId])).rows[0].result).toBe("FAILURE")});
it("15 represents HTTP failure",()=>expect(structuredFailure("HTTP_FAILURE","500",request().asOf,500)).toMatchObject({classification:"HTTP_FAILURE",httpStatus:500}));
it("16 transient failure is retryable",()=>expect(structuredFailure("TIMEOUT","x",request().asOf).retryable).toBe(true));
it("17 compliance failure is non-retryable",()=>expect(structuredFailure("COMPLIANCE_BLOCKED","x",request().asOf).retryable).toBe(false));
it("18 retains rate limit metadata",()=>expect(profile().rateLimit).toEqual({requests:1,windowMinutes:1}));
it("19 enforces minimum interval",()=>{const p=profile();p.schedule.nextEligibleCapture=new Date("2026-08-22");expect(canExecuteLive(p,"ALLOW",request().asOf)).toBe(false)});
it("20 deterministic backoff metadata",()=>expect(profile().schedule.backoff).toEqual({initialMinutes:15,maximumMinutes:1440,multiplier:2}));
it("21 compliance denial is never retried",()=>expect(structuredFailure("COMPLIANCE_BLOCKED","x",request().asOf).retryable).toBe(false));
it("22 deterministic observation identity",()=>expect(deterministicObservationIdentity("s","x","a","h")).toBe(deterministicObservationIdentity("s","x","a","h")));
it("23 within-source duplicate identity",()=>expect(deterministicObservationIdentity("s","x","a","h")).toBe(deterministicObservationIdentity("s","x","c","h")));
it("24 cross-source independence",()=>expect(deterministicObservationIdentity("s1","x","a","h")).not.toBe(deterministicObservationIdentity("s2","x","a","h")));
it("25 independent observations persist",async()=>{const q=await db.query<{count:string}>("select count(distinct source_id||':'||observation_identity)::text count from source_observation_identities");expect(Number(q.rows[0].count)).toBeGreaterThan(0)});
it("26 retains stable external IDs",async()=>expect((await new RosendinAdapter(transport(fixtures[0])).capturePage(request())).result.externalIdentifiers["0"]).toBe("JR104653"));
it("27 rejects fuzzy merge",()=>expect(conservativeCorrelation({title:"Electrician",city:"Austin"},{title:"Electrician",city:"Austin"})).toBeNull());
it("28 reconstructs provenance",async()=>{const q=await db.query<{count:string}>("select count(*)::text count from source_observation_identities o join raw_evidence e on e.id=o.evidence_id join production_source_executions x on x.id=o.execution_id");expect(Number(q.rows[0].count)).toBeGreaterThan(0)});
it("29 unknown fields remain unknown",async()=>expect((await new RosendinAdapter(transport(fixtures[0])).capturePage(request())).observations[0].facts.current).toBeNull());
it("30 does not fabricate company",async()=>expect((await new RosendinAdapter(transport("<p>Journeyman Electrician JR1</p>")).capturePage(request())).observations).toHaveLength(0));
it("31 does not fabricate project",async()=>expect((await new BechtelAdapter(transport("<p>Electrical Field Engineer 297735 Bechtel</p>")).capturePage(request())).observations[0].facts.project).toBeNull());
it("32 does not fabricate buyer",async()=>expect((await new TpwdConstructionAdapter(transport("<p>Construction Bid Opportunities Texas</p>")).capturePage(request())).observations[0].organization).toBeNull());
for(const [n,key] of [[33,"verified"],[34,"manpowerAcceptance"],[35,"contactGrade"],[36,"eligibility"],[37,"score"],[38,"commercialAction"]]as const)it(`${n} does not create ${key}`,async()=>expect((await new RosendinAdapter(transport(fixtures[0])).capturePage(request())).observations[0]).not.toHaveProperty(key));
it("39 deterministic transport has no Internet dependency",()=>expect(transport("x").get("fixture://local")).resolves.toMatchObject({body:"x"}));
it("40 preserves Phase 2C boundary",()=>expect([RosendinAdapter,BechtelAdapter,TpwdConstructionAdapter]).toHaveLength(3));
it("records health backoff outcomes without scheduler",()=>expect(nextHealth(health(),{at:request().asOf,success:false,empty:false,failure:"RATE_LIMITED"},"APPROVED_FOR_LIVE_CAPTURE")).toMatchObject({state:"DEGRADED",lastFailure:"RATE_LIMITED"}));
});
