import{readFile}from"node:fs/promises";import{resolve}from"node:path";import{renderToStaticMarkup}from"react-dom/server";import{describe,expect,it}from"vitest";import Home from"../../app/page";import CommandCenter from"../../app/command-center/page";import Opportunities from"../../app/opportunities/page";import Companies from"../../app/companies/page";import Projects from"../../app/projects/page";import Contacts from"../../app/contacts/page";import Signals from"../../app/signals/page";import Verification from"../../app/verification/page";import Actions from"../../app/actions/page";import Hot from"../../app/hot/page";import NearReady from"../../app/near-ready/page";import Evidence from"../../app/evidence/page";import Relationships from"../../app/relationships/page";import Sources from"../../app/sources/page";import Activity from"../../app/activity/page";import Settings from"../../app/settings/page";import{NAVIGATION,isActiveRoute}from"../../components/shell/app-shell";import{CurrentnessBadge,ScopeBadge,TRUST_STATES,TrustState}from"../../components/ui/status-primitives";import{EmptyState,ErrorState,Skeleton}from"../../components/ui/foundation";
describe("Phase UI-1 professional frontend foundation",()=>{
  it("root redirects to Command Center",()=>expect(()=>Home()).toThrow(/NEXT_REDIRECT/));
  it("sidebar architecture contains all approved routes without duplicates",()=>{const paths=NAVIGATION.flatMap(x=>x.items.map(i=>i.href));expect(paths).toEqual(["/command-center","/opportunities","/companies","/projects","/contacts","/signals","/verification","/actions","/hot","/near-ready","/evidence","/relationships","/sources","/activity","/settings"]);expect(new Set(paths).size).toBe(paths.length)});
  it("active-route matching is exact or a child route",()=>{expect(isActiveRoute("/opportunities","/opportunities")).toBe(true);expect(isActiveRoute("/opportunities/123","/opportunities")).toBe(true);expect(isActiveRoute("/companies","/opportunities")).toBe(false)});
  it("all major route scaffolds render honest capability language",()=>{for(const Page of[Opportunities,Companies,Projects,Contacts,Signals,Verification,Actions,Hot,NearReady,Evidence,Relationships,Sources,Activity,Settings]){const html=renderToStaticMarkup(<Page/>);expect(html).toMatch(/UI integration pending|Planned capability/);expect(html).toContain("No production intelligence is loaded or simulated")}});
  it("Command Center renders no invented business metrics",()=>{const html=renderToStaticMarkup(<CommandCenter/>);expect(html).toContain("No canonical data loaded");expect(html).not.toMatch(/Acme|Bechtel|Hays|MMR|Finish Line|HOT [1-9]/)});
  it("every trust state has accessible icon-and-text semantics",()=>{for(const state of Object.keys(TRUST_STATES)as(keyof typeof TRUST_STATES)[]){const html=renderToStaticMarkup(<TrustState state={state}/>);expect(html).toContain("aria-label");expect(html).toContain(TRUST_STATES[state][0]);expect(html).toContain("<svg")}});
  it("currentness states expose accessible text",()=>{for(const state of["CURRENT","AGING","STALE","UNKNOWN"]as const)expect(renderToStaticMarkup(<CurrentnessBadge state={state}/>)).toContain("Currentness:")});
  it("unknown scope is explicitly not global",()=>{const html=renderToStaticMarkup(<ScopeBadge scope="UNKNOWN"/>);expect(html).toContain("Scope unknown — not global");expect(html).not.toContain("Company scope")});
  it("foundational empty, loading, and error states are semantic",()=>{expect(renderToStaticMarkup(<EmptyState title="No data" description="Pending"/>)).toContain("aria-labelledby");expect(renderToStaticMarkup(<Skeleton/>)).toContain('role="status"');expect(renderToStaticMarkup(<ErrorState/>)).toContain('role="alert"')});
  it("global CSS includes focus, mobile touch, and reduced-motion baselines",async()=>{const css=await readFile(resolve(process.cwd(),"src/app/globals.css"),"utf8");expect(css).toContain(":focus-visible");expect(css).toContain("min-height:44px");expect(css).toContain("prefers-reduced-motion")});
});
