import{describe,expect,it}from"vitest";
import type{ConversionEvidenceInput}from"../../domain/commercial-conversion";
import type{TrackedDiscoverySignal}from"../../domain/discovery-promotion";
import{NO_ACTIONABILITY_EVIDENCE}from"../../domain/opportunity-actionability";
import{DISCOVERY_SOURCE_ORGANIZATION_PROFILES,conversionGraph,convertDiscoverySignal,previewConversionDecision,prioritizeCommercialConversion,rankConversionCohort,resolveOrganizationProvenance}from"../../server/services/commercial-conversion/commercial-conversion-service";

const at=new Date("2026-08-30T02:00:00Z");
const signal=(id="real-electrician"):TrackedDiscoverySignal=>({trackedId:`tracked-discovery:${id}`,signalId:`demand-signal:${id}`,externalId:id,sourceKey:"approved-source",sourceUrl:"https://example.test/public-listing",title:"Journeyman Electrician",organization:"Explicit Employer",location:"Houston, TX",recognizedRoles:["JOURNEYMAN_ELECTRICIAN"],roleMatches:[{role:"JOURNEYMAN_ELECTRICIAN",phrase:"Journeyman Electrician"}],tier:"STANDARD",observedAt:at,reasons:["explicit electrician role"],ruleVersion:"fixture"});
const base=(id="real-electrician"):ConversionEvidenceInput=>({signal:signal(id),evidenceIds:[`evidence:${id}`],employer:"Explicit Employer",companyRole:"PROBABLE_END_EMPLOYER",companyRoleEvidenceIds:[`evidence:${id}`],project:null,buyer:null,wage:null,perDiemOrIncentive:null,schedule:null,headcount:null,acceptance:null,contacts:[],actionability:NO_ACTIONABILITY_EVIDENCE(`conversion:${id}`),conflicts:[]});
const acceptance=(verificationState:"UNVERIFIED"|"VERIFIED"="UNVERIFIED")=>({id:"af01",category:"STAFFING_VENDOR_ACCEPTED",verificationState,accepted:true,observedAt:at,validUntil:new Date("2026-12-01T00:00:00Z"),evidenceIds:["evidence:af01"]});
const contact=(verificationState:"UNVERIFIED"|"VERIFIED"="UNVERIFIED",gradeCandidate:"A"|"B"|"C"|"D"="B",routeType="PROFESSIONAL_EMAIL")=>({id:"route",organization:"Explicit Employer",function:"PROCUREMENT",routeType,target:"vendor@example.test",gradeCandidate,verificationState,observedAt:at,staleAfter:new Date("2026-12-01T00:00:00Z"),evidenceIds:["evidence:route"]});

describe("Phase 2S commercial conversion truth boundaries",()=>{
  it("real discovered signal with unknown buyer remains a structured trackable dossier",()=>{const d=convertDiscoverySignal(base());expect(d.buyer).toBeNull();expect(d.discoverySignalId).toBe("demand-signal:real-electrician");expect(d.failedConversion).toBe(true)});
  it("job posting alone does not verify AF-01",()=>expect(convertDiscoverySignal(base()).acceptance).toBeNull());
  it("vendor-registration/AF-01 candidate remains unverified and does not clear HOT-A",()=>{const d=convertDiscoverySignal({...base(),acceptance:acceptance()});expect(d.acceptance!.verificationState).toBe("UNVERIFIED");expect(d.eligibility.find(x=>x.eligibilityType==="HOT_A_ELIGIBLE")!.eligible).toBe(false)});
  it("unverified recruiter contact never becomes Grade A authority or clears verified gates",()=>{const d=convertDiscoverySignal({...base(),contacts:[contact("UNVERIFIED","A","RECRUITER_EMAIL")]});expect(d.contacts[0].gradeCandidate).toBe("A");expect(d.eligibility.every(x=>!x.eligible)).toBe(true);expect(d.verificationQueue.map(x=>x.kind)).toContain("VERIFY_CONTACT_GRADE")});
  it("official vendor route is preserved without claiming buyer authority",()=>{const d=convertDiscoverySignal({...base(),contacts:[contact("VERIFIED","C","VENDOR_REGISTRATION")]});expect(d.buyer).toBeNull();expect(d.contacts[0].routeType).toBe("VENDOR_REGISTRATION");expect(d.eligibility.find(x=>x.eligibilityType==="VAMO_ELIGIBLE")!.eligible).toBe(true)});
  it("UNKNOWN temporal state remains UNKNOWN without explicit evidence",()=>expect(convertDiscoverySignal(base()).temporalState).toBe("UNKNOWN"));
  it("expired opportunity cannot become Active HOT even with verified gates",()=>{const x={...base(),acceptance:acceptance("VERIFIED"),contacts:[contact("VERIFIED")],actionability:{...NO_ACTIONABILITY_EVIDENCE("conversion:real-electrician"),deadlines:[{kind:"ORIGINAL"as const,date:new Date("2026-08-01"),observedAt:at,evidenceIds:["evidence:deadline"]}]}};const d=convertDiscoverySignal(x);expect(d.eligibility.find(e=>e.eligibilityType==="HOT_A_ELIGIBLE")!.eligible).toBe(true);expect(d.activeHot.every(h=>!h.active)).toBe(true)});
  it("verified AF-01 plus verified actionable route affects eligibility only through the real engine",()=>{const d=convertDiscoverySignal({...base(),project:"Explicit Project",acceptance:acceptance("VERIFIED"),contacts:[contact("VERIFIED")],actionability:{...NO_ACTIONABILITY_EVIDENCE("conversion:real-electrician"),explicitStatus:"OPEN"}});expect(d.eligibility.find(e=>e.eligibilityType==="HOT_A_ELIGIBLE")!.eligible).toBe(true);expect(d.score.state).toBe("SCORED");expect(d.activeHot.find(h=>h.hotType==="HOT_A")!.active).toBe(true)});
  it("candidate evidence alone does not clear verified gates",()=>expect(convertDiscoverySignal({...base(),acceptance:acceptance(),contacts:[contact()]}).score.state).toBe("NOT_SCORABLE"));
  it("human preview uses the real eligibility/score/action/Active-HOT path without persistence",()=>{const input={...base(),project:"Explicit Project",acceptance:acceptance(),contacts:[contact()],actionability:NO_ACTIONABILITY_EVIDENCE("conversion:real-electrician")};const p=previewConversionDecision(input,{verifyAcceptance:true,verifyContactIds:["route"],explicitStatus:"OPEN"});expect(p.current.score.state).toBe("NOT_SCORABLE");expect(p.ifVerified.score.state).toBe("SCORED");expect(p.ifVerified.activeHot.some(h=>h.active)).toBe(true);expect(p.persisted).toBe(false)});
  it("does not use a false would-unlock-HOT heuristic",()=>{const p=previewConversionDecision({...base(),acceptance:acceptance()},{verifyAcceptance:true});expect(p.ifVerified.eligibility.every(e=>!e.eligible)).toBe(true);expect(p.ifVerified.activeHot.every(h=>!h.active)).toBe(true)});
  it("missing buyer never silently invents one",()=>expect(conversionGraph(base()).companyRoles.some(r=>r.role==="MANPOWER_BUYER")).toBe(false));
  it("conflicting evidence remains preserved and blocks eligibility",()=>{const d=convertDiscoverySignal({...base(),conflicts:["official pages disagree on company role"]});expect(d.conflicts).toEqual(["official pages disagree on company role"]);expect(d.eligibility.every(e=>!e.eligible)).toBe(true)});
  it("failed conversion remains a valid structured result with blockers and verification work",()=>{const d=convertDiscoverySignal(base());expect(d.failedConversion).toBe(true);expect(d.conversionBlockers.length).toBeGreaterThan(0);expect(d.verificationQueue.length).toBeGreaterThan(0)});
  it("priority is versioned, deterministic, and does not mutate eligibility or input",()=>{const x=base(),before=JSON.stringify(x),a=prioritizeCommercialConversion(x),b=prioritizeCommercialConversion(x);expect(a).toEqual(b);expect(a.ruleVersion).toBe("commercial-conversion-priority@1.0.0");expect(JSON.stringify(x)).toBe(before);expect(convertDiscoverySignal(x).eligibility.every(e=>!e.eligible)).toBe(true)});
  it("cohort ranking is deterministic",()=>{const xs=[base("b"),{...base("a"),wage:"$42/hr"}];expect(rankConversionCohort(xs,2).map(x=>x.input.signal.externalId)).toEqual(["a","b"])});
  it("duplicate evidence does not duplicate opportunity identity or dossier evidence",()=>{const x={...base(),evidenceIds:["e","e"]};expect(conversionGraph(x).opportunity.identityKey).toBe("conversion:real-electrician");expect(convertDiscoverySignal(x).evidenceIds).toEqual(["e"])});
  it("produces recommendation-only data and performs no automatic outreach",()=>{const d=convertDiscoverySignal(base());expect(typeof d.commercialAction).toBe("string");expect(JSON.stringify(d)).not.toMatch(/outreachExecuted|emailSent|formSubmitted/)});
  it("does not activate prohibited or under-review sources",()=>expect(JSON.stringify(convertDiscoverySignal(base()))).not.toMatch(/ibew20|tradesmenup|smartbuy|sam\.gov|usajobs/i));
  it("Active HOT is impossible unless all existing verified and temporal gates pass",()=>{for(const x of[base(),{...base(),acceptance:acceptance("VERIFIED")},{...base(),contacts:[contact("VERIFIED")]},{...base(),acceptance:acceptance("VERIFIED"),contacts:[contact("VERIFIED")]}])expect(convertDiscoverySignal(x).activeHot.every(h=>!h.active)).toBe(true)});
});

describe("Phase 2S-B source organization provenance",()=>{
  const profile=(key:keyof typeof DISCOVERY_SOURCE_ORGANIZATION_PROFILES)=>({...DISCOVERY_SOURCE_ORGANIZATION_PROFILES[key],sourceUrl:`https://example.test/${key}`,observedAt:at});
  it("official first-party career source establishes posting organization",()=>expect(resolveOrganizationProvenance(null,profile("strike"))).toMatchObject({organization:"Strike",employer:"Strike",basis:"VERIFIED_FIRST_PARTY_SOURCE_IDENTITY",companyRole:"PROBABLE_END_EMPLOYER"}));
  it("first-party identity establishes neither buyer nor AF-01 nor contact authority",()=>{const p=resolveOrganizationProvenance(null,profile("bechtel")),d=convertDiscoverySignal({...base(),employer:p.employer,companyRole:p.companyRole,organizationProvenance:p});expect(d.buyer).toBeNull();expect(d.acceptance).toBeNull();expect(d.contacts).toEqual([])});
  it("union identity cannot become employer",()=>expect(resolveOrganizationProvenance(null,profile("ibew716"))).toMatchObject({organization:null,employer:null,basis:"UNKNOWN"}));
  it("row-stated union contractor becomes contractor and employer evidence",()=>expect(resolveOrganizationProvenance("Big State Electric",profile("ibew716"))).toMatchObject({organization:"Big State Electric",employer:"Big State Electric",contractor:"Big State Electric",basis:"ROW_STATED_DISPATCH_CONTRACTOR"}));
  it("staffing source remains a staffing intermediary distinct from unknown end client",()=>expect(resolveOrganizationProvenance(null,profile("trillium"))).toMatchObject({organization:"Trillium Staffing",employer:"Trillium Staffing",staffingIntermediary:"Trillium Staffing",companyRole:"STAFFING_COMPANY"}));
  it("staffing source identity does not establish client AF-01",()=>{const p=resolveOrganizationProvenance(null,profile("trillium")),d=convertDiscoverySignal({...base(),employer:p.employer,companyRole:p.companyRole,organizationProvenance:p});expect(d.buyer).toBeNull();expect(d.acceptance).toBeNull();expect(d.eligibility.find(e=>e.eligibilityType==="HOT_A_ELIGIBLE")!.eligible).toBe(false)});
  it("direct listing organization outranks inherited identity",()=>expect(resolveOrganizationProvenance("Explicit Subsidiary",profile("strike"))).toMatchObject({organization:"Explicit Subsidiary",basis:"DIRECT_LISTING"}));
  it("direct/inherited conflict is preserved",()=>expect(resolveOrganizationProvenance("Explicit Subsidiary",profile("strike")).conflicts).toEqual(['direct listing organization "Explicit Subsidiary" conflicts with source identity "Strike"']));
  it("unknown source ownership produces no inherited organization",()=>expect(resolveOrganizationProvenance(null,{sourceId:"unknown",sourceUrl:"https://example.test",identityClass:"UNKNOWN_SOURCE_IDENTITY",organization:"Claimed Name",ownershipEvidence:"ownership not verified",observedAt:at})).toMatchObject({organization:null,employer:null,basis:"UNKNOWN"}));
  it("provenance metadata is deterministic",()=>expect(resolveOrganizationProvenance(null,profile("bechtel"))).toEqual(resolveOrganizationProvenance(null,profile("bechtel"))));
  it("replay is idempotent",()=>{const p=resolveOrganizationProvenance(null,profile("bechtel")),x={...base(),employer:p.employer,companyRole:p.companyRole,organizationProvenance:p};expect(convertDiscoverySignal(x)).toEqual(convertDiscoverySignal(x))});
  it("legitimate provenance does not change eligibility or Active HOT semantics",()=>{const before=convertDiscoverySignal(base()),p=resolveOrganizationProvenance("Explicit Employer",profile("strike")),after=convertDiscoverySignal({...base(),organizationProvenance:p});expect(after.eligibility.map(e=>e.eligible)).toEqual(before.eligibility.map(e=>e.eligible));expect(after.activeHot.map(h=>h.active)).toEqual(before.activeHot.map(h=>h.active))});
  it("source identity never auto-verifies facts or performs outreach",()=>{for(const key of["strike","trillium","bechtel"]as const){const p=resolveOrganizationProvenance(null,profile(key)),d=convertDiscoverySignal({...base(key),employer:p.employer,companyRole:p.companyRole,organizationProvenance:p});expect(d.acceptance).toBeNull();expect(d.contacts).toEqual([]);expect(d.activeHot.every(h=>!h.active)).toBe(true);expect(JSON.stringify(d)).not.toMatch(/emailSent|formSubmitted|outreachExecuted/)}});
  it("does not activate unauthorized sources",()=>expect(Object.keys(DISCOVERY_SOURCE_ORGANIZATION_PROFILES).sort()).toEqual(["bechtel","ibew716","strike","trillium"]));
});
