import type { ContactPersonCandidate, ContactPersonRecord, ContactRouteCandidate, ContactRouteRecord, RouteGradeEvaluation } from "../../../domain/contact";
import type { SqlClient } from "../evidence/postgres-evidence-repository";
import type { ContactRepository } from "./contact-repository";
interface PersonRow { id:string; company_id:string; name:string; normalized_name:string; title:string|null; department:string|null; contact_function:ContactPersonRecord["contactFunction"]; public_professional_profile_url:string|null; evidence_id:string|null; verification_state:ContactPersonRecord["verificationState"]; first_seen_at:string|Date; last_seen_at:string|Date; stale_after:string|Date|null; verification_due_at:string|Date|null; language_status:ContactPersonRecord["languageStatus"]; language_evidence_id:string|null; notes:string|null; contact_metadata:Record<string,unknown> }
interface RouteRow { id:string; company_id:string; contact_person_id:string|null; route_type:ContactRouteRecord["routeType"]; target:string; observed_target:string; normalized_target:string; route_grade:ContactRouteRecord["routeGrade"]; lifecycle:ContactRouteRecord["lifecycle"]; verification_state:ContactRouteRecord["verificationState"]; evidence_id:string|null; first_seen_at:string|Date; last_seen_at:string|Date; last_verified_at:string|Date|null; stale_after:string|Date|null; verification_due_at:string|Date|null; route_metadata:Record<string,unknown> }
interface GradeRow { id:string; contact_route_id:string; grade:RouteGradeEvaluation["grade"]; reason:string; rule_version:string; evaluated_at:string|Date; inputs:Record<string,unknown> }
const personCols="id,company_id,name,normalized_name,title,department,contact_function,public_professional_profile_url,evidence_id,verification_state,first_seen_at,last_seen_at,stale_after,verification_due_at,language_status,language_evidence_id,notes,contact_metadata";
const routeCols="id,company_id,contact_person_id,route_type,target,observed_target,normalized_target,route_grade,lifecycle,verification_state,evidence_id,first_seen_at,last_seen_at,last_verified_at,stale_after,verification_due_at,route_metadata";
const d=(v:string|Date|null)=>v===null?null:new Date(v);
const person=(r:PersonRow):ContactPersonRecord=>({id:r.id,companyId:r.company_id,fullName:r.name,normalizedName:r.normalized_name,title:r.title,department:r.department,contactFunction:r.contact_function,professionalProfileUrl:r.public_professional_profile_url,evidenceId:r.evidence_id,verificationState:r.verification_state,observedAt:new Date(r.first_seen_at),firstSeenAt:new Date(r.first_seen_at),lastSeenAt:new Date(r.last_seen_at),staleAfter:d(r.stale_after),verificationDueAt:d(r.verification_due_at),languageStatus:r.language_status,languageEvidenceId:r.language_evidence_id,notes:r.notes,metadata:r.contact_metadata});
const route=(r:RouteRow):ContactRouteRecord=>({id:r.id,companyId:r.company_id,contactPersonId:r.contact_person_id,routeType:r.route_type,target:r.target,observedTarget:r.observed_target,normalizedTarget:r.normalized_target,routeGrade:r.route_grade,lifecycle:r.lifecycle,verificationState:r.verification_state,evidenceId:r.evidence_id,observedAt:new Date(r.first_seen_at),firstSeenAt:new Date(r.first_seen_at),lastSeenAt:new Date(r.last_seen_at),lastVerifiedAt:d(r.last_verified_at),staleAfter:d(r.stale_after),verificationDueAt:d(r.verification_due_at),metadata:r.route_metadata});
export class PostgresContactRepository implements ContactRepository {
 constructor(private readonly client:SqlClient){}
 async upsertPerson(c:ContactPersonCandidate,n:string,key:string){const q=await this.client.query<PersonRow>(`insert into contact_people(company_id,name,normalized_name,title,department,contact_function,public_professional_profile_url,evidence_id,verification_state,verified_at,first_seen_at,last_seen_at,stale_after,verification_due_at,language_status,language_evidence_id,notes,contact_metadata,person_identity_key) values($1,$2,$3,$4,$5,$6,$7,$8,$9::verification_state,case when $9::verification_state='VERIFIED' then $10::timestamptz end,$10,$10,$11,$12,$13,$14,$15,$16::jsonb,$17) on conflict(person_identity_key) where person_identity_key is not null do update set last_seen_at=excluded.last_seen_at,updated_at=excluded.last_seen_at returning ${personCols}`,[c.companyId,c.fullName,n,c.title??null,c.department??null,c.contactFunction,c.professionalProfileUrl??null,c.evidenceId??null,c.verificationState??"UNVERIFIED",c.observedAt.toISOString(),c.staleAfter?.toISOString()??null,c.verificationDueAt?.toISOString()??null,c.languageStatus??"UNKNOWN",c.languageEvidenceId??null,c.notes??null,JSON.stringify(c.metadata??{}),key]);return person(q.rows[0]);}
 async upsertRoute(c:ContactRouteCandidate,n:string){const q=await this.client.query<RouteRow>(`insert into contact_routes(company_id,contact_person_id,route_type,target,observed_target,normalized_target,lifecycle,verification_state,evidence_id,first_seen_at,last_seen_at,last_verified_at,stale_after,verification_due_at,route_metadata) values($1,$2,$3,$4,$4,$5,$6,$7,$8,$9,$9,$10,$11,$12,$13::jsonb) on conflict(company_id,coalesce(contact_person_id,'00000000-0000-0000-0000-000000000000'::uuid),route_type,normalized_target) where normalized_target is not null and superseded_by_route_id is null do update set last_seen_at=excluded.last_seen_at,updated_at=excluded.last_seen_at returning ${routeCols}`,[c.companyId,c.contactPersonId??null,c.routeType,c.target,n,c.lifecycle??"UNKNOWN",c.verificationState??"UNVERIFIED",c.evidenceId??null,c.observedAt.toISOString(),c.lastVerifiedAt?.toISOString()??null,c.staleAfter?.toISOString()??null,c.verificationDueAt?.toISOString()??null,JSON.stringify(c.metadata??{})]);return route(q.rows[0]);}
 async getRoute(id:string){const q=await this.client.query<RouteRow>(`select ${routeCols} from contact_routes where id=$1`,[id]);return q.rows[0]?route(q.rows[0]):null;}
 async listRoutes(companyId:string){const q=await this.client.query<RouteRow>(`select ${routeCols} from contact_routes where company_id=$1 order by first_seen_at,id`,[companyId]);return q.rows.map(route);}
 async linkEvidence(kind:"CONTACT_PERSON"|"CONTACT_ROUTE",id:string,evidenceId:string){const col=kind==="CONTACT_PERSON"?"contact_person_id":"contact_route_id";await this.client.query(`insert into evidence_links(evidence_id,link_type,${col}) values($1,'SUPPORTS',$2) on conflict(evidence_id,${col},link_type) where ${col} is not null do nothing`,[evidenceId,id]);}
 async saveGrade(i:Omit<RouteGradeEvaluation,"id">){const q=await this.client.query<GradeRow>(`with updated as(update contact_routes set route_grade=$2,updated_at=$5 where id=$1),saved as(insert into contact_route_grade_evaluations(contact_route_id,grade,reason,rule_version,evaluated_at,inputs) values($1,$2,$3,$4,$5,$6::jsonb) returning *) select id,contact_route_id,grade,reason,rule_version,evaluated_at,inputs from saved`,[i.contactRouteId,i.grade,i.reason,i.ruleVersion,i.evaluatedAt.toISOString(),JSON.stringify(i.inputs)]);const r=q.rows[0];return{id:r.id,contactRouteId:r.contact_route_id,grade:r.grade,reason:r.reason,ruleVersion:r.rule_version,evaluatedAt:new Date(r.evaluated_at),inputs:r.inputs};}
 async listGrades(id:string){const q=await this.client.query<GradeRow>(`select id,contact_route_id,grade,reason,rule_version,evaluated_at,inputs from contact_route_grade_evaluations where contact_route_id=$1 order by evaluated_at,created_at,id`,[id]);return q.rows.map(r=>({id:r.id,contactRouteId:r.contact_route_id,grade:r.grade,reason:r.reason,ruleVersion:r.rule_version,evaluatedAt:new Date(r.evaluated_at),inputs:r.inputs}));}
}
