import type { CreateHumanVerificationTaskInput, HumanAnswerDisposition, HumanCommercialMechanism, HumanVerificationQuestionType } from "../../../domain/human-verification";
import type { HumanVerificationNeed, HumanVerificationPacket, HumanVerificationPlan, HumanVerificationPlanningInput, HumanVerificationPriority } from "../../../domain/human-verification-planning";
import { isVerifiedPositiveManpowerAcceptance, normalizeManpowerAcceptanceResult } from "../../../domain/manpower-acceptance";
import type { VerificationTargetType } from "../../../domain/verification";
import type { HumanVerificationRepository } from "../../repositories/human-verification/human-verification-repository";
import { HUMAN_VERIFICATION_RULE_VERSION, HumanVerificationService } from "./human-verification-service";

export const HUMAN_VERIFICATION_PLANNING_RULE_VERSION = "human-verification-planning@1.0.0";
const af01Needs = new Set<HumanVerificationNeed>(["EXTERNAL_MANPOWER_ACCEPTANCE_UNKNOWN", "EXTERNAL_MANPOWER_ACCEPTANCE_CONFLICT", "STALE_COMMERCIAL_EVIDENCE"]);
const mechanisms: HumanCommercialMechanism[] = ["DIRECT_EXTERNAL_MANPOWER", "MSP_OR_STAFFING_PROGRAM", "FULL_SCOPE_SUBCONTRACTORS_ONLY", "DIRECT_HIRE_INTERNAL_ONLY", "NO_EXTERNAL_MANPOWER", "WORKFORCE_PARTNER_OR_SUBVENDOR", "RECRUITING_ONLY", "PAYROLL_ONLY", "OTHER_MECHANISM", "MECHANISM_UNKNOWN"];
const dispositions: HumanAnswerDisposition[] = ["AFFIRMATIVE", "NEGATIVE", "REFERRAL", "CONFIDENTIAL_NO_DISCLOSURE", "UNKNOWN_DONT_KNOW", "QUALIFIED_OR_CONDITIONAL", "OTHER"];

function scopeText(input: HumanVerificationPlanningInput) { return [input.tradeId, input.projectName, input.scope.geographicScope].filter(Boolean).join(" / ") || "the stated scope" }
function template(input: HumanVerificationPlanningInput): { objective: string; type: HumanVerificationQuestionType; primary: string; followUp: string | null; authority: HumanVerificationPacket["authorityRequired"]; effects: string[] } {
  const scope = scopeText(input), company = input.companyName ?? "the company", project = input.projectName ?? "the project";
  const authority = (minimumLevel: HumanVerificationPacket["authorityRequired"]["minimumLevel"], evidence: string[]) => ({ minimumLevel, evidenceToCapture: evidence, warning: "Job title alone does not establish canonical authority; capture the person's basis and exact scope." });
  switch (input.need) {
    case "EXTERNAL_MANPOWER_ACCEPTANCE_UNKNOWN": case "EXTERNAL_MANPOWER_ACCEPTANCE_CONFLICT": case "STALE_COMMERCIAL_EVIDENCE":
      return { objective: "Verify external supplemental manpower acceptance within bounded scope", type: "MANPOWER_ACCEPTANCE", primary: `When manpower demand exceeds your direct-hire workforce for ${scope}, does your team use outside staffing or supplemental craft-labor providers?`, followUp: "If so, is that labor purchased directly, through an MSP or approved vendor network, or only through full-scope subcontractors?", authority: authority("SUBJECT_MATTER_INFORMED", ["department and role", "how the person knows", "company/project scope", "effective period"]), effects: ["AF01 may later become VERIFIED_POSITIVE", "AF01 may later become VERIFIED_NEGATIVE"] };
    case "VENDOR_ROUTE_UNKNOWN":
      return { objective: "Verify the governed MSP or staffing-program route", type: "CONTACT_ROUTE", primary: `If supplemental craft labor is used for ${scope}, is it purchased directly or through an MSP, staffing program, or approved vendor network?`, followUp: "Which department manages that route?", authority: authority("PROCESS_PARTICIPANT", ["process participation", "department", "route scope"]), effects: ["A vendor or staffing route may later become supportable"] };
    case "MISSING_ACTIONABLE_CONTACT": case "BUYER_AUTHORITY_UNKNOWN": case "CONTACT_AUTHORITY_UNKNOWN":
      return { objective: "Verify the responsible commercial decision path and authority", type: input.need === "MISSING_ACTIONABLE_CONTACT" ? "CONTACT_ROUTE" : "CONTACT_AUTHORITY", primary: `Which department or person manages supplemental craft-labor vendors for ${scope}?`, followUp: "What role does that person or department have in the process?", authority: authority("ROUTING_ONLY", ["referral source", "department", "decision-path responsibility"]), effects: ["Contact route may become stronger", "Contact authority may later be established"] };
    case "PROJECT_COMPANY_LINK_UNVERIFIED":
      return { objective: "Verify contractor participation on a specific project", type: "RELATIONSHIP", primary: `Is ${company} currently performing ${scope} on ${project}?`, followUp: "What is the exact scope and current effective period?", authority: authority("SUBJECT_MATTER_INFORMED", ["project knowledge basis", "exact project scope", "effective period"]), effects: ["A project/company relationship claim may later become supportable", "M3 may later become derivable"] };
    case "WORKFORCE_PARTNER_RELATIONSHIP_UNVERIFIED": case "RELATIONSHIP_UNVERIFIED":
      return { objective: input.need === "WORKFORCE_PARTNER_RELATIONSHIP_UNVERIFIED" ? "Verify workforce partner or subvendor acceptance" : "Verify a bounded commercial relationship", type: "RELATIONSHIP", primary: `Do you work with smaller labor providers or subvendors to supplement your workforce for ${scope}?`, followUp: "Is that relationship project-specific, regional, or limited to a particular trade or mechanism?", authority: authority("SUBJECT_MATTER_INFORMED", ["relationship knowledge basis", "counterparty", "scope", "effective period"]), effects: ["A workforce-partner relationship claim may later become supportable", "M3 or M4 may later become derivable"] };
    case "QUALIFICATION_REQUIREMENT_UNKNOWN": case "QUALIFICATION_ROUTE_UNKNOWN":
      return { objective: "Verify qualification requirements or the responsible qualification route", type: "QUALIFICATION_REQUIREMENT", primary: `What requirements must a supplemental workforce or vendor provider satisfy before being considered for ${scope}?`, followUp: "Which department or system owns that qualification process?", authority: authority("PROCESS_PARTICIPANT", ["process ownership", "requirement source", "scope and currentness"]), effects: ["Qualification requirements may later become known; Fly satisfaction remains UNKNOWN"] };
    default:
      return { objective: "Obtain bounded human confirmation for a governed commercial fact", type: "CLAIM_CONFIRMATION", primary: `Can you confirm the current governed commercial fact for ${scope}?`, followUp: "What is the exact scope and effective period?", authority: authority("SUBJECT_MATTER_INFORMED", ["knowledge basis", "scope", "effective period"]), effects: ["A governed claim may later become supportable"] };
  }
}
function priority(input: HumanVerificationPlanningInput): HumanVerificationPriority { if (input.urgentTemporalWindow && input.nearHotEligibility) return "URGENT"; if (input.nearHotEligibility || (input.staleOrConflicting && input.commerciallyMaterial)) return "HIGH"; if (input.commerciallyMaterial && input.contact?.routeCurrent) return "NORMAL"; return "LOW" }
function target(input: HumanVerificationPlanningInput): { type: VerificationTargetType; id: string } | null { if (input.targetType && input.targetId) return { type: input.targetType, id: input.targetId }; if (!input.companyId) return null; if (af01Needs.has(input.need)) return { type: "MANPOWER_ACCEPTANCE", id: input.opportunityId ?? input.companyId }; if (["MISSING_ACTIONABLE_CONTACT", "VENDOR_ROUTE_UNKNOWN", "QUALIFICATION_ROUTE_UNKNOWN"].includes(input.need)) return { type: "COMPANY_RESOLUTION", id: input.companyId }; return { type: input.claimId ? "CLAIM" : "COMPANY_ROLE", id: input.claimId ?? input.companyId } }
function normalized(value: unknown): unknown { if (Array.isArray(value)) return value.map(normalized); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,normalized(item)])); return value }
function sameScope(input: HumanVerificationPlanningInput) { if (!input.currentAf01Scope) return false; const requested = { ...input.scope, projectId: input.scope.projectId ?? input.projectId ?? undefined, tradeId: input.scope.tradeId ?? input.tradeId ?? undefined, occupationId: input.scope.occupationId ?? input.occupationId ?? undefined }; return JSON.stringify(normalized(requested)) === JSON.stringify(normalized(input.currentAf01Scope)) }
function af01Resolved(input: HumanVerificationPlanningInput, now: Date) { if (!af01Needs.has(input.need) || input.need === "EXTERNAL_MANPOWER_ACCEPTANCE_CONFLICT") return false; if (!input.currentAf01Result || !sameScope(input)) return false; const result = normalizeManpowerAcceptanceResult(input.currentAf01Result); const current = !input.currentAf01ValidUntil || input.currentAf01ValidUntil > now; return current && (isVerifiedPositiveManpowerAcceptance(result) || result === "VERIFIED_NEGATIVE") }

export class HumanVerificationPlanningService {
  private readonly tasks: HumanVerificationService;
  constructor(private readonly repository: HumanVerificationRepository, private readonly clock: () => Date = () => new Date()) { this.tasks = new HumanVerificationService(repository) }
  async plan(input: HumanVerificationPlanningInput): Promise<HumanVerificationPlan> {
    const base = { verificationRequired: false, priority: priority(input), readinessToExecute: false, missingPrerequisites: [] as string[], blocker: input.blockerCode ?? input.need, targetType: null, targetId: null, packet: null, task: null, created: false };
    if (input.internalSoftwareDefect || !input.commerciallyMaterial) return { ...base, disposition: "NOT_HUMAN_VERIFICATION_PROBLEM" };
    if (input.prohibitedOutreach) return { ...base, disposition: "PROHIBITED_OUTREACH" };
    if (input.governedStateResolved || af01Resolved(input, this.clock())) return { ...base, disposition: "ALREADY_RESOLVED" };
    if (!input.publicEvidenceExhausted) return { ...base, disposition: "PUBLIC_RESEARCH_REQUIRED" };
    if (!input.companyId) return { ...base, disposition: "NEEDS_TARGET_RESOLUTION", missingPrerequisites: ["company identity"] };
    const selected = target(input); if (!selected) return { ...base, disposition: "NEEDS_TARGET_RESOLUTION", missingPrerequisites: ["governed target"] };
    const q = template(input), routeReady = Boolean(input.contact?.routeId && input.contact.routeCurrent !== false);
    const nextAction = routeReady ? (input.contact?.preferredMethod === "EMAIL" ? "EMAIL" : "CALL") : "FIND_BETTER_ROUTE";
    const packet: HumanVerificationPacket = { task: { id: null, status: "PLANNED", createdAt: null, dueAt: input.dueAt?.toISOString() ?? null, assignedOperatorId: input.assignedOperatorId ?? null, verificationObjective: q.objective }, target: { companyId: input.companyId, companyName: input.companyName ?? null, projectId: input.projectId ?? null, projectName: input.projectName ?? null, opportunityId: input.opportunityId ?? null, opportunityTitle: input.opportunityTitle ?? null, tradeId: input.tradeId ?? null, occupationId: input.occupationId ?? null, person: input.contact ?? null }, whyThisMatters: { blocker: input.blockerCode ?? input.need, commercialQuestion: q.objective, currentCanonicalState: input.currentAf01Result ?? "UNRESOLVED", publicEvidenceInsufficientReason: "Governed public/electronic evidence has been exhausted without resolving the required decision." }, question: { primary: q.primary, followUp: q.followUp }, expectedClassifications: { answerDispositions: dispositions, commercialMechanisms: mechanisms }, authorityRequired: q.authority, scopeToConfirm: { ...input.scope, projectId: input.scope.projectId ?? input.projectId ?? undefined, tradeId: input.scope.tradeId ?? input.tradeId ?? undefined, occupationId: input.scope.occupationId ?? input.occupationId ?? undefined }, possibleEffects: q.effects.map(x => `${x}; task creation itself does not change canonical truth`), sourceBasis: input.sourceBasis, conflicts: input.conflicts ?? [], doNotClaim: ["Do not claim external-manpower acceptance from a referral or ordinary subcontracting.", "Do not claim companywide policy from project-specific or unknown scope.", "Do not claim M4 because companies share an ecosystem.", "Do not claim supplier approval from a portal.", "Do not claim Fly satisfies a buyer qualification requirement; satisfaction remains UNKNOWN."], safetyPrivacy: ["No automatic outreach.", "Do not assume recording consent.", "Use business-purpose contact data only and avoid unnecessary PII.", "Preserve the exact response later; summaries must not replace it."], nextAction };
    if (!routeReady) return { ...base, verificationRequired: true, disposition: "NEEDS_CONTACT_ROUTE", targetType: selected.type, targetId: selected.id, packet, missingPrerequisites: ["current actionable contact route"] };
    const taskInput: CreateHumanVerificationTaskInput = { companyId: input.companyId, targetType: selected.type, targetId: selected.id, verificationObjective: q.objective, questionType: q.type, primaryQuestion: q.primary, followUpQuestion: q.followUp, createdBy: input.createdBy, ruleVersion: HUMAN_VERIFICATION_RULE_VERSION, opportunityId: input.opportunityId, projectId: input.projectId, claimId: input.claimId, blockerCode: input.blockerCode ?? input.need, contactPersonId: input.contact?.personId, contactRouteId: input.contact?.routeId, preferredMethod: input.contact?.preferredMethod, assignedOperatorId: input.assignedOperatorId, dueAt: input.dueAt, tradeId: input.tradeId, occupationId: input.occupationId, scope: packet.scopeToConfirm, packetSnapshot: packet as unknown as Record<string, unknown> };
    const result = await this.tasks.createTask(taskInput);
    const finalPacket = { ...packet, task: { ...packet.task, id: result.task.id, status: result.task.status, createdAt: result.task.createdAt.toISOString() } };
    if (!result.created) await this.repository.createTaskEvent({ verificationTaskId: result.task.id, eventType: "MATERIAL_CHANGE", oldState: result.task.status, newState: result.task.status, reason: "Equivalent planning request deduplicated against open task", operatorId: input.createdBy, occurredAt: this.clock(), evidenceIds: input.sourceBasis.map(x => x.evidenceId), claimIds: input.sourceBasis.flatMap(x => x.claimId ? [x.claimId] : []), metadata: { planningDisposition: "DUPLICATE_OPEN_TASK", ruleVersion: HUMAN_VERIFICATION_PLANNING_RULE_VERSION } });
    return { ...base, verificationRequired: true, disposition: result.created ? "READY" : "DUPLICATE_OPEN_TASK", readinessToExecute: true, targetType: selected.type, targetId: selected.id, packet: finalPacket, task: result.task, created: result.created };
  }
}
