import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import type { EconomicDecisionRecord } from "../../domain/economic-decision";
import { OpportunityEconomicDecisionSection } from "../../components/opportunity-detail/opportunity-economic-decision-section";
import { assembleOpportunityEconomicDecisionDetail } from "../../server/read-models/economic-decisions";

const opportunityId="11111111-1111-4111-8111-111111111111",otherOpportunityId="22222222-2222-4222-8222-222222222222";
function record(id:string,disposition:EconomicDecisionRecord["disposition"],supersedesDecisionId:string|null,rationale=`Rationale ${id}`,target=opportunityId):EconomicDecisionRecord{return{id,opportunityId:target,scenarioSnapshotId:`snapshot-${id}`,disposition,rationale,scenarioEffectiveCertainty:"OPERATOR_ASSUMPTION",scenarioBlockingReasons:[`Blocking reason ${id}`],ruleVersion:"economic-decision@1",decidedBy:`operator-${id}`,decidedAt:new Date(`2026-09-11T1${id.slice(-1)}:00:00Z`),supersedesDecisionId,createdAt:new Date(`2026-09-11T1${id.slice(-1)}:00:00Z`)}};
const render=(records:readonly EconomicDecisionRecord[])=>renderToStaticMarkup(<OpportunityEconomicDecisionSection locale="en-US" decisions={assembleOpportunityEconomicDecisionDetail(opportunityId,records)}/>);

describe("Phase 4M economic decision read-only presentation",()=>{
  it.each(["PROCEED","DECLINE","DEFER"] as const)("presents the human-selected %s disposition as non-interactive status",disposition=>{const html=render([record("d1",disposition,null)]);expect(html).toContain(`>${disposition}<`);expect(html).toContain("Human-authorized business disposition");expect(html).not.toContain("<button");});
  it("presents current rationale, operator, timestamp, certainty, snapshot, and blockers",()=>{const html=render([record("d1","PROCEED",null,"Authorized human rationale")]);expect(html).toContain("Current durable decision");expect(html).toContain("Authorized human rationale");expect(html).toContain("operator-d1");expect(html).toContain('dateTime="2026-09-11T11:00:00.000Z"');expect(html).toContain("Operator assumption");expect(html).toContain("snapshot-d1");expect(html).toContain("Blocking reason d1");});
  it("distinguishes no decision from unavailable capability with accessible status semantics",()=>{const empty=renderToStaticMarkup(<OpportunityEconomicDecisionSection locale="en-US" decisions={{opportunityId,current:null,history:[]}}/>),unavailable=renderToStaticMarkup(<OpportunityEconomicDecisionSection locale="en-US" decisions={null}/>);expect(empty).toContain('role="status"');expect(empty).toContain("No durable economic decision has been recorded");expect(unavailable).toContain('role="status"');expect(unavailable).toContain("information unavailable");expect(unavailable).toContain("does not mean that no decision exists");});
  it("shows D3 once as current and D1/D2 as historical in certified order",()=>{const d1=record("d1","PROCEED",null),d2=record("d2","DEFER","d1"),d3=record("d3","DECLINE","d2"),html=render([d3,d1,d2]),history=html.slice(html.indexOf("Decision history"));expect(html.match(/Current durable decision/g)).toHaveLength(1);expect(html.match(/Historical #/g)).toHaveLength(2);expect(history.indexOf("Rationale d1")).toBeLessThan(history.indexOf("Rationale d2"));expect(html).toContain("Rationale d3");expect(html).toContain('aria-labelledby="decision-history-title"');});
  it("preserves a long rationale without truncation and excludes foreign records through the certified projection",()=>{const rationale="Operational context ".repeat(80),foreign=record("x9","DECLINE",null,"FOREIGN SECRET",otherOpportunityId),html=render([foreign,record("d1","PROCEED",null,rationale)]);expect(html).toContain(rationale);expect(html).not.toContain("FOREIGN SECRET");});
  it("contains no decision write control, mutation hook, repository, or request path",async()=>{const path=resolve(process.cwd(),"src/components/opportunity-detail/opportunity-economic-decision-section.tsx"),source=(await readFile(path,"utf8")).toLowerCase(),html=render([record("d1","PROCEED",null)]).toLowerCase();expect(source).not.toMatch(/server action|repository|fetch\(|useeffect|useactionstate|\.create\(|\.save\(|post|patch|put|delete/);expect(html).not.toMatch(/<button|<form|<input|<select|<textarea/);});
  it("renders localized read-only semantics without changing durable vocabulary",()=>{const decisions=assembleOpportunityEconomicDecisionDetail(opportunityId,[record("d1","DEFER",null)]),html=renderToStaticMarkup(<OpportunityEconomicDecisionSection locale="es-US" decisions={decisions}/>);expect(html).toContain("Decisión duradera vigente");expect(html).toContain("POSPONER");expect(html).toContain("no es una recomendación del sistema");});
});
