import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { OpportunityDetailView } from "../../components/opportunity-detail/opportunity-detail-view";
import { assembleOpportunityIntelligenceDetail } from "../../server/read-models/opportunity-detail";
import { getOpportunityDetailPage, loadOpportunityDetail } from "../../server/opportunity-detail/get-opportunity-detail-page";

const id="11111111-1111-4111-8111-111111111111", now=new Date("2026-09-05T12:00:00Z");
function detail(overrides:Record<string,unknown>={}) { const graph={opportunity:{id,identityKey:"stable-01",projectId:"project-1",unresolvedCompanyContext:null,title:"Battery Plant Expansion",lifecycle:"ACTIVE",firstSeenAt:now,lastSeenAt:now,staleAfter:null,verificationDueAt:null,metadata:{}},demandSignals:[{id:"d-1",role_type:"ELECTRICIAN",headcount_estimate:null,per_diem_available:false,stale_after:null}],claims:[{id:"c-1",predicate:"workforce_demand",supporting_evidence_id:"e-1",verification_state:"VERIFIED",stale_after:null}],companies:[{id:"co-1",common_name:"Acme Energy"}],companyRoles:[{id:"r-1",role:"MANPOWER_BUYER",verification_state:"VERIFIED"}],project:{id:"project-1",name:"Battery Plant",location_text:"Austin, TX"},acceptance:{id:"a-1",result:"VERIFIED_NEGATIVE",reason:"Authorized buyer response",valid_until:null,qualifying_categories:[],supporting_evidence_ids:["e-1"]},vendorRoutes:[],contactPeople:[{id:"p-1",name:"Jordan Lee",title:"Procurement Manager",verification_state:"VERIFIED"}],contactRoutes:[{id:"route-1",route_type:"CORPORATE_EMAIL",target:"buyer@acme.example",verification_state:"VERIFIED",stale_after:null}],routeGrades:[{contact_route_id:"route-1",grade:"A"}],evidence:[{id:"e-1",source_url:"https://example.com/source",source_id:"source-1",capture_method:"HUMAN_INTERACTION",captured_at:now}],verificationReviews:[{id:"v-1",target_type:"MANPOWER_ACCEPTANCE",decision:"VERIFY",reason:"Authorized response reviewed",decided_at:now,evidence_ids:["e-1"]}],asOf:now,claimConflictCount:0,gaps:["MISSING_ACTIONABLE_ROUTE"],conflicts:[],...overrides}; return assembleOpportunityIntelligenceDetail(graph as Parameters<typeof assembleOpportunityIntelligenceDetail>[0],now); }
const ready=(d=detail())=>({state:"READY" as const,detail:d});
describe("UI-5 Opportunity Intelligence Detail",()=>{
  it("renders persisted relationships and evidence provenance",()=>{const html=renderToStaticMarkup(<OpportunityDetailView locale="en-US" result={ready()}/>);expect(html).toContain("Acme Energy");expect(html).toContain("Battery Plant");expect(html).toContain("Jordan Lee");expect(html).toContain("https://example.com/source");});
  it("renders verified negative only from the canonical result",()=>{const d=detail();expect(d.acceptance).toMatchObject({result:"VERIFIED_NEGATIVE",accepted:false,trust:"VERIFIED"});expect(renderToStaticMarkup(<OpportunityDetailView locale="en-US" result={ready(d)}/>)).toContain("Verified non-acceptance");});
  it("does not turn missing acceptance into a negative",()=>{const d=detail({acceptance:null});expect(d.acceptance).toBeNull();const html=renderToStaticMarkup(<OpportunityDetailView locale="en-US" result={ready(d)}/>);expect(html).toContain("Unknown / unavailable");expect(html).not.toContain("Verified non-acceptance");});
  it("preserves candidate routes as unverified",()=>{const d=detail({contactRoutes:[{id:"route-1",route_type:"CORPORATE_EMAIL",target:"candidate@example.com",verification_state:"UNVERIFIED"}]});expect(d.commercialRoute.routes[0].trust).toBe("UNVERIFIED");});
  it("keeps unknown values distinct from zero and false",()=>{const d=detail();expect(d.demand[0].headcount).toEqual({state:"UNKNOWN",value:null});expect(d.demand[0].perDiem).toEqual({state:"KNOWN",value:false});expect(renderToStaticMarkup(<OpportunityDetailView locale="en-US" result={ready(d)}/>)).not.toContain(">0<");});
  it("represents legitimate empty relationships without query failure",()=>{const d=detail({demandSignals:[],companyRoles:[],contactPeople:[],contactRoutes:[],vendorRoutes:[],evidence:[],verificationReviews:[]});const html=renderToStaticMarkup(<OpportunityDetailView locale="en-US" result={ready(d)}/>);expect(html).toContain("No demand relationships");expect(html).toContain("No linked evidence records");});
  it("distinguishes unavailable, not found, and query error",()=>{for(const [state,text] of [["UNAVAILABLE","not configured"],["NOT_FOUND","does not identify"],["ERROR","could not be read"]] as const)expect(renderToStaticMarkup(<OpportunityDetailView locale="en-US" result={{state,detail:null,reason:"fixture"}}/>)).toContain(text);});
  it("rejects malformed stable IDs as not found before database access",async()=>{expect(await loadOpportunityDetail("not-an-id")).toMatchObject({state:"NOT_FOUND"});});
  it("maps thrown loaders to query error",async()=>{expect(await getOpportunityDetailPage(id,async()=>{throw new Error("offline")})).toMatchObject({state:"ERROR"});});
  it("renders bilingual interface copy without translating proper nouns",()=>{const html=renderToStaticMarkup(<OpportunityDetailView locale="es-US" result={ready()}/>);expect(html).toContain("Demanda de fuerza laboral");expect(html).toContain("Evidencia y procedencia");expect(html).toContain("Acme Energy");});
  it("keeps UI-4 stable-ID routing",async()=>{const source=await readFile(resolve(process.cwd(),"src/components/opportunity-radar/opportunity-radar-view.tsx"),"utf8");expect(source).toContain("encodeURIComponent(item.opportunityId)");});
  it("keeps React free of database and governed-state calculation",async()=>{const source=(await readFile(resolve(process.cwd(),"src/components/opportunity-detail/opportunity-detail-view.tsx"),"utf8")).toLowerCase();expect(source).not.toMatch(/supabase|database_url|select |insert |update |delete |calculate|fetch\(|useeffect/);expect(source).not.toMatch(/hot_|af01|eligib/);});
  it("uses a read-only detail loader with no canonical writes",async()=>{const source=(await readFile(resolve(process.cwd(),"src/server/opportunity-detail/get-opportunity-detail-page.ts"),"utf8")).toLowerCase();expect(source).toContain("loadgraph");expect(source).toContain("listcompleteness");expect(source).not.toMatch(/\.save|\.create|\.link|insert |update |delete /);});
  it("provides mobile detail breakpoints and overflow-safe content",async()=>{const css=await readFile(resolve(process.cwd(),"src/app/globals.css"),"utf8");expect(css).toContain(".detail-layout{grid-template-columns:1fr}");expect(css).toContain("overflow-wrap:anywhere");});
});
