import type{ConversionEvidenceInput}from"../../../domain/commercial-conversion";
import{previewConversionDecision}from"../commercial-conversion/commercial-conversion-service";
import{COMMERCIAL_EVIDENCE_ACQUISITION_RULE_VERSION}from"../../../domain/commercial-evidence-acquisition";
import type{AcquisitionTaskType,AcquisitionVerificationItem,CandidateCommercialEvidence,CommercialEvidenceAcquisitionPlan,CommercialEvidenceDimension,CommercialEvidenceGap,EvidenceSourceType,EvidenceTier}from"../../../domain/commercial-evidence-acquisition";

const unique=<T>(xs:T[])=>[...new Set(xs)];
const opportunity=(x:ConversionEvidenceInput)=>`conversion:${x.signal.externalId}`;
const definitions:Record<CommercialEvidenceGap,{task:AcquisitionTaskType;dimension:CommercialEvidenceDimension;priority:"HIGH"|"MEDIUM"|"LOW";tier:EvidenceTier;sources:EvidenceSourceType[];why:string}>={
  MISSING_BUYER:{task:"FIND_BUYER_FUNCTION",dimension:"BUYER",priority:"HIGH",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_PROCUREMENT","OFFICIAL_CORPORATE_CONTACT","OFFICIAL_BID_DOCUMENT"],why:"No supported external-manpower commercial counterpart is recorded; employer identity is insufficient."},
  MISSING_BUYER_FUNCTION:{task:"FIND_BUYER_FUNCTION",dimension:"BUYER",priority:"HIGH",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_PROCUREMENT","OFFICIAL_CORPORATE_CONTACT"],why:"No procurement, sourcing, subcontracting, or workforce-buying function is supported."},
  MISSING_AF01:{task:"FIND_EXTERNAL_MANPOWER_POLICY",dimension:"AF01",priority:"HIGH",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CONTINGENT_WORKFORCE","OFFICIAL_SUBCONTRACTOR_ONBOARDING","OFFICIAL_SUPPLIER_VENDOR"],why:"No VERIFIED accepted external-manpower category exists; a supplier portal alone is insufficient."},
  MISSING_ACTIONABLE_CONTACT:{task:"FIND_COMMERCIAL_CONTACT",dimension:"CONTACT",priority:"HIGH",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CORPORATE_CONTACT","OFFICIAL_PROCUREMENT"],why:"No verified actionable commercial route exists."},
  MISSING_CONTACT_AUTHORITY:{task:"FIND_COMMERCIAL_CONTACT",dimension:"CONTACT",priority:"HIGH",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CORPORATE_CONTACT","PROFESSIONAL_CORPORATE_PAGE"],why:"A route exists but its commercial authority is not VERIFIED."},
  MISSING_TEMPORAL_STATUS:{task:"VERIFY_TEMPORAL_STATUS",dimension:"TEMPORAL",priority:"HIGH",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CAREER_POSTING","OFFICIAL_BID_DOCUMENT","OFFICIAL_PROJECT"],why:"No explicit current status or governing deadline supports OPEN."},
  MISSING_PROJECT:{task:"FIND_PROJECT_CONTEXT",dimension:"PROJECT",priority:"MEDIUM",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_PROJECT","OFFICIAL_BID_DOCUMENT","GOVERNMENT_PUBLIC_RECORD"],why:"No distinct project identity is supported."},
  MISSING_PROJECT_RELATIONSHIP:{task:"FIND_PROJECT_CONTEXT",dimension:"PROJECT",priority:"MEDIUM",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_PROJECT","OFFICIAL_BID_DOCUMENT"],why:"No supported relationship connects the organization to a project."},
  MISSING_HEADCOUNT:{task:"FIND_HEADCOUNT",dimension:"HEADCOUNT",priority:"MEDIUM",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CAREER_POSTING","UNION_DISPATCH"],why:"No explicit worker count is recorded."},
  MISSING_SCHEDULE:{task:"FIND_SCHEDULE",dimension:"SCHEDULE",priority:"MEDIUM",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CAREER_POSTING","UNION_DISPATCH"],why:"No explicit schedule is recorded."},
  MISSING_DURATION:{task:"FIND_DURATION",dimension:"DURATION",priority:"MEDIUM",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CAREER_POSTING","OFFICIAL_PROJECT"],why:"No explicit assignment or project duration is recorded."},
  MISSING_ECONOMICS:{task:"FIND_ECONOMICS",dimension:"ECONOMICS",priority:"LOW",tier:"TIER_1_PRIMARY_AUTHORITATIVE",sources:["OFFICIAL_CAREER_POSTING","UNION_DISPATCH"],why:"No explicit wage, per-diem, or incentive evidence is recorded."},
};
const order={HIGH:0,MEDIUM:1,LOW:2};
export function commercialEvidenceGaps(x:ConversionEvidenceInput):CommercialEvidenceGap[]{const gaps:CommercialEvidenceGap[]=[];if(!x.buyer)gaps.push("MISSING_BUYER","MISSING_BUYER_FUNCTION");if(!x.acceptance||x.acceptance.verificationState!=="VERIFIED")gaps.push("MISSING_AF01");const verified=x.contacts.filter(c=>c.verificationState==="VERIFIED");if(!verified.length)gaps.push("MISSING_ACTIONABLE_CONTACT");if(x.contacts.length&&!verified.length)gaps.push("MISSING_CONTACT_AUTHORITY");if(x.actionability.explicitStatus===null&&!x.actionability.deadlines.length)gaps.push("MISSING_TEMPORAL_STATUS");if(!x.project)gaps.push("MISSING_PROJECT","MISSING_PROJECT_RELATIONSHIP");if(x.headcount===null)gaps.push("MISSING_HEADCOUNT");if(!x.schedule)gaps.push("MISSING_SCHEDULE");gaps.push("MISSING_DURATION");if(!x.wage&&!x.perDiemOrIncentive)gaps.push("MISSING_ECONOMICS");return unique(gaps)}
export function planCommercialEvidenceAcquisition(x:ConversionEvidenceInput):CommercialEvidenceAcquisitionPlan{const opportunityId=opportunity(x),gaps=commercialEvidenceGaps(x),tasks=gaps.map(g=>{const d=definitions[g];return{id:`acquisition:${x.signal.externalId}:${d.task}:${d.dimension}`,taskType:d.task,opportunityId,signalId:x.signal.signalId,dimension:d.dimension,currentState:"UNKNOWN_OR_UNVERIFIED",whyNeeded:d.why,preferredEvidenceTier:d.tier,preferredSourceTypes:d.sources,priority:d.priority,blockingImpact:d.priority==="HIGH"?["ELIGIBILITY_OR_ACTIVE_HOT"]:["COMMERCIAL_INTERPRETATION"],verificationRequired:true as const,provenanceRequired:true as const,ruleVersion:COMMERCIAL_EVIDENCE_ACQUISITION_RULE_VERSION}}).filter((t,i,a)=>a.findIndex(y=>y.id===t.id)===i).sort((a,b)=>order[a.priority]-order[b.priority]||a.id.localeCompare(b.id));return{opportunityId,signalId:x.signal.signalId,gaps,tasks,candidateEvidence:[],verificationItems:[],ruleVersion:COMMERCIAL_EVIDENCE_ACQUISITION_RULE_VERSION}}
const verificationKind=(e:CandidateCommercialEvidence):AcquisitionVerificationItem["kind"]=>e.claimType==="BUYER_ORGANIZATION"?"VERIFY_BUYER":e.claimType==="BUYER_FUNCTION"?"VERIFY_BUYER_FUNCTION":e.claimType==="EXTERNAL_MANPOWER_ACCEPTANCE"?"VERIFY_AF01":e.claimType==="COMMERCIAL_CONTACT"?"VERIFY_CONTACT_ROUTE":e.claimType==="CONTACT_AUTHORITY"?"VERIFY_CONTACT_GRADE":e.claimType==="TEMPORAL_STATUS"?"VERIFY_TEMPORAL_STATUS":"VERIFY_PROJECT_RELATIONSHIP";
export function addCandidateCommercialEvidence(plan:CommercialEvidenceAcquisitionPlan,incoming:readonly CandidateCommercialEvidence[]):CommercialEvidenceAcquisitionPlan{const candidates=[...plan.candidateEvidence];for(const raw of incoming){if(candidates.some(x=>x.id===raw.id))continue;candidates.push({...raw,verificationState:"UNVERIFIED"})}candidates.sort((a,b)=>a.id.localeCompare(b.id));const verificationItems=candidates.map((e):AcquisitionVerificationItem=>({id:`verification:${e.id}`,opportunityId:plan.opportunityId,kind:verificationKind(e),candidateFact:e.candidateClaim,supportingEvidenceIds:[e.id],conflictingEvidence:[...e.conflicts],currentProductionFact:"UNKNOWN_OR_UNVERIFIED",decisionRequired:`Human must VERIFY, REJECT, NEEDS_MORE_EVIDENCE, or DEFER ${e.claimType}.`,impactIfVerified:"Re-run the real decision preview; effect depends on remaining gates.",impactIfRejected:"Candidate remains unavailable to production decision engines.",remainingBlockers:plan.gaps,recommendedHumanAction:"Review the cited public source, provenance, applicability, authority, freshness, and conflicts.",decision:null}));return{...plan,candidateEvidence:candidates,verificationItems}}
export function previewCandidateImpact(x:ConversionEvidenceInput,evidence:CandidateCommercialEvidence){const decision=evidence.claimType==="EXTERNAL_MANPOWER_ACCEPTANCE"?{verifyAcceptance:true}:evidence.claimType==="COMMERCIAL_CONTACT"||evidence.claimType==="CONTACT_AUTHORITY"?{verifyContactIds:x.contacts.map(c=>c.id)}:evidence.claimType==="TEMPORAL_STATUS"&&/\bOPEN\b/i.test(evidence.candidateClaim)?{explicitStatus:"OPEN"as const}:{};return previewConversionDecision(x,decision)}
