begin;
create type production_source_readiness as enum('DISCOVERED','UNDER_REVIEW','APPROVED_FOR_FIXTURE','APPROVED_FOR_LIVE_CAPTURE','PAUSED','BLOCKED','RETIRED');create type production_source_health as enum('HEALTHY','DEGRADED','FAILING','BLOCKED','STALE','PAUSED');
create table production_source_profiles(source_id uuid primary key references sources(id),schema_version text not null,source_family text not null,source_tier text not null,capabilities text[] not null default '{}',capture_methods text[] not null default '{}',readiness production_source_readiness not null default 'DISCOVERED',schedule jsonb not null,rate_limit jsonb,identity_version text not null,profile_metadata jsonb not null default '{}',updated_at timestamptz not null default now());
create table production_source_executions(id uuid primary key,source_id uuid not null references sources(id),adapter_id text not null,adapter_version text not null,policy_decision_id uuid references source_capture_policy_decisions(id),started_at timestamptz not null,ended_at timestamptz,result text not null check(result in('SUCCESS','EMPTY_SUCCESS','FAILURE')),failure jsonb,evidence_ids uuid[] not null default '{}',parser_id text not null,parser_version text not null,correlation_metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table source_observation_identities(id uuid primary key default gen_random_uuid(),source_id uuid not null references sources(id),observation_identity text not null,external_identifiers jsonb not null default '{}',captured_identifier text not null,content_hash text not null,observed_at timestamptz not null,created_at timestamptz not null default now(),unique(source_id,observation_identity));
create table source_contribution_events(id uuid primary key default gen_random_uuid(),source_id uuid not null references sources(id),execution_id uuid references production_source_executions(id),event_type text not null,subject_type text not null,subject_id text not null,occurred_at timestamptz not null,event_metadata jsonb not null default '{}',created_at timestamptz not null default now());
create trigger production_source_executions_append_only before update or delete on production_source_executions for each row execute function prevent_source_audit_mutation();create trigger source_observation_identities_append_only before update or delete on source_observation_identities for each row execute function prevent_source_audit_mutation();create trigger source_contribution_events_append_only before update or delete on source_contribution_events for each row execute function prevent_source_audit_mutation();
create index production_source_execution_time_idx on production_source_executions(source_id,started_at desc);create index source_contribution_funnel_idx on source_contribution_events(source_id,event_type,occurred_at desc);create index source_observation_external_ids_idx on source_observation_identities using gin(external_identifiers);
commit;
