import type { EconomicDecisionView, OpportunityEconomicDecisionDetail } from "../../server/read-models/economic-decisions";
import type { Locale } from "../../i18n/locale";
import { formatDate } from "../../i18n/format";
import { t } from "../../i18n/translate";
import { EconomicFactTierBadge } from "../ui/status-primitives";

const formatDateTime = (locale: Locale, value: Date) => formatDate(locale, value, { dateStyle: "medium", timeStyle: "short" });
function DecisionFacts({ locale, decision }: { locale: Locale; decision: EconomicDecisionView }) { return <dl className="decision-facts"><div><dt>{t(locale,"economicDecision.operator")}</dt><dd>{decision.decidedByOperatorId}</dd></div><div><dt>{t(locale,"economicDecision.decidedAt")}</dt><dd><time dateTime={decision.decidedAt.toISOString()}>{formatDateTime(locale,decision.decidedAt)}</time></dd></div><div><dt>{t(locale,"economicDecision.certainty")}</dt><dd><EconomicFactTierBadge tier={decision.scenarioEffectiveCertainty} locale={locale}/></dd></div><div><dt>{t(locale,"economicDecision.snapshot")}</dt><dd><code>{decision.scenarioSnapshotId}</code></dd></div></dl>; }
function BlockingReasons({ locale, reasons }: { locale: Locale; reasons: readonly string[] }) { return reasons.length ? <div className="decision-blockers"><h4>{t(locale,"economicDecision.blockingReasons")}</h4><ul>{reasons.map((reason,index)=><li key={`${index}-${reason}`}>{reason}</li>)}</ul></div> : null; }
function Disposition({ locale, decision, current }: { locale: Locale; decision: EconomicDecisionView; current: boolean }) { const label=t(locale,`economicDecision.disposition.${decision.disposition}`); return <span className={`decision-disposition decision-${decision.disposition.toLowerCase()}`} aria-label={`${current?t(locale,"economicDecision.current"):t(locale,"economicDecision.historical")}: ${label}`}>{label}</span>; }

export function OpportunityEconomicDecisionSection({ locale, decisions }: { locale: Locale; decisions: OpportunityEconomicDecisionDetail | null }) {
  if(decisions===null)return <div className="decision-state decision-unavailable" role="status"><strong>{t(locale,"economicDecision.unavailableTitle")}</strong><p>{t(locale,"economicDecision.unavailableDescription")}</p></div>;
  if(decisions.current===null)return <div className="decision-state" role="status"><strong>{t(locale,"economicDecision.emptyTitle")}</strong><p>{t(locale,"economicDecision.emptyDescription")}</p></div>;
  const current=decisions.current,historical=decisions.history.filter(decision=>!decision.isCurrent);
  return <div className="decision-section"><p className="decision-boundary">{t(locale,"economicDecision.humanBoundary")}</p><article className="decision-current" aria-labelledby={`decision-current-${current.decisionId}`}><header><div><span>{t(locale,"economicDecision.current")}</span><h3 id={`decision-current-${current.decisionId}`}>{t(locale,"economicDecision.currentTitle")}</h3></div><Disposition locale={locale} decision={current} current/></header><blockquote>{current.rationale}</blockquote><DecisionFacts locale={locale} decision={current}/><BlockingReasons locale={locale} reasons={current.scenarioBlockingReasons}/></article>
    {historical.length>0&&<section className="decision-history" aria-labelledby="decision-history-title"><header><h3 id="decision-history-title">{t(locale,"economicDecision.historyTitle")}</h3><span>{historical.length}</span></header><ol>{historical.map(decision=><li key={decision.decisionId}><article aria-label={`${t(locale,"economicDecision.historical")} ${decision.lineagePosition}`}><header><span>{t(locale,"economicDecision.historical")} #{decision.lineagePosition}</span><Disposition locale={locale} decision={decision} current={false}/></header><p className="decision-rationale">{decision.rationale}</p><DecisionFacts locale={locale} decision={decision}/><BlockingReasons locale={locale} reasons={decision.scenarioBlockingReasons}/><p className="decision-lineage">{t(locale,"economicDecision.supersededBy")} <code>{decisions.history[decision.lineagePosition]?.decisionId}</code></p></article></li>)}</ol></section>}
  </div>;
}
