import Link from "next/link";
import type { ReactNode } from "react";
import type { Locale } from "../../i18n/locale";
import { formatDate } from "../../i18n/format";
import { t } from "../../i18n/translate";
import type { OpportunityIntelligenceDetail, DetailField } from "../../server/read-models/opportunity-detail";
import type { OpportunityDetailPageResult } from "../../server/opportunity-detail/get-opportunity-detail-page";
import { CurrentnessBadge, TrustState } from "../ui/status-primitives";
import { ErrorState } from "../ui/foundation";

const formatDateTime = (value: string, locale: Locale) => formatDate(locale, new Date(value), { dateStyle: "medium", timeStyle: "short" });

export function OpportunityDetailView({ locale, result }: { readonly locale: Locale; readonly result: OpportunityDetailPageResult }) {
  if (result.state !== "READY") return <StateView locale={locale} state={result.state} />;
  const d = result.detail, unknown = t(locale, "opportunityDetail.unknown");
  return <div className="page-stack opportunity-detail-view">
    <Link className="detail-back" href="/opportunities">← {t(locale, "opportunityDetail.back")}</Link>
    <header className="detail-hero"><div className="detail-hero-main"><p className="overline">{t(locale, "opportunityDetail.eyebrow")}</p><h1>{d.title ?? d.project ?? unknown}</h1><p>{t(locale, "opportunityDetail.description")}</p><div className="detail-reference"><span>{t(locale, "opportunityDetail.reference")}</span><code>{d.opportunityId}</code></div></div><div className="detail-status-stack"><span className="detail-readonly">{t(locale, "opportunityDetail.readOnly")}</span><CurrentnessBadge state={d.currentness} locale={locale}/><span>{d.lifecycle}</span></div></header>
    <section className="detail-fact-band" aria-label={t(locale,"opportunityDetail.eyebrow")}><Fact label={t(locale,"opportunityDetail.label.company")} value={d.company ?? unknown}/><Fact label={t(locale,"opportunityDetail.label.project")} value={d.project ?? unknown}/><Fact label={t(locale,"opportunityDetail.label.location")} value={d.location ?? unknown}/><Fact label={t(locale,"opportunityDetail.asOf")} value={formatDateTime(d.asOf, locale)}/></section>
    <div className="detail-layout"><main className="detail-main"><Section title={t(locale,"opportunityDetail.section.demand")} index="01">{d.demand.length ? d.demand.map((demand, i)=><div className="demand-record" key={demand.id}><div className="record-kicker">#{String(i+1).padStart(2,"0")} · {demand.id}</div><div className="detail-grid"><Field locale={locale} label="trade" field={demand.trade}/><Field locale={locale} label="occupation" field={demand.occupation}/><Field locale={locale} label="specialty" field={demand.specialty}/><Field locale={locale} label="headcount" field={demand.headcount}/><Field locale={locale} label="hours" field={demand.hoursPerWeek}/><Field locale={locale} label="duration" field={demand.duration}/><Field locale={locale} label="start" field={demand.startTiming}/><Field locale={locale} label="perDiem" field={demand.perDiem}/><Fact label={t(locale,"opportunityDetail.label.demandStatus")} value={demand.status}/></div></div>) : <HonestEmpty>{t(locale,"opportunityDetail.empty.demand")}</HonestEmpty>}</Section>
      <Section title={t(locale,"opportunityDetail.section.route")} index="02"><CommercialRoute locale={locale} detail={d}/></Section>
      <Section title={t(locale,"opportunityDetail.section.evidence")} index="03">{d.evidence.length ? <ol className="evidence-timeline">{d.evidence.map(item=><li key={item.id}><span className="timeline-node"/><div className="evidence-head"><strong>{item.type ?? t(locale,"opportunityDetail.unknown")}</strong><div><TrustState state={item.trust} locale={locale}/><CurrentnessBadge state={item.currentness} locale={locale}/></div></div><dl><Meta label={t(locale,"opportunityDetail.label.source")} value={item.sourceUrl ? <a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceUrl}</a> : item.source}/><Meta label={t(locale,"opportunityDetail.label.captured")} value={item.capturedAt ? formatDateTime(item.capturedAt,locale) : unknown}/><Meta label={t(locale,"opportunityDetail.label.published")} value={item.publishedAt ? formatDateTime(item.publishedAt,locale) : unknown}/><Meta label={t(locale,"opportunityDetail.label.claim")} value={item.claim ?? unknown}/><Meta label={t(locale,"opportunityDetail.label.provenance")} value={item.id}/></dl></li>)}</ol> : <HonestEmpty>{t(locale,"opportunityDetail.empty.evidence")}</HonestEmpty>}</Section></main>
      <aside className="detail-rail"><RailSection title={t(locale,"opportunityDetail.section.acceptance")}><Acceptance locale={locale} detail={d}/></RailSection><RailSection title={t(locale,"opportunityDetail.section.verification")}><Verification locale={locale} detail={d}/></RailSection><RailSection title={t(locale,"opportunityDetail.section.gaps")}><Gaps locale={locale} detail={d}/></RailSection></aside></div>
  </div>;
}
function StateView({locale,state}:{locale:Locale;state:"NOT_FOUND"|"UNAVAILABLE"|"ERROR"}) { const base=state==="NOT_FOUND"?"notFound":state==="UNAVAILABLE"?"unavailable":"error"; return <div className="page-stack detail-state"><Link className="detail-back" href="/opportunities">← {t(locale,"opportunityDetail.back")}</Link><ErrorState locale={locale} title={t(locale,`opportunityDetail.state.${base}Title`)} description={t(locale,`opportunityDetail.state.${base}Description`)}/></div>; }
function Section({title,index,children}:{title:string;index:string;children:ReactNode}) { return <section className="detail-section"><header><span>{index}</span><h2>{title}</h2></header>{children}</section>; }
function RailSection({title,children}:{title:string;children:ReactNode}) { return <section className="detail-rail-section"><h2>{title}</h2>{children}</section>; }
function Fact({label,value}:{label:string;value:ReactNode}) { return <div className="detail-fact"><span>{label}</span><strong>{value}</strong></div>; }
function Field({locale,label,field}:{locale:Locale;label:"trade"|"occupation"|"specialty"|"headcount"|"hours"|"duration"|"start"|"perDiem";field:DetailField}) { let value:ReactNode=field.value as ReactNode; if(field.state==="UNKNOWN")value=t(locale,"opportunityDetail.unknown"); else if(label==="perDiem"&&field.value===false)value=t(locale,"opportunityDetail.unknown"); return <Fact label={t(locale,`opportunityDetail.label.${label}`)} value={value}/>; }
function Meta({label,value}:{label:string;value:ReactNode}) { return <><dt>{label}</dt><dd>{value}</dd></>; }
function HonestEmpty({children}:{children:ReactNode}) { return <p className="detail-honest-empty">{children}</p>; }
function CommercialRoute({locale,detail:d}:{locale:Locale;detail:OpportunityIntelligenceDetail}) { const u=t(locale,"opportunityDetail.unknown"); if(d.commercialRoute.capability==="UNAVAILABLE")return <HonestEmpty>{t(locale,"opportunityDetail.empty.route")}</HonestEmpty>; return <div className="route-stack">{d.commercialRoute.buyerOrganizations.map((buyer,i)=><div className="route-record" key={`buyer-${i}`}><Fact label={t(locale,"opportunityDetail.label.buyer")} value={buyer.name??u}/><Fact label={t(locale,"opportunityDetail.label.role")} value={buyer.role??u}/><TrustState state={buyer.trust} locale={locale}/></div>)}{d.commercialRoute.people.map(person=><div className="route-record" key={person.id}><Fact label={t(locale,"opportunityDetail.label.contact")} value={person.name||u}/><Fact label={t(locale,"opportunityDetail.label.authority")} value={[person.title,person.function].filter(Boolean).join(" · ")||u}/><TrustState state={person.trust} locale={locale}/></div>)}{d.commercialRoute.routes.map(route=><div className="route-record" key={route.id}><Fact label={t(locale,"opportunityDetail.label.route")} value={`${route.type} · ${route.target||u}`}/><Fact label={t(locale,"opportunityDetail.label.grade")} value={route.grade??u}/><div className="route-badges"><TrustState state={route.trust} locale={locale}/><CurrentnessBadge state={route.currentness} locale={locale}/></div></div>)}{d.commercialRoute.vendorRoutes.map(route=><div className="route-record" key={route.id}><Fact label={t(locale,"opportunityDetail.label.vendorRoute")} value={`${route.type} · ${route.target??u}`}/><CurrentnessBadge state={route.currentness} locale={locale}/></div>)}</div>; }
function Acceptance({locale,detail:d}:{locale:Locale;detail:OpportunityIntelligenceDetail}) { if(!d.acceptance)return <HonestEmpty>{t(locale,"opportunityDetail.acceptance.unknown")}</HonestEmpty>; const label=d.acceptance.accepted===true?"positive":d.acceptance.accepted===false?"negative":d.acceptance.trust==="CANDIDATE"?"candidate":"unknown"; return <div className={`acceptance-block acceptance-${label}`}><strong>{t(locale,`opportunityDetail.acceptance.${label}`)}</strong><TrustState state={d.acceptance.trust} locale={locale}/><CurrentnessBadge state={d.acceptance.currentness} locale={locale}/><Fact label={t(locale,"opportunityDetail.label.result")} value={d.acceptance.result}/><Fact label={t(locale,"opportunityDetail.label.reason")} value={d.acceptance.reason??t(locale,"opportunityDetail.unknown")}/></div>; }
function Verification({locale,detail:d}:{locale:Locale;detail:OpportunityIntelligenceDetail}) { return d.humanVerification.decisions.length?<ul className="verification-list">{d.humanVerification.decisions.map(x=><li key={x.id}><strong>{x.decision}</strong><span>{x.targetType}</span><p>{x.reason}</p><time>{formatDateTime(x.decidedAt,locale)}</time></li>)}</ul>:<HonestEmpty>{t(locale,"opportunityDetail.empty.verification")}</HonestEmpty>; }
function Gaps({locale,detail:d}:{locale:Locale;detail:OpportunityIntelligenceDetail}) { if(!d.gaps.length&&!d.conflicts.length)return <HonestEmpty>{t(locale,"opportunityDetail.empty.gaps")}</HonestEmpty>; return <ul className="gap-list">{d.gaps.map(g=><li key={g}>{t(locale,`opportunityDetail.gap.${g}`)}</li>)}{d.conflicts.map((c,i)=><li className="gap-conflict" key={i}>{c}</li>)}</ul>; }
