import type{HumanVerificationDecision,RecordVerificationInput,ReviewCandidate,VerificationDecisionRecord,VerificationState,VerificationTargetType}from"../../../domain/verification";import type{SqlClient}from"../evidence/postgres-evidence-repository";import type{VerificationRepository,VerificationTarget}from"./verification-repository";
type R={id:string;target_type:VerificationTargetType;target_id:string;decision:HumanVerificationDecision;reviewer_id:string;reason:string;decided_at:string|Date;previous_state:VerificationState|null;resulting_state:VerificationState|null;supersedes_decision_id:string|null;rule_version:string;metadata:Record<string,unknown>;created_at:string|Date;evidence_ids:string[]};const map=(r:R):VerificationDecisionRecord=>({id:r.id,targetType:r.target_type,targetId:r.target_id,decision:r.decision,reviewerId:r.reviewer_id,reason:r.reason,decidedAt:new Date(r.decided_at),previousState:r.previous_state,resultingState:r.resulting_state,supersedesDecisionId:r.supersedes_decision_id,ruleVersion:r.rule_version,metadata:r.metadata,evidenceIds:r.evidence_ids??[],createdAt:new Date(r.created_at)});const pg=(v:string[])=>`{${v.map(x=>`"${x}"`).join(",")}}`;
const targets:Record<VerificationTargetType,{table:string;state?:string;stale?:string;due?:string}>={CLAIM:{table:"claims",state:"verification_state",stale:"stale_after",due:"verification_due_at"},COMPANY_RESOLUTION:{table:"company_resolution_audits"},COMPANY_ROLE:{table:"company_roles",state:"verification_state"},PROJECT:{table:"projects"},MANPOWER_ACCEPTANCE:{table:"manpower_acceptance_evaluations",stale:"valid_until"},CONTACT_PERSON:{table:"contact_people",state:"verification_state",stale:"stale_after",due:"verification_due_at"},CONTACT_ROUTE:{table:"contact_routes",state:"verification_state",stale:"stale_after",due:"verification_due_at"},CONTACT_ROUTE_GRADE:{table:"contact_route_grade_evaluations"},OPPORTUNITY_CONFLICT:{table:"opportunities",due:"verification_due_at"}};
const support:Record<VerificationTargetType,string>={CLAIM:"select supporting_evidence_id id from claims where id=$1 union select evidence_id from evidence_links where claim_id=$1",COMPANY_RESOLUTION:"select evidence_id id from company_resolution_audits where id=$1",COMPANY_ROLE:"select raw_evidence_id id from company_roles where id=$1 union select evidence_id from evidence_links where company_role_id=$1",PROJECT:"select evidence_id id from evidence_links where project_id=$1",MANPOWER_ACCEPTANCE:"select unnest(supporting_evidence_ids)id from manpower_acceptance_evaluations where id=$1",CONTACT_PERSON:"select evidence_id id from contact_people where id=$1 union select evidence_id from evidence_links where contact_person_id=$1",CONTACT_ROUTE:"select evidence_id id from contact_routes where id=$1 union select evidence_id from evidence_links where contact_route_id=$1",CONTACT_ROUTE_GRADE:"select r.evidence_id id from contact_route_grade_evaluations g join contact_routes r on r.id=g.contact_route_id where g.id=$1 union select e.evidence_id from contact_route_grade_evaluations g join evidence_links e on e.contact_route_id=g.contact_route_id where g.id=$1",OPPORTUNITY_CONFLICT:"select evidence_id id from opportunity_evidence where opportunity_id=$1 union select c.supporting_evidence_id from opportunity_claims x join claims c on c.id=x.claim_id where x.opportunity_id=$1"};
export class PostgresVerificationRepository implements VerificationRepository{constructor(private readonly c:SqlClient){}
async loadTarget(type:VerificationTargetType,id:string,asOf:Date):Promise<VerificationTarget>{const x=targets[type],state=x.state?x.state+"::text":"null::text",stale=x.stale?x.stale:"null::timestamptz",due=x.due?x.due:"null::timestamptz";const q=await this.c.query<{state:VerificationState|null;stale_at:string|Date|null;due_at:string|Date|null}>(`select ${state} state,${stale} stale_at,${due} due_at from ${x.table} where id=$1`,[id]);const r=q.rows[0];return{exists:!!r,state:r?.state??null,stale:!!r?.stale_at&&new Date(r.stale_at)<=asOf,verificationDueAt:r?.due_at?new Date(r.due_at):null}}
async evidenceSupports(type:VerificationTargetType,id:string,evidenceIds:string[]){if(!evidenceIds.length)return false;const q=await this.c.query<{count:string}>(`select count(distinct id)::text count from(${support[type]})s where id=any($2::uuid[])`,[id,pg(evidenceIds)]);return Number(q.rows[0].count)===evidenceIds.length}
async record(i:RecordVerificationInput,previous:VerificationState|null,resulting:VerificationState|null){await this.c.query("begin");try{const primary=i.decision==="VERIFY"?i.evidenceIds[0]??null:null;const q=await this.c.query<R>("insert into human_verification_decisions(target_type,target_id,decision,reviewer_id,reason,decided_at,previous_state,resulting_state,primary_evidence_id,supersedes_decision_id,rule_version,metadata)values($1,$2,$3,$4,$5,$6,$7::verification_state,$8::verification_state,$9,$10,$11,$12::jsonb)returning *,array[]::uuid[] evidence_ids",[i.targetType,i.targetId,i.decision,i.reviewerId,i.reason,i.decidedAt.toISOString(),previous,resulting,primary,i.supersedesDecisionId??null,i.ruleVersion,JSON.stringify(i.metadata??{})]);for(const e of i.evidenceIds)await this.c.query("insert into human_verification_decision_evidence(decision_id,evidence_id)values($1,$2)",[q.rows[0].id,e]);if((i.decision==="VERIFY"||i.decision==="REJECT")&&targets[i.targetType].state){const contact=i.targetType==="CONTACT_PERSON"||i.targetType==="CONTACT_ROUTE",extra=i.targetType==="CLAIM"?",verified_at=case when $2::verification_state='VERIFIED' then $3 else verified_at end,verification_actor_reference=$4":i.targetType==="CONTACT_PERSON"?",verified_at=case when $2::verification_state='VERIFIED' then $3 else verified_at end,evidence_id=coalesce(evidence_id,$4::uuid)":i.targetType==="CONTACT_ROUTE"?",last_verified_at=case when $2::verification_state='VERIFIED' then $3 else last_verified_at end,evidence_id=coalesce(evidence_id,$4::uuid)":"";const params=i.targetType==="CLAIM"?[i.targetId,resulting,i.decidedAt.toISOString(),i.reviewerId]:contact?[i.targetId,resulting,i.decidedAt.toISOString(),primary]:[i.targetId,resulting,i.decidedAt.toISOString()];await this.c.query(`update ${targets[i.targetType].table} set verification_state=$2::verification_state${extra},updated_at=$3 where id=$1`,params)}await this.c.query("commit");return{...map(q.rows[0]),evidenceIds:i.evidenceIds}}catch(error){await this.c.query("rollback");throw error}}
async history(type:VerificationTargetType,id:string,asOf?:Date){const q=await this.c.query<R>("select d.*,coalesce(array_agg(e.evidence_id order by e.evidence_id)filter(where e.evidence_id is not null),'{}')evidence_ids from human_verification_decisions d left join human_verification_decision_evidence e on e.decision_id=d.id where d.target_type=$1 and d.target_id=$2 and($3::timestamptz is null or d.decided_at<=$3)group by d.id order by d.decided_at,d.created_at,d.id",[type,id,asOf?.toISOString()??null]);return q.rows.map(map)}
async queue(opportunityId:string,asOf:Date):Promise<ReviewCandidate[]>{const q=await this.c.query<{target_type:VerificationTargetType;target_id:string;reason:string;priority:number;due_at:string|Date|null;latest_decision:HumanVerificationDecision|null}>(`with candidates as(
select 'OPPORTUNITY_CONFLICT'::human_verification_target_type target_type,o.id target_id,'Opportunity has conflicting evidence' reason,10 priority,o.verification_due_at due_at from opportunities o where o.id=$1 and exists(select 1 from opportunity_completeness_snapshots s where s.opportunity_id=o.id and s.evaluated_at<=$2 and 'CONFLICTING_EVIDENCE'=any(s.gaps))
union all select 'CLAIM',c.id,'Material claim is unverified, stale, or due',20,c.verification_due_at from claims c join opportunity_claims x on x.claim_id=c.id where x.opportunity_id=$1 and(c.verification_state in('UNVERIFIED','STALE')or c.stale_after<=$2 or c.verification_due_at<=$2)
union all select 'COMPANY_RESOLUTION',a.id,'Company identity resolution requires review',15,null from company_resolution_audits a join opportunity_companies x on x.company_id=a.candidate_company_id where x.opportunity_id=$1
union all select 'COMPANY_ROLE',r.id,'Company role requires review',30,null from company_roles r join opportunity_company_roles x on x.company_role_id=r.id where x.opportunity_id=$1 and r.verification_state='UNVERIFIED'
union all select 'PROJECT',o.project_id,'Project identity requires review',35,o.verification_due_at from opportunities o where o.id=$1 and o.project_id is not null
union all select 'MANPOWER_ACCEPTANCE',m.id,'Manpower acceptance requires human review',40,m.valid_until from manpower_acceptance_evaluations m where(m.opportunity_id=$1 or(m.opportunity_id is null and m.company_id in(select company_id from opportunity_companies where opportunity_id=$1)))and m.evaluated_at<=$2 and(m.result<>'VERIFIED'or m.valid_until<=$2)
union all select 'CONTACT_PERSON',p.id,'Contact person is unverified, stale, or due',50,p.verification_due_at from contact_people p join opportunity_contact_people x on x.contact_person_id=p.id where x.opportunity_id=$1 and(p.verification_state in('UNVERIFIED','STALE')or p.stale_after<=$2 or p.verification_due_at<=$2)
union all select 'CONTACT_ROUTE',r.id,'Contact route authority is unverified, stale, or due',60,r.verification_due_at from contact_routes r join opportunity_contact_routes x on x.contact_route_id=r.id where x.opportunity_id=$1 and(r.verification_state in('UNVERIFIED','STALE')or r.stale_after<=$2 or r.verification_due_at<=$2)
),ranked as(select c.*,d.decision latest_decision,row_number()over(partition by c.target_type,c.target_id order by d.decided_at desc nulls last,d.created_at desc nulls last)rn from candidates c left join human_verification_decisions d on d.target_type=c.target_type and d.target_id=c.target_id and d.decided_at<=$2)select target_type,target_id,reason,priority,due_at,latest_decision from ranked where rn=1 and coalesce(latest_decision::text,'')not in('VERIFY','REJECT') order by priority,target_type,target_id`,[opportunityId,asOf.toISOString()]);return q.rows.map(r=>({targetType:r.target_type,targetId:r.target_id,reason:r.reason,priority:r.priority,priorityReason:`P${r.priority}: ${r.reason}`,verificationDueAt:r.due_at?new Date(r.due_at):null,latestDecision:r.latest_decision}))}
}
