import{createHash}from"node:crypto";import{readFile}from"node:fs/promises";import{resolve}from"node:path";import{PGlite}from"@electric-sql/pglite";import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{CONTACT_ROUTE_GRADES}from"../../domain/contact";import{buildExplicitContactCandidates}from"../../server/contacts/builders/explicit-contact-builder";import{PostgresContactRepository}from"../../server/repositories/contact/postgres-contact-repository";import type{SqlClient}from"../../server/repositories/evidence/postgres-evidence-repository";import{PostgresEvidenceRepository}from"../../server/repositories/evidence/postgres-evidence-repository";import{ContactService,normalizeRouteTarget}from"../../server/services/contact/contact-service";
const now=new Date("2026-08-20T12:00:00Z");const migrations=["20260817010000_canonical_model.sql","20260817020000_evidence_provenance.sql","20260817030000_source_registry_compliance.sql","20260817040000_controlled_ingestion.sql","20260817050000_claim_assertions.sql","20260817060000_company_resolution.sql","20260817070000_manpower_acceptance.sql","20260817080000_contacts_routes.sql"];
describe("contacts and contact routes",()=>{let db:PGlite,repo:PostgresContactRepository,evidenceRepo:PostgresEvidenceRepository,service:ContactService,seq=0;
beforeAll(async()=>{db=new PGlite();for(const m of migrations)await db.exec(await readFile(resolve(process.cwd(),"supabase/migrations",m),"utf8"));const c=db as unknown as SqlClient;repo=new PostgresContactRepository(c);evidenceRepo=new PostgresEvidenceRepository(c);service=new ContactService(repo,()=>now);});afterAll(async()=>db.close());
async function ctx(){seq++;const s=await db.query<{id:string}>("insert into sources(name) values($1) returning id",[`Contact source ${seq}`]);const e=await evidenceRepo.create({sourceId:s.rows[0].id,sourceUrl:`https://fixture/contact/${seq}`,capturedAt:now,captureMethod:"HTTP_FETCH",contentHash:createHash("sha256").update(`contact-${seq}`).digest("hex"),payloadSizeBytes:20});const c=await db.query<{id:string}>("insert into companies(common_name) values($1) returning id",[`Contact Co ${seq}`]);return{companyId:c.rows[0].id,evidenceId:e.id};}
async function verifiedRoute(overrides:Record<string,unknown>={}){const c=await ctx();const r=await service.createRoute({companyId:c.companyId,routeType:"PROFESSIONAL_EMAIL",target:`person${seq}@example.com`,evidenceId:c.evidenceId,verificationState:"VERIFIED",lastVerifiedAt:now,observedAt:now,lifecycle:"ACTIVE",...overrides});return{...c,route:r};}
it("keeps person and route as separate records",async()=>{const c=await ctx();const p=await service.createPerson({companyId:c.companyId,fullName:"Jane Doe",title:"Craft Recruiter",contactFunction:"CRAFT_RECRUITER",evidenceId:c.evidenceId,observedAt:now});const r=await service.createRoute({companyId:c.companyId,contactPersonId:p.id,routeType:"PROFESSIONAL_EMAIL",target:"jane@example.com",evidenceId:c.evidenceId,observedAt:now});expect(r.contactPersonId).toBe(p.id);expect(r.id).not.toBe(p.id);});
it("does not create a person from a corporate inbox",()=>{const c=buildExplicitContactCandidates({companyId:"c",evidenceId:"e",observedAt:now,text:"Contact Us: info@example.com"});expect(c.people).toEqual([]);expect(c.routes[0].routeType).toBe("CORPORATE_EMAIL");});
it("keeps a named recruiter unverified and without inferred authority",async()=>{const c=await ctx();const x=buildExplicitContactCandidates({...c,observedAt:now,text:"Jane Doe — Craft Recruiter\nEmail: jane@example.com"});const p=await service.createPerson(x.people[0]);expect(p).toMatchObject({contactFunction:"CRAFT_RECRUITER",verificationState:"UNVERIFIED"});expect(x.people[0].metadata).not.toHaveProperty("authority");});
it("never grades a main office phone A",async()=>{const{route}=await verifiedRoute({routeType:"OFFICE_PHONE",target:"(571) 379-6040"});expect((await service.grade({route,personFunction:"OPERATIONS",authorityExplicit:true})).grade).toBe("D");});
it("never grades careers email A merely because verified",async()=>{const{route}=await verifiedRoute({routeType:"RECRUITER_EMAIL",target:"careers@example.com"});expect((await service.grade({route,personFunction:"RECRUITER",authorityExplicit:true})).grade).toBe("D");});
it("allows A only for verified direct relevant route with explicit authority",async()=>{const{route}=await verifiedRoute();const g=await service.grade({route,personFunction:"WORKFORCE",authorityExplicit:true});expect(g).toMatchObject({grade:"A",ruleVersion:"contact-route-grade@1.0.0"});});
it("grades procurement department routes B and official portal routes C",async()=>{const a=await verifiedRoute({routeType:"PROCUREMENT_EMAIL",target:"procurement@example.com"});const b=await verifiedRoute({routeType:"SUPPLIER_PORTAL",target:"https://example.com/vendor"});expect((await service.grade({route:a.route})).grade).toBe("B");expect((await service.grade({route:b.route})).grade).toBe("C");});
it("uses explicit grade values without ordinal arithmetic",()=>{expect(CONTACT_ROUTE_GRADES).toEqual(["A","B","C","D","E"]);expect(CONTACT_ROUTE_GRADES.every(v=>typeof v==="string")).toBe(true);});
it("rejects verified people and routes without provenance",async()=>{const c=await ctx();await expect(service.createPerson({companyId:c.companyId,fullName:"No Evidence",contactFunction:"OTHER",verificationState:"VERIFIED",observedAt:now})).rejects.toThrow(/evidence/);await expect(service.createRoute({companyId:c.companyId,routeType:"CORPORATE_EMAIL",target:"x@example.com",verificationState:"VERIFIED",observedAt:now})).rejects.toThrow(/evidence/);});
it("automated candidates default UNVERIFIED",async()=>{const c=await ctx();const x=buildExplicitContactCandidates({...c,observedAt:now,text:"Jane Doe — Recruiter\nEmail jane@example.com"});expect((await service.createPerson(x.people[0])).verificationState).toBe("UNVERIFIED");expect((await service.createRoute(x.routes[0])).verificationState).toBe("UNVERIFIED");});
it("supports multiple routes for one person and corporate routes without people",async()=>{const c=await ctx();const p=await service.createPerson({companyId:c.companyId,fullName:"Pat Lee",contactFunction:"PROCUREMENT",evidenceId:c.evidenceId,observedAt:now});await service.createRoute({companyId:c.companyId,contactPersonId:p.id,routeType:"PROFESSIONAL_EMAIL",target:"pat@example.com",evidenceId:c.evidenceId,observedAt:now});await service.createRoute({companyId:c.companyId,contactPersonId:p.id,routeType:"PROFESSIONAL_PHONE",target:"571-555-0100",evidenceId:c.evidenceId,observedAt:now});await service.createRoute({companyId:c.companyId,routeType:"CORPORATE_PHONE",target:"571-555-0199",evidenceId:c.evidenceId,observedAt:now});const rs=await repo.listRoutes(c.companyId);expect(rs).toHaveLength(3);expect(rs.filter(r=>r.contactPersonId===null)).toHaveLength(1);});
it("normalizes duplicate email and phone routes conservatively",async()=>{const c=await ctx();const one=await service.createRoute({companyId:c.companyId,routeType:"CORPORATE_EMAIL",target:" INFO@Example.COM ",evidenceId:c.evidenceId,observedAt:now});const two=await service.createRoute({companyId:c.companyId,routeType:"CORPORATE_EMAIL",target:"info@example.com",evidenceId:c.evidenceId,observedAt:now});expect(two.id).toBe(one.id);expect(normalizeRouteTarget("CORPORATE_PHONE","(571) 379-6040")).toBe("+15713796040");});
it("does not merge ambiguous same-name people across evidence",async()=>{const a=await ctx();const b=await ctx();const companyId=a.companyId;const p1=await service.createPerson({companyId,fullName:"Alex Smith",title:"Manager",contactFunction:"OTHER",evidenceId:a.evidenceId,observedAt:now});const p2=await service.createPerson({companyId,fullName:"Alex Smith",title:"Manager",contactFunction:"OTHER",evidenceId:b.evidenceId,observedAt:now});expect(p2.id).not.toBe(p1.id);});
it("does not treat stale routes as current high grade",async()=>{const{route}=await verifiedRoute({staleAfter:new Date("2026-08-19T00:00:00Z")});expect((await service.grade({route,personFunction:"WORKFORCE",authorityExplicit:true})).grade).toBe("E");expect(await service.currentGrade({...route,routeGrade:"A"})).toBe("E");});
it("retains historical grade snapshots",async()=>{const{route}=await verifiedRoute();await service.grade({route,personFunction:"WORKFORCE",authorityExplicit:true});await service.grade({route,personFunction:"OTHER",authorityExplicit:false});const h=await repo.listGrades(route.id);expect(h.map(x=>x.grade)).toEqual(["A","E"]);await expect(db.query("delete from contact_route_grade_evaluations where contact_route_id=$1",[route.id])).rejects.toThrow(/append-only/);});
it("requires explicit evidence for Spanish or bilingual status",async()=>{const c=await ctx();await expect(service.createPerson({companyId:c.companyId,fullName:"Juan García",contactFunction:"OTHER",languageStatus:"SPANISH_CONFIRMED",evidenceId:c.evidenceId,observedAt:now})).rejects.toThrow(/language/);const x=buildExplicitContactCandidates({...c,observedAt:now,text:"Juan García — Procurement Manager\nBilingual English and Spanish"});expect(x.people[0].languageStatus).toBe("BILINGUAL_CONFIRMED");expect(x.people[0].languageEvidenceId).toBe(c.evidenceId);});
it("never infers language from surname or location",()=>{const x=buildExplicitContactCandidates({companyId:"c",evidenceId:"e",observedAt:now,text:"Juan García — Operations Manager\nHouston, Texas"});expect(x.people[0].languageStatus).toBe("UNKNOWN");});
it("manpower acceptance informs relevance but cannot fabricate authority",async()=>{const{route}=await verifiedRoute();const g=await service.grade({route,personFunction:"WORKFORCE",authorityExplicit:false,manpowerAcceptance:"VERIFIED"});expect(g.grade).toBe("B");expect(g.reason).toContain("manpower acceptance");});
it("preserves evidence links and exposes no outreach or Phase 1J operations",async()=>{const c=await ctx();const p=await service.createPerson({companyId:c.companyId,fullName:"Evidence Person",contactFunction:"OTHER",evidenceId:c.evidenceId,observedAt:now});expect(await evidenceRepo.listLinksByEvidence(c.evidenceId)).toContainEqual(expect.objectContaining({target:{kind:"CONTACT_PERSON",id:p.id}}));expect(Object.getOwnPropertyNames(ContactService.prototype)).toEqual(["constructor","createPerson","createRoute","grade","currentGrade"]);});
});
