import type{CommercialConversionDossier,ConversionEvidenceInput,ConversionPriority,ConversionVerificationItem}from"../../../domain/commercial-conversion";
import{COMMERCIAL_CONVERSION_PRIORITY_RULE_VERSION,COMMERCIAL_CONVERSION_RULE_VERSION}from"../../../domain/commercial-conversion";
import{SOURCE_ORGANIZATION_PROVENANCE_RULE_VERSION}from"../../../domain/commercial-conversion";
import type{OrganizationProvenance,SourceOrganizationProfile}from"../../../domain/commercial-conversion";
import type{EligibilityResult,EligibilitySnapshot}from"../../../domain/eligibility";
import type{OpportunityGraph}from"../../../domain/opportunity";
import{NO_ACTIONABILITY_EVIDENCE}from"../../../domain/opportunity-actionability";
import type{EligibilityRepository}from"../../repositories/eligibility/eligibility-repository";
import type{ScoringRepository}from"../../repositories/scoring/scoring-repository";
import{activeHotLeadsForGraph}from"../active-lead/active-lead-service";
import{assessActionability,gatedCommercialActionForGraph}from"../opportunity-actionability/opportunity-actionability-service";
import{EligibilityService}from"../eligibility/eligibility-service";
import{ScoringService}from"../scoring/scoring-service";

const noopEligibility:EligibilityRepository={async activeEvidenceIds(ids){return ids},async save(r:EligibilityResult):Promise<EligibilitySnapshot>{return{...r,id:"unused",createdAt:r.evaluatedAt}},async list(){return[]}};
const noopScoring:ScoringRepository={async save(r){return{...r,id:"unused",createdAt:r.evaluatedAt}},async list(){return[]}};
const unique=(xs:string[])=>[...new Set(xs)].sort();

export const DISCOVERY_SOURCE_ORGANIZATION_PROFILES:Record<string,Omit<SourceOrganizationProfile,"sourceUrl"|"observedAt">>={
  ibew716:{sourceId:"ibew716",identityClass:"UNION_DISPATCH_SOURCE",organization:"IBEW Local 716",ownershipEvidence:"Official union dispatch board; union identity is not the employer."},
  strike:{sourceId:"strike",identityClass:"FIRST_PARTY_EMPLOYER_SOURCE",organization:"Strike",ownershipEvidence:"Official Strike-branded JazzHR board at strike.applytojob.com."},
  trillium:{sourceId:"trillium",identityClass:"STAFFING_SOURCE",organization:"Trillium Staffing",ownershipEvidence:"Official Trillium Staffing jobs search; source identity establishes staffing intermediary only."},
  bechtel:{sourceId:"bechtel",identityClass:"FIRST_PARTY_EMPLOYER_SOURCE",organization:"Bechtel",ownershipEvidence:"Official Bechtel-branded SAP SuccessFactors career search."},
};

export function resolveOrganizationProvenance(directOrganization:string|null,profile:SourceOrganizationProfile):OrganizationProvenance{
  const direct=directOrganization?.trim()||null,inherited=profile.organization?.trim()||null,conflicts:string[]=[];
  if(direct&&inherited&&profile.identityClass!=="UNION_DISPATCH_SOURCE"&&direct.toLowerCase()!==inherited.toLowerCase())conflicts.push(`direct listing organization "${direct}" conflicts with source identity "${inherited}"`);
  if(direct){const dispatch=profile.identityClass==="UNION_DISPATCH_SOURCE";return{organization:direct,basis:dispatch?"ROW_STATED_DISPATCH_CONTRACTOR":"DIRECT_LISTING",sourceId:profile.sourceId,sourceUrl:profile.sourceUrl,sourceIdentityClass:profile.identityClass,evidenceBasis:"Organization stated directly in the captured listing row; direct evidence outranks inherited identity.",observedAt:profile.observedAt,derivationRuleVersion:SOURCE_ORGANIZATION_PROVENANCE_RULE_VERSION,conflicts,companyRole:"UNKNOWN",employer:direct,contractor:dispatch?direct:null,staffingIntermediary:null}}
  if(inherited&&profile.identityClass==="FIRST_PARTY_EMPLOYER_SOURCE")return{organization:inherited,basis:"VERIFIED_FIRST_PARTY_SOURCE_IDENTITY",sourceId:profile.sourceId,sourceUrl:profile.sourceUrl,sourceIdentityClass:profile.identityClass,evidenceBasis:profile.ownershipEvidence,observedAt:profile.observedAt,derivationRuleVersion:SOURCE_ORGANIZATION_PROVENANCE_RULE_VERSION,conflicts,companyRole:"PROBABLE_END_EMPLOYER",employer:inherited,contractor:null,staffingIntermediary:null};
  if(inherited&&profile.identityClass==="STAFFING_SOURCE")return{organization:inherited,basis:"VERIFIED_STAFFING_SOURCE_IDENTITY",sourceId:profile.sourceId,sourceUrl:profile.sourceUrl,sourceIdentityClass:profile.identityClass,evidenceBasis:profile.ownershipEvidence,observedAt:profile.observedAt,derivationRuleVersion:SOURCE_ORGANIZATION_PROVENANCE_RULE_VERSION,conflicts,companyRole:"STAFFING_COMPANY",employer:inherited,contractor:null,staffingIntermediary:inherited};
  return{organization:null,basis:"UNKNOWN",sourceId:profile.sourceId,sourceUrl:profile.sourceUrl,sourceIdentityClass:profile.identityClass,evidenceBasis:profile.ownershipEvidence,observedAt:profile.observedAt,derivationRuleVersion:SOURCE_ORGANIZATION_PROVENANCE_RULE_VERSION,conflicts,companyRole:"UNKNOWN",employer:null,contractor:null,staffingIntermediary:null};
}

export function prioritizeCommercialConversion(input:ConversionEvidenceInput):ConversionPriority{
  const reasons:string[]=[];let score=25;
  const add=(n:number,reason:string)=>{score+=n;reasons.push(`+${n} ${reason}`)};
  if(input.employer)add(12,"explicit employer");if(input.signal.location)add(8,"specific location");if(input.wage)add(8,"explicit wage");if(input.schedule)add(6,"explicit schedule/hours");if(input.perDiemOrIncentive)add(5,"explicit per-diem/incentive");if(input.headcount!==null)add(5,"explicit headcount");if(input.project)add(8,"explicit project");if(input.buyer)add(8,"explicit buyer/counterpart");if(input.acceptance)add(input.acceptance.verificationState==="VERIFIED"?12:4,input.acceptance.verificationState==="VERIFIED"?"verified AF-01":"AF-01 candidate preserved");if(input.contacts.length)add(Math.min(10,input.contacts.length*3),"public contact/vendor pathway evidence");
  const blockers=[!input.buyer,!input.acceptance,!input.contacts.length,input.actionability.explicitStatus===null&&!input.actionability.deadlines.length,input.conflicts.length>0].filter(Boolean).length;
  score=Math.max(0,Math.min(100,score-blockers*3));return{score,reasons,blockerCount:blockers,ruleVersion:COMMERCIAL_CONVERSION_PRIORITY_RULE_VERSION};
}

export function conversionGraph(input:ConversionEvidenceInput):OpportunityGraph{
  const opportunityId=`conversion:${input.signal.externalId}`,asOf=input.signal.observedAt;
  const acceptance=input.acceptance?.verificationState==="VERIFIED"&&input.acceptance.accepted===true?{id:input.acceptance.id,result:"VERIFIED",valid_until:input.acceptance.validUntil}:input.acceptance?{id:input.acceptance.id,result:"INSUFFICIENT_EVIDENCE",valid_until:input.acceptance.validUntil}:null;
  const company=input.employer?{id:`company:${input.signal.externalId}`,name:input.employer}:null;
  const routes=input.contacts.map(c=>({id:c.id,route_type:c.routeType,target:c.target,verification_state:c.verificationState,lifecycle:c.verificationState==="STALE"?"STALE":"ACTIVE",stale_after:c.staleAfter,last_seen_at:c.observedAt}));
  return{opportunity:{id:opportunityId,identityKey:opportunityId,projectId:input.project?`project:${input.signal.externalId}`:null,unresolvedCompanyContext:input.employer?null:input.signal.organization,title:input.signal.title,lifecycle:"UNKNOWN",firstSeenAt:asOf,lastSeenAt:asOf,staleAfter:null,verificationDueAt:null,metadata:{discoverySignalId:input.signal.signalId}},demandSignals:[{id:input.signal.signalId,raw_evidence_id:input.evidenceIds[0]??null,stale_after:null,headcount:input.headcount,schedule:input.schedule,last_seen_at:asOf}],claims:[],companies:company?[company]:[],companyRoles:input.companyRole!=="UNKNOWN"&&company?[{id:`role:${input.signal.externalId}`,role:input.companyRole,evidence_ids:input.companyRoleEvidenceIds}]:[],project:input.project?{id:`project:${input.signal.externalId}`,name:input.project}:null,acceptance,vendorRoutes:[],contactPeople:[],contactRoutes:routes,routeGrades:input.contacts.map(c=>({id:`grade:${c.id}`,contact_route_id:c.id,grade:c.gradeCandidate})),evidence:input.evidenceIds.map(id=>({id})),verificationReviews:[],gaps:[...(!input.employer?["MISSING_COMPANY"as const]:[]),...(input.companyRole==="UNKNOWN"?["MISSING_COMPANY_ROLE"as const]:[]),...(!input.project?["MISSING_PROJECT"as const]:[]),...(!acceptance||acceptance.result!=="VERIFIED"?["MISSING_MANPOWER_ACCEPTANCE"as const]:[]),...(!routes.length?["MISSING_CONTACT"as const,"MISSING_ACTIONABLE_ROUTE"as const]:[]),...(input.conflicts.length?["CONFLICTING_EVIDENCE"as const]:[])],conflicts:[...input.conflicts],asOf,descriptiveOnly:true};
}

function verificationQueue(input:ConversionEvidenceInput):ConversionVerificationItem[]{
  const q:ConversionVerificationItem[]=[];const item=(kind:ConversionVerificationItem["kind"],state:string,evidence:string[],affectsEligibility:boolean,affectsActiveHot:boolean,action:string)=>q.push({kind,currentState:state,supportingEvidenceIds:evidence,conflictingEvidence:[...input.conflicts],affectsEligibility,affectsActiveHot,recommendedHumanAction:action});
  if(!input.buyer)item("VERIFY_BUYER","UNKNOWN",[],false,false,"Identify and evidence the commercial counterparty; do not infer it from the employer.");if(input.companyRole==="UNKNOWN")item("VERIFY_COMPANY_ROLE","UNKNOWN",input.companyRoleEvidenceIds,false,false,"Classify the employer role from authoritative evidence.");if(!input.project)item("IDENTIFY_PROJECT","UNKNOWN",[],false,false,"Find explicit project evidence or retain UNKNOWN.");if(!input.acceptance||input.acceptance.verificationState!=="VERIFIED")item("VERIFY_AF01",input.acceptance?.verificationState??"UNKNOWN",input.acceptance?.evidenceIds??[],true,true,"Human-review official external-manpower acceptance evidence.");
  for(const c of input.contacts){if(c.verificationState!=="VERIFIED")item("VERIFY_CONTACT_ROUTE",c.verificationState,c.evidenceIds,true,true,"Verify route ownership, currency, function, and applicability.");if(c.verificationState!=="VERIFIED"||c.gradeCandidate==="A")item("VERIFY_CONTACT_GRADE",`candidate ${c.gradeCandidate}`,c.evidenceIds,true,true,"Apply frozen grade rules; Grade A requires decision-path authority.")}
  if(!input.contacts.length)item("FIND_ACTIONABLE_CONTACT","UNKNOWN",[],true,true,"Find a public procurement/vendor/professional route.");if(input.actionability.explicitStatus===null&&!input.actionability.deadlines.length)item("VERIFY_TEMPORAL_STATUS","UNKNOWN",input.actionability.evidenceIds,false,true,"Find explicit status or deadline evidence.");if(input.conflicts.length)item("VERIFY_CONFLICT","UNRESOLVED",input.evidenceIds,true,true,"Resolve conflicting evidence through human review.");return q;
}

export function convertDiscoverySignal(input:ConversionEvidenceInput):CommercialConversionDossier{
  const g=conversionGraph(input),asOf=g.asOf;const eligibility=new EligibilityService({graph:async()=>g},noopEligibility,()=>asOf).assess(g,asOf);const snapshots:EligibilitySnapshot[]=eligibility.map(r=>({...r,id:`${g.opportunity.id}:${r.eligibilityType}`,createdAt:asOf}));const score=new ScoringService({graph:async()=>g},noopEligibility,noopScoring,()=>asOf).assess(g,snapshots,asOf);const gated=gatedCommercialActionForGraph(g,input.actionability??NO_ACTIONABILITY_EVIDENCE(g.opportunity.id),asOf);const hot=activeHotLeadsForGraph(g,input.actionability,asOf),priority=prioritizeCommercialConversion(input),queue=verificationQueue(input);const blockers=unique([...eligibility.flatMap(e=>e.blockingGaps),...assessActionability(input.actionability,asOf).blockers,...input.conflicts]);
  return{discoverySignalId:input.signal.signalId,sourceId:input.signal.sourceKey,sourceExternalId:input.signal.externalId,organization:input.organizationProvenance?.organization??input.signal.organization,role:input.signal.title,location:input.signal.location,employer:input.employer,companyRole:input.companyRole,organizationProvenance:input.organizationProvenance??null,project:input.project,buyer:input.buyer,economics:{wage:input.wage,perDiemOrIncentive:input.perDiemOrIncentive,schedule:input.schedule,headcount:input.headcount},acceptance:input.acceptance,contacts:[...input.contacts],temporalState:gated.actionability.state,evidenceIds:unique(input.evidenceIds),conflicts:[...input.conflicts],verificationQueue:queue,eligibility,score,commercialAction:gated.underlyingAction,activeHot:hot,conversionPriority:priority,conversionBlockers:blockers,failedConversion:!eligibility.some(e=>e.eligible),observedAt:input.signal.observedAt,ruleVersions:[COMMERCIAL_CONVERSION_RULE_VERSION,priority.ruleVersion,...(input.organizationProvenance?[input.organizationProvenance.derivationRuleVersion]:[]),...unique(eligibility.map(e=>e.ruleVersion)),score.ruleVersion,gated.actionability.ruleVersion]};
}

export type PreviewDecision={verifyAcceptance?:boolean;verifyContactIds?:string[];explicitStatus?:"OPEN"|"CLOSED"|"AWARDED"|"CANCELLED"};
export function previewConversionDecision(input:ConversionEvidenceInput,decision:PreviewDecision){const hypothetical:ConversionEvidenceInput={...input,acceptance:decision.verifyAcceptance&&input.acceptance?{...input.acceptance,verificationState:"VERIFIED",accepted:true}:input.acceptance,contacts:input.contacts.map(c=>decision.verifyContactIds?.includes(c.id)?{...c,verificationState:"VERIFIED"}:c),actionability:decision.explicitStatus?{...input.actionability,explicitStatus:decision.explicitStatus,explicitStatusFreshUntil:null}:input.actionability};const current=convertDiscoverySignal(input),ifVerified=convertDiscoverySignal(hypothetical);return{current:{eligibility:current.eligibility,score:current.score,action:current.commercialAction,activeHot:current.activeHot},ifVerified:{eligibility:ifVerified.eligibility,score:ifVerified.score,action:ifVerified.commercialAction,activeHot:ifVerified.activeHot},changed:JSON.stringify(current)!==JSON.stringify(ifVerified),persisted:false}}
export function rankConversionCohort(inputs:readonly ConversionEvidenceInput[],limit=5){return[...inputs].map(input=>({input,priority:prioritizeCommercialConversion(input)})).sort((a,b)=>b.priority.score-a.priority.score||a.input.signal.externalId.localeCompare(b.input.signal.externalId)).slice(0,limit)}
