import type{EligibilityReason,EligibilityResult,EligibilityType,RequirementResult}from"../../../domain/eligibility";import type{OpportunityGraph}from"../../../domain/opportunity";import type{EligibilityRepository}from"../../repositories/eligibility/eligibility-repository";
export const ELIGIBILITY_RULE_VERSION="eligibility@1.0.0";export const HOT_A_ROUTE_GRADES=new Set(["A","B","C"]);export const VAMO_ROUTE_GRADES=new Set(["A","B","C"]);export const HOT_B_ROUTE_GRADES=new Set(["A","B","C","D"]);export const HOT_B_ROUTE_TYPES=new Set(["RECRUITER_EMAIL","RECRUITER_PHONE","PROFESSIONAL_EMAIL","PROFESSIONAL_PHONE","PROFESSIONAL_PROFILE"]);
export interface OpportunityGraphLoader{graph(id:string,asOf:Date):Promise<OpportunityGraph>}
type X=Record<string,unknown>;const date=(v:unknown)=>v?new Date(String(v)):null;const id=(x:X)=>String(x.id);const latestReviews=(g:OpportunityGraph)=>{const m=new Map<string,X>();for(const r of g.verificationReviews)m.set(`${r.target_type}:${r.target_id}`,r);return m};
export class EligibilityService{constructor(private readonly graphs:OpportunityGraphLoader,private readonly repo:EligibilityRepository,private readonly clock:()=>Date=()=>new Date()){}
assess(g:OpportunityGraph,evaluatedAt:Date=this.clock()):EligibilityResult[]{const asOf=g.asOf,reviews=latestReviews(g),currentDemand=g.demandSignals.filter(d=>!date(d.stale_after)||date(d.stale_after)!>asOf),staleDemand=g.demandSignals.some(d=>!!date(d.stale_after)&&date(d.stale_after)!<=asOf);const provenance=currentDemand.length>0&&currentDemand.every(d=>!!d.raw_evidence_id)&&g.evidence.length>0;const conflictReview=reviews.get(`OPPORTUNITY_CONFLICT:${g.opportunity.id}`),conflictResolved=conflictReview?.decision==="VERIFY";const conflict=g.conflicts.length>0&&!conflictResolved;const nonFinal=[...reviews.values()].filter(r=>r.decision==="NEEDS_MORE_EVIDENCE"||r.decision==="DEFER"||r.decision==="REJECT");const humanOk=nonFinal.length===0;const company=g.companies.length>0,approvedUnresolved=!!g.opportunity.unresolvedCompanyContext&&conflictResolved;const acceptance=g.acceptance,acceptanceVerified=acceptance?.result==="VERIFIED",acceptanceStale=!!acceptance&&!!date(acceptance.valid_until)&&date(acceptance.valid_until)!<=asOf;const grades=new Map(g.routeGrades.map(x=>[String(x.contact_route_id),String(x.grade)]));const currentRoutes=g.contactRoutes.filter(r=>r.lifecycle!=="STALE"&&r.lifecycle!=="DISABLED"&&(!date(r.stale_after)||date(r.stale_after)!>asOf));const staleRoute=g.contactRoutes.some(r=>!!date(r.stale_after)&&date(r.stale_after)!<=asOf);const routeVerified=(r:X)=>r.verification_state==="VERIFIED"||reviews.get(`CONTACT_ROUTE:${r.id}`)?.decision==="VERIFY";const route=(set:Set<string>)=>currentRoutes.some(r=>set.has(grades.get(String(r.id))??"")&&routeVerified(r));const hotBPath=currentRoutes.some(r=>HOT_B_ROUTE_GRADES.has(grades.get(String(r.id))??"")&&HOT_B_ROUTE_TYPES.has(String(r.route_type))&&routeVerified(r));const economicsReady=currentDemand.some(d=>d.base_pay_min!=null&&d.base_pay_max!=null&&d.pay_currency!=null);const reviewed={evidenceIds:g.evidence.map(id),claimIds:g.claims.map(id),contactIds:g.contactPeople.map(id),routeIds:g.contactRoutes.map(id),reviewDecisionIds:g.verificationReviews.map(id)};
const make=(type:EligibilityType,requirements:RequirementResult[]):EligibilityResult=>{const failed=requirements.filter(x=>!x.passed).map(x=>x.code),passed=requirements.filter(x=>x.passed).map(x=>x.code);return{opportunityId:g.opportunity.id,evaluatedAt,asOf,ruleVersion:ELIGIBILITY_RULE_VERSION,eligibilityType:type,eligible:failed.length===0,passedRequirements:passed,failedRequirements:failed,blockingGaps:failed,reviewedIdentifiers:reviewed,requirements,explanation:failed.length?`${type} blocked: ${failed.join(", ")}`:`${type} requirements satisfied`,economicsReady}};const req=(code:EligibilityReason,passed:boolean,detail:string,identifiers:string[]=[]):RequirementResult=>({code,passed,detail,identifiers});
const common=[req("CURRENT_DEMAND_REQUIRED",currentDemand.length>0,"At least one current demand signal is required",currentDemand.map(id)),req("STALE_DEMAND",!staleDemand,"Required demand must not be stale"),req("PROVENANCE_REQUIRED",provenance,"Current demand requires evidence provenance",g.evidence.map(id)),req("HUMAN_VERIFICATION_REQUIRED",humanOk,"Required reviews must resolve to VERIFY",[...reviews.values()].map(id)),req("MATERIAL_CONFLICT_PRESENT",!conflict,"Material conflicts require evidence-backed human resolution")];
const vamo=make("VAMO_ELIGIBLE",[...common,req("COMPANY_REQUIRED",company||approvedUnresolved,"Canonical company or approved unresolved commercial context required",g.companies.map(id)),req("ACTIONABLE_CONTACT_REQUIRED",route(VAMO_ROUTE_GRADES),"Explicit route grade A, B, or C required",currentRoutes.map(id)),req("STALE_CONTACT_ROUTE",!staleRoute,"Required route must be current")]);
const hotA=make("HOT_A_ELIGIBLE",[...common,req("COMPANY_REQUIRED",company,"Canonical company required",g.companies.map(id)),req("MANPOWER_ACCEPTANCE_REQUIRED",!!acceptanceVerified&&!acceptanceStale,"Current VERIFIED external manpower acceptance is mandatory",acceptance?[id(acceptance)]:[]),req("STALE_ACCEPTANCE",!acceptanceStale,"Acceptance must not be expired"),req("ACTIONABLE_CONTACT_REQUIRED",route(HOT_A_ROUTE_GRADES),"Explicit route grade A, B, or C required",currentRoutes.map(id)),req("STALE_CONTACT_ROUTE",!staleRoute,"Required route must be current")]);
const hotB=make("HOT_B_ELIGIBLE",[...common,req("HOT_B_INTELLIGENCE_PATH_PRESENT",hotBPath,"Verified recruiter or professional path with explicit grade A-D required",currentRoutes.map(id)),req("UNKNOWN_BUYER",company||!g.project,"Buyer may remain unknown but must not be fabricated"),req("STALE_CONTACT_ROUTE",!staleRoute,"Required intelligence route must be current")]);return[vamo,hotA,hotB]}
async evaluate(opportunityId:string,asOf:Date=this.clock()){const graph=await this.graphs.graph(opportunityId,asOf),active=new Set(await this.repo.activeEvidenceIds(graph.evidence.map(id),asOf));graph.evidence=graph.evidence.filter(e=>active.has(id(e)));const results=this.assess(graph,this.clock());return Promise.all(results.map(x=>this.repo.save(x)))}history(opportunityId:string,asOf?:Date){return this.repo.list(opportunityId,asOf)}}
